### ISSUE TITLE
bug: ReadTimeout: timed out

### ISSUE THREAD

**Issue by lucasiscovici** [langfuse/langfuse#1217]
### Describe the bug

Giving up execute_task_with_backoff(...) after 3 tries (httpx.ReadTimeout: timed out)
Giving up execute_task_with_backoff(...) after 3 tries (httpx.ReadTimeout: timed out)
ERROR:backoff:Giving up execute_task_with_backoff(...) after 3 tries (httpx.ReadTimeout: timed out)
ERROR:langfuse:error uploading: timed out
Traceback (most recent call last):
  File "/Users/liscovici/Library/Caches/pypoetry/virtualenvs/eval-llm--fJEs3ezU-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/Users/liscovici/Library/Caches/pypoetry/virtualenvs/eval-llm--fJEs3ezU-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/Users/liscovici/Library/Caches/pypoetry/virtualenvs/eval-llm--fJEs3ezU-py3.10/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/Users/liscovici/Library/Caches/pypoetry/virtualenvs/eval-llm--fJEs3ezU-py3.10/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/Users/liscovici/Library/Caches/pypoetry/virtualenvs/eval-llm--fJEs3ezU-py3.10/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/Users/liscovici/Library/Caches/pypoetry/virtualenvs/eval-llm--fJEs3ezU-py3.10/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 132, in handle_request
    raise exc
  File "/Users/liscovici/Library/Caches/pypoetry/virtualenvs/eval-llm--fJEs3ezU-py3.10/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 110, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/Users/liscovici/Library/Caches/pypoetry/virtualenvs/eval-llm--fJEs3ezU-py3.10/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 175, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/Users/liscovici/Library/Caches/pypoetry/virtualenvs/eval-llm--fJEs3ezU-py3.10/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 211, in _receive_event
    data = self._network_stream.read(
  File "/Users/liscovici/Library/Caches/pypoetry/virtualenvs/eval-llm--fJEs3ezU-py3.10/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "/Users/liscovici/miniconda/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/liscovici/Library/Caches/pypoetry/virtualenvs/eval-llm--fJEs3ezU-py3.10/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out

### To reproduce

i think a lot of metadata

**Comment by thenicekat** [comment]
Did you ever get to solving this? If yes, how do you solve this?
