### ISSUE TITLE
bug: ImportError on import: from langfuse.callback import CallbackHandler 

### ISSUE THREAD

**Issue by mjoyce-nr** [langfuse/langfuse#1274]
### Describe the bug

024-02-27 15:57:30,325 - ERROR - Traceback (most recent call last):
  File "...., line 71, in plan
    from langfuse.callback import CallbackHandler
  File "/home/maria/miniconda3/envs/platform/lib/python3.9/site-packages/langfuse/callback.py", line 16, in <module>
    from langfuse.extract_model import _extract_model_name
  File "/home/maria/miniconda3/envs/platform/lib/python3.9/site-packages/langfuse/extract_model.py", line 4, in <module>
    from langchain_community.chat_models import (
ImportError: cannot import name 'ChatDeepInfra' from 'langchain_community.chat_models' (/home/maria/miniconda3/envs/platform/lib/python3.9/site-packages/langchain_community/chat_models/__init__.py)

### To reproduce

import this class in python code; from langfuse.callback import CallbackHandler 

### Additional information

I upgraded to langfuse [release 2.11.0](https://github.com/langfuse/langfuse-python/releases/tag/v2.11.0) and this started happening.

**Comment by maxdeichmann** [comment]
Hi @mjoyce-nr, thanks for raising this. Do you mind sharing your chain with me?

**Comment by danielsotopino** [comment]
Hi there, same problem here.

```
import constants
import os
import db_utils #agregado
from database import db #agregado
from dotenv import load_dotenv
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import Chroma
from langchain.chains import RetrievalQAWithSourcesChain
from langchain.retrievers.multi_query import MultiQueryRetriever
from langchain_openai.chat_models import ChatOpenAI
from langchain.prompts.chat import (
    ChatPromptTemplate,
    SystemMessagePromptTemplate,
    HumanMessagePromptTemplate,
)
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain

from langchain.vectorstores.pgvector import PGVector, DistanceStrategy
from langchain_community.vectorstores import Qdrant
import qdrant_client
from langchain_community.callbacks import get_openai_callback
from langfuse.callback import CallbackHandler

load_dotenv()


# langfuse_handler = CallbackHandler()

CONNECTION_STRING = PGVector.connection_string_from_db_params(
    driver=os.environ.get("PGVECTOR_DRIVER", "psycopg2"),
    host=os.environ.get("PGVECTOR_HOST", "localhost"),
    port=int(os.environ.get("PGVECTOR_PORT", "5432")),
    database=os.environ.get("PGVECTOR_DATABASE", "postgres"),
    user=os.environ.get("PGVECTOR_USER", "postgres"),
    password=os.environ.get("PGVECTOR_PASSWORD", "postgres"),
)

def count_tokens(chain, query):
    with get_openai_callback() as cb:
        result = chain(query)
    return {
        'result': result,
        'token_count': cb
    }

def get_chain(store, prompt, temperature=0):
    chain_type_kwargs = {"prompt": prompt}
    llm = ChatOpenAI(temperature=temperature)
    chain = RetrievalQAWithSourcesChain.from_chain_type(
        llm,
        chain_type="stuff", 
        retriever=MultiQueryRetriever.from_llm(retriever=store.as_retriever(), llm=llm),
        chain_type_kwargs=chain_type_kwargs,
        reduce_k_below_max_tokens=True,
        verbose=True
    )
    return chain

def get_chroma_db(store, embedding):
    return Chroma(persist_directory=store, embedding_function=embedding)

def get_pgvector_db(store, embedding):
    return PGVector(
        connection_string=CONNECTION_STRING,
        embedding_function=embedding,
        collection_name=store,
        distance_strategy=DistanceStrategy.EUCLIDEAN,
    )

def get_qdrant_db(store, embeddings):
    url = os.environ["QDRANT_URL"]
    client = qdrant_client.QdrantClient(url=url)
    qdrant = Qdrant(client=client, collection_name=store, embeddings=embeddings)
    return qdrant

# Tu tono de respuesta será cálido y apuntando a orientar al cliente.
# Tu tono de respuesta será formal, serio y directo con los clientes.
# Tu tono de respuesta será informal y lúdico con los clientes.

system_template="""
    ###INSTRUCTION###
    Usa la siguiente información y responde a las preguntas de los clientes.
    Tu tono de respuesta es formal, serio y directo con los clientes.
    Si no encuentras la respuesta en la información proporcionada, simplemente di "{fallback}.", no debes inventar una respuesta o buscar otras fuentes o serás penalizado.

    {summaries}
    """

system_chilean_template="""Traduce la siguiente información a lenguaje chileno
---
{prompt_answer}
"""

def send_chat(text, store, temperature=0, context_template=None, dialect=None, chatbot_id=None):
    embedding = OpenAIEmbeddings()
    vectordb = get_qdrant_db(store, embedding)

    fallback = "Perdón, no tengo la manera de responder a tu pregunta."

    if context_template == None:
        context_template = system_template

    context_template = context_template.replace('{fallback}', fallback)

    messages = [
        SystemMessagePromptTemplate.from_template(context_template),
        HumanMessagePromptTemplate.from_template("{question}")
    ]
    prompt = ChatPromptTemplate.from_messages(messages)

    chain = get_chain(vectordb, prompt, temperature)

    interaction_result = count_tokens(chain, {"question": text})

    if dialect == None:
        return interaction_result

    language_prompt = PromptTemplate(
        input_variables=["dialect", "prompt_answer"],
        template='''Traduce el siguiente texto a dialecto {dialect}:
        {prompt_answer}
        '''
    )

    llm = ChatOpenAI(temperature=temperature)
    language_chain = LLMChain(llm=llm, prompt=language_prompt)
    language_interaction_result = count_tokens(language_chain, {"dialect": dialect, "prompt_answer":interaction_result['result']['answer']})

    language_interaction_result['result']['answer'] = language_interaction_result['result']['text']
    language_interaction_result['token_count'].total_tokens += interaction_result['token_count'].total_tokens
    language_interaction_result['token_count'].prompt_tokens += interaction_result['token_count'].prompt_tokens
    language_interaction_result['token_count'].completion_tokens += interaction_result['token_count'].completion_tokens
    language_interaction_result['token_count'].successful_requests += interaction_result['token_count'].successful_requests
    language_interaction_result['token_count'].total_cost += interaction_result['token_count'].total_cost

    return language_interaction_result
```

**Comment by hassiebp** [comment]
Closing this issue as stale
