### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by qiankunli** [langfuse/langfuse#1375]
### Describe the bug

env: mac m1, pycharm 
langfuse=1.10.0
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/ext/ext_langfuse.py", line 1, in <module>
    from langfuse.client import Langfuse
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/langfuse/__init__.py", line 1, in <module>
    from .client import Langfuse
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/langfuse/client.py", line 11, in <module>
    from langfuse.api.client import FintoLangfuse
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/langfuse/api/__init__.py", line 3, in <module>
    from .resources import (
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/langfuse/api/resources/__init__.py", line 3, in <module>
    from . import (
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/langfuse/api/resources/commons/__init__.py", line 3, in <module>
    from .types import (
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/langfuse/api/resources/commons/types/__init__.py", line 3, in <module>
    from .create_event_request import CreateEventRequest
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/langfuse/api/resources/commons/types/create_event_request.py", line 6, in <module>
    from ....core.datetime_utils import serialize_datetime
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/langfuse/api/core/__init__.py", line 4, in <module>
    from .client_wrapper import AsyncClientWrapper, BaseClientWrapper, SyncClientWrapper
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/langfuse/api/core/client_wrapper.py", line 5, in <module>
    import httpx
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/httpx/_api.py", line 4, in <module>
    from ._client import Client
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/httpx/_client.py", line 30, in <module>
    from ._transports.default import AsyncHTTPTransport, HTTPTransport
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 30, in <module>
    import httpcore
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/httpcore/__init__.py", line 1, in <module>
    from ._api import request, stream
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/httpcore/_api.py", line 5, in <module>
    from ._sync.connection_pool import ConnectionPool
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/httpcore/_sync/__init__.py", line 1, in <module>
    from .connection import HTTPConnection
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 12, in <module>
    from .._synchronization import Lock
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/httpcore/_synchronization.py", line 11, in <module>
    import trio
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/trio/__init__.py", line 22, in <module>
    from ._core import TASK_STATUS_IGNORED as TASK_STATUS_IGNORED  # isort: split
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/trio/_core/__init__.py", line 21, in <module>
    from ._local import RunVar, RunVarToken
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/trio/_core/_local.py", line 9, in <module>
    from . import _run
  File "/Users/bytedance/PycharmProjects/epscp/model-001/app/venv/lib/python3.10/site-packages/trio/_core/_run.py", line 2800, in <module>
    raise NotImplementedError("unsupported platform")
NotImplementedError: unsupported platform
```

### To reproduce

env: mac m1, pycharm 
langfuse=1.10.0

**Comment by marcklingen** [comment]
1.10.0 is a very outdated version, try to upgrade and please confirm whether you are still getting this error

**Comment by marcklingen** [comment]
closing this for now, feel free to reopen if this is still relevant
