### ISSUE TITLE
bug: Error handling achat_stream 

### ISSUE THREAD

**Issue by adieyal** [langfuse/langfuse#1450]
### Describe the bug

I'm not sure if this is an issue with LangFuse, LlamaIndex, or my code. I get the following exception
```python
ERROR 2024-03-20 07:13:33,634 langfuse 244 Exception in adding task Object of type async_generator is not JSON serializable           
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/langfuse/task_manager.py", line 236, in add_task
    json.dumps(event, cls=EventSerializer)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/dist-packages/langfuse/serializer.py", line 55, in default
    return JSONEncoder.default(self, obj)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type async_generator is not JSON serializable
```

I tracked down the trace event to llama_index.core.agent.running.base.py.AgentRunner.astream_chat
```python
    @trace_method("chat")
    async def astream_chat(
        self,
        message: str,
        chat_history: Optional[List[ChatMessage]] = None,
        tool_choice: Optional[Union[str, dict]] = None,
    ) -> StreamingAgentChatResponse:
        # override tool choice is provided as input.
        if tool_choice is None:
            tool_choice = self.default_tool_choice
        with self.callback_manager.event(
            CBEventType.AGENT_STEP,
            payload={EventPayload.MESSAGES: [message]},
        ) as e:
            chat_response = await self._achat(
                message, chat_history, tool_choice, mode=ChatResponseMode.STREAM
            )
            assert isinstance(chat_response, StreamingAgentChatResponse)
            e.on_end(payload={EventPayload.RESPONSE: chat_response})
        return chat_response
```

The payload looks something like this:
```python
{<EventPayload.RESPONSE: 'response'>: StreamingAgentChatResponse(response='', sources=[ToolOutput(content=some output\n', tool_name='run_test', raw_input={'args': (), 'kwargs': {'message': 'test'}}, raw_output='Some output\n')], chat_stream=None, achat_stream=<async_generator object llm_chat_callback.<locals>.wrap.<locals>.wrapped_async_llm_chat.<locals>.wrapped_gen at 0x7fcda9451ca0>,
 source_nodes=[], _unformatted_response='', _queue=<queue.Queue object at 0x7fcda98e9430>, _aqueue=<Queue at 0x7fcda97db490 maxsize=0>, _is_function=False, _new_item_event=<asy
ncio.locks.Event object at 0x7fcda97dbb80 [set]>, _is_function_false_event=<asyncio.locks.Event object at 0x7fcda9494d30 [set]>, _is_function_not_none_thread_event=<threading.E
vent object at 0x7fcda9494e80>)}
```

### To reproduce

```python
from llama_index.agent.openai import OpenAIAgent
from langfuse.llama_index import LlamaIndexCallbackHandler
from llama_index.core.callbacks import CallbackManager

langfuse_handler = LlamaIndexCallbackHandler(user_id=1)
callback_manager = CallbackManager([langfuse_handler])

agent = OpenAIAgent.from_tools(tools, callback_manager=callback_manager)
response = await self._agent.astream_chat("Some output")
```

### Additional information

langfuse==2.20.3
llama-index-callbacks-langfuse==0.1.2

**Comment by adieyal** [comment]
Thanks - no issues so far - will update if it crops up again
