### ISSUE TITLE
Add support for async (ainvoke / acall / abatch) in Langchain Python Integration

### ISSUE THREAD

**Issue by Hokyjack** [langfuse/langfuse#1456]
### Describe the bug

I am using Langchain in my chatbot application, it uses Fast API + Langchain.
To provide a realtime for user, I need to use `acall` or `ainvoke` in my code, so the frontend can stream the output.
However it seems that Langfuse doesn't support asynchronous generation tracking.
Is it something that will be eventually added to Langfuse? 
It would really help, as the asynchronous chains are really hard to trace and track.

Thumbs app for a good work!

### To reproduce

Run any chain using async call (ainvoke / acall / agenerate)
E.g.:
```
# Add Langfuse handler as callback (classic and LCEL)
chain.ainvoke({"input": "Hello"}, config={"callbacks": [langfuse_handler]})
```

**Comment by marcklingen** [comment]
This isn't a bug but a limitation of the integration, see: https://langfuse.com/docs/integrations/langchain/tracing#supported-langchain-interfaces

Idea post here: https://github.com/orgs/langfuse/discussions/1212

Open for contributions on this!

**Comment by marcklingen** [comment]
Should be fairly easy to add here: https://github.com/langfuse/langfuse-python/blob/main/langfuse/callback/langchain.py

**Comment by SinghCoder** [comment]
@marcklingen , I was thinking of trying this as I need streaming on my end as well, but tell me one thing on current code. LangChain `BaseTracer` class provides all util helpers for interacting with "langchain" runs.. Then why did Langfuse tracer start with the BaseCallbackHandler instead?

The BaseTracer does a lot of heavy lifting of populating metadata etc.. And all you need is to implement `_persist_run` (this is kinda legacy which gets entire run tree in one go).. or implement other `_on_<X>_<Y>` methods as per need.. 

Can we move to those instead?

**Comment by marcklingen** [comment]
We are currently working on this, thanks for the pointer to `BaseTracer`. Currently there is not much documentation in addition to the SDK reference covering this interface.
This is interesting though: https://python.langchain.com/docs/modules/agents/how_to/streaming#using-callbacks-legacy

**Comment by maxdeichmann** [comment]
@Hokyjack thanks for the issue. Do you have a code example where your async implementation failed?

**Comment by RevanthMedukonduru** [comment]
Hello @hassiebp,  I can see still PR is open, Looking if there is any update:
> getting errors for Async based operations (ainvoke) - For replication please use standard `Langgraph implementation of  Map-reduce: https://python.langchain.com/docs/versions/migrating_chains/map_reduce_chain/`

`Error:`

ERROR:langfuse:UUID('1eb31fae-6164-48b5-8ba9-9d626defedfb')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/langfuse/callback/langchain.py", line 255, in on_chain_start
    self.runs[run_id] = self.runs[parent_run_id].span(**content)
KeyError: UUID('1eb31fae-6164-48b5-8ba9-9d626defedfb')
ERROR:langfuse:run not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/langfuse/callback/langchain.py", line 441, in on_chain_end
    raise Exception("run not found")
Exception: run not found
ERROR:langfuse:run not found

Looking forward for reply or update, thanks!

**Comment by ned9** [comment]
hey @marcklingen, looking at your reply over [here](https://github.com/orgs/langfuse/discussions/1212#discussioncomment-9049988) indicating that streaming support has been added for Langchain, can this be closed?

**Comment by marcklingen** [comment]
Thanks for the ping @ned9, this should work, we forgot to close this issue when releasing this.
