### ISSUE TITLE
bug:  Circular reference detected when using langgraph

### ISSUE THREAD

**Issue by BIGPPWONG** [langfuse/langfuse#1608]
### Describe the bug

ERROR:langfuse:Exception in adding task Circular reference detected
Traceback (most recent call last):
  File "/home/Documents/PythonProjects/multiAgentServer/.venv/lib/python3.10/site-packages/langfuse/task_manager.py", line 236, in add_task
    json.dumps(event, cls=EventSerializer)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/Documents/PythonProjects/multiAgentServer/.venv/lib/python3.10/site-packages/langfuse/serializer.py", line 82, in encode
    return super().encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected

### To reproduce

compiled_graph= workflow.compile()
await compiled_graph.ainvoke(inputs, config={"callbacks": callbacks })

### Additional information

I don't know excatly how this can be reproduce.

**Comment by marcklingen** [comment]
thanks for sharing, will resolve this soon in the python sdk

**Comment by DARK-art108** [comment]
I am also trying to add langfuse with langgraph any documentation is their to do that?
