### ISSUE TITLE
bug: 'GenerationChunk' object has no attribute 'message'

### ISSUE THREAD

**Issue by shenghann** [langfuse/langfuse#1905]
### Describe the bug

Error message observed:
```
Traceback (most recent call last):
  File "/home/shenlim/nav-ai-dev-debug/gen-ai/ai-navigator-test2/app/env/lib/python3.10/site-packages/langfuse/callback/langchain.py", line 677, in on_llm_end
    else _extract_raw_esponse(generation)
  File "/home/shenlim/nav-ai-dev-debug/gen-ai/ai-navigator-test2/app/env/lib/python3.10/site-packages/langfuse/callback/langchain.py", line 815, in _extract_raw_esponse
    else last_response.message.additional_kwargs
AttributeError: 'GenerationChunk' object has no attribute 'message'
```

### To reproduce

Using the observe decorator on a function that creates and runs a langchain QA chain
```
@observe()
async def aget_qa_chain():
    
    # setup langfuse handler
    langfuse_context.update_current_trace(
        session_id=session_id,
        user_id=user_id,
    )
    langfuse_handler = langfuse_context.get_current_langchain_handler()
```
This is how the callback handler is passed to `arun`
```
chain = load_qa_chain(vertex_llm_text, chain_type="stuff", prompt=PROMPT)
answer = await chain.arun({"input_documents": matching_engine_response, "question": question}, callbacks=[langfuse_handler])
```

### Additional information

langchain==0.1.7
langfuse==2.27.1

LLM: GCP Vertex AI text-bison

**Comment by marcklingen** [comment]
Thanks for reporting this!
