### ISSUE TITLE
bug: Langfuse Exception: parent run not found

### ISSUE THREAD

**Issue by Altaf-Axway** [langfuse/langfuse#2149]
### Describe the bug

I am using Langfuse to monitor a LangChain Chatbot using Ollama LLAMA3 model.
An error catch and logged by langfuse/callback/langchain.py

```
2024-05-25 18:35:21,554 DEBUG app: Condensed question: steps to create grafana alerts
2024-05-25 18:35:21,554 DEBUG app: Question: steps to create grafana alerts
2024-05-25 18:35:21,562 ERROR langfuse: parent run not found
Traceback (most recent call last):
  File "/Users/<my-user>/Desktop/WIP/.venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 518, in on_retriever_start
    raise Exception("parent run not found")
Exception: parent run not found
/Users/<my-user>/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2024-05-25 18:35:21,861 ERROR langfuse: run not found
Traceback (most recent call last):
  File "/Users/<my-user>/Desktop/WIP/.venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 544, in on_retriever_end
    raise Exception("run not found")
Exception: run not found
``` 

### To reproduce

ChatBot Code

```python
from langchain_elasticsearch import ElasticsearchStore
from langfuse.callback import CallbackHandler
from langfuse.decorators import langfuse_context, observe
from llm_integrations import get_llm
from elasticsearch_client import (
    elasticsearch_client,
    get_elasticsearch_chat_message_history,
)
from flask import render_template, stream_with_context, current_app
import json
import os


INDEX = os.getenv("ES_INDEX", "workplace-app-docs")
INDEX_CHAT_HISTORY = os.getenv(
    "ES_INDEX_CHAT_HISTORY", "workplace-app-docs-chat-history"
)
ELSER_MODEL = os.getenv("ELSER_MODEL", ".elser_model_2")
SESSION_ID_TAG = "[SESSION_ID]"
SOURCE_TAG = "[SOURCE]"
DONE_TAG = "[DONE]"

store = ElasticsearchStore(
    es_connection=elasticsearch_client,
    index_name=INDEX,
    strategy=ElasticsearchStore.SparseVectorRetrievalStrategy(model_id=ELSER_MODEL),
)


@stream_with_context
@observe()
def ask_question(question, session_id):
    yield f"data: {SESSION_ID_TAG} {session_id}\n\n"
    current_app.logger.debug("Chat session ID: %s", session_id)
    
    #langfuse_context.get_current_langchain_handler()

    langfuse_context.update_current_trace(
        name="test1",
        session_id=session_id,
    )
    #langfuse_context.get_current_langchain_handler()
    langfuse_handler = langfuse_context.get_current_langchain_handler()
    langfuse_handler = CallbackHandler(
    public_key="<pub_key>",
    secret_key="<secret_key>",
    host="https://cloud.langfuse.com",
    session_id=session_id
    )
    
    # langfuse_context.get_current_langchain_handler()

    chat_history = get_elasticsearch_chat_message_history(
        INDEX_CHAT_HISTORY, session_id
    )

    if len(chat_history.messages) > 0:
        # create a condensed question
        condense_question_prompt = render_template(
            "condense_question_prompt.txt",
            question=question,
            chat_history=chat_history.messages,
        )
        condensed_question = get_llm().invoke(condense_question_prompt, config={"callbacks": [langfuse_handler]}).content
    else:
        condensed_question = question

    current_app.logger.debug("Condensed question: %s", condensed_question)
    current_app.logger.debug("Question: %s", question)

    docs = store.as_retriever().invoke(condensed_question, config={"callbacks": [langfuse_handler]})
    for doc in docs:
        doc_source = {**doc.metadata, "page_content": doc.page_content}
        current_app.logger.debug(
            "Retrieved document passage from: %s", doc.metadata["name"]
        )
        yield f"data: {SOURCE_TAG} {json.dumps(doc_source)}\n\n"

    qa_prompt = render_template(
        "rag_prompt.txt",
        question=question,
        docs=docs,
        chat_history=chat_history.messages,
    )

    answer = ""
    for chunk in get_llm().stream(qa_prompt, config={"callbacks": [langfuse_handler]}):
        content = chunk.content.replace("\n\n", "\n").replace(
            "\n", " "
        )  # the stream can get messed up with newlines
        yield f"data: {content}\n\n"
        answer += chunk.content


    yield f"data: {DONE_TAG}\n\n"
    current_app.logger.debug("Answer: %s", answer)

    chat_history.add_user_message(question)
    chat_history.add_ai_message(answer)
``` 

### SDK and container versions

List of Python packages and their respective versions

| Packages | Version |
|--------|--------|
| langchain | 0.1.9 |
| langchain-community | 0.0.27 |
| langchain-core  | 0.1.30 |
| langchain-elasticsearch | 0.1.0 |
| langchain-mistralai   | 0.0.5 | 
| langfuse | 2.33.0 |

### Additional information

in the console we see the below errors populating

```
2024-05-25 18:35:19,765 WARNING werkzeug:  * Debugger is active!
2024-05-25 18:35:19,785 INFO werkzeug:  * Debugger PIN: 259-812-146
2024-05-25 18:35:19,893 INFO werkzeug: 127.0.0.1 - - [25/May/2024 18:35:19] "OPTIONS /api/chat HTTP/1.1" 200 -
2024-05-25 18:35:19,947 INFO werkzeug: 127.0.0.1 - - [25/May/2024 18:35:19] "POST /api/chat HTTP/1.1" 200 -
2024-05-25 18:35:19,947 DEBUG app: Chat session ID: 0e48b67c-33a7-4f55-8d30-2de8f47b80cd
/Users/<my-user>/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/Users/<my-user>/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2024-05-25 18:35:21,554 DEBUG app: Condensed question: steps to create grafana alerts
2024-05-25 18:35:21,554 DEBUG app: Question: steps to create grafana alerts
2024-05-25 18:35:21,562 ERROR langfuse: parent run not found
Traceback (most recent call last):
  File "/Users/<my-user>/Desktop/WIP/.venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 518, in on_retriever_start
    raise Exception("parent run not found")
Exception: parent run not found
/Users/<my-user>/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2024-05-25 18:35:21,861 ERROR langfuse: run not found
Traceback (most recent call last):
  File "/Users/<my-user>/Desktop/WIP/.venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 544, in on_retriever_end
    raise Exception("run not found")
Exception: run not found
2024-05-25 18:35:21,862 DEBUG app: Retrieved document passage from: Steps to create grafana alerts
2024-05-25 18:35:21,862 DEBUG app: Retrieved document passage from: How to create Grafana Alerts for a team
2024-05-25 18:35:21,862 DEBUG app: Retrieved document passage from: What is Grafana Alerts
2024-05-25 18:35:21,862 DEBUG app: Retrieved document passage from: Grafana Overview
/Users/<my-user>/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2024-05-25 18:35:57,037 DEBUG app: Answer: To create Grafana alerts, follow these steps:

Step 1 - <steps here in answer>

SOURCES: <Doc-Link>
/Users/<my-user>/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/Users/<my-user>/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2024-05-25 18:38:39,443 INFO werkzeug:  * Detected change in '/Users/<my-user>/Desktop/WIP/elasticsearch-labs/example-apps/chatbot-rag-app/api/chat.py', reloading
2024-05-25 18:38:40,658 INFO werkzeug:  * Restarting with stat
``` 

Hence in the langfuse traces we don't see the tree structure for the trace with the name "test1" that we set in the context

### Are you interested to contribute a fix for this bug?

Yes

**Comment by Altaf-Axway** [comment]
We even tried python sdk also but we still see the same issue


Code

```python
from langchain_elasticsearch import ElasticsearchStore
from langfuse.callback import CallbackHandler
from llm_integrations import get_llm
from elasticsearch_client import (
    elasticsearch_client,
    get_elasticsearch_chat_message_history,
)
from flask import render_template, stream_with_context, current_app
import json
import os
from langfuse import Langfuse

INDEX = os.getenv("ES_INDEX", "workplace-app-docs")
INDEX_CHAT_HISTORY = os.getenv(
    "ES_INDEX_CHAT_HISTORY", "workplace-app-docs-chat-history"
)
ELSER_MODEL = os.getenv("ELSER_MODEL", ".elser_model_2")
SESSION_ID_TAG = "[SESSION_ID]"
SOURCE_TAG = "[SOURCE]"
DONE_TAG = "[DONE]"

store = ElasticsearchStore(
    es_connection=elasticsearch_client,
    index_name=INDEX,
    strategy=ElasticsearchStore.SparseVectorRetrievalStrategy(model_id=ELSER_MODEL),
)


@stream_with_context
def ask_question(question, session_id):
    yield f"data: {SESSION_ID_TAG} {session_id}\n\n"
    current_app.logger.debug("Chat session ID: %s", session_id)
    langfuse = Langfuse()
    trace = langfuse.trace()
    langfuse_handler_trace = trace.get_langchain_handler()
    langfuse_handler_trace = CallbackHandler(
    public_key="<key>",
    secret_key="<key>",
    host="https://cloud.langfuse.com",
    session_id=session_id
    )

    span = trace.span()
    langfuse_handler_span = span.get_langchain_handler()

    langfuse_handler_span = CallbackHandler(
    public_key="<key>",
    secret_key="<key>",
    host="https://cloud.langfuse.com",
    session_id=session_id
    )

    chat_history = get_elasticsearch_chat_message_history(
        INDEX_CHAT_HISTORY, session_id
    )

    if len(chat_history.messages) > 0:
        # create a condensed question
        condense_question_prompt = render_template(
            "condense_question_prompt.txt",
            question=question,
            chat_history=chat_history.messages,
        )
        condensed_question = get_llm().invoke(condense_question_prompt,config={"callbacks": [langfuse_handler_span]}).content
    else:
        condensed_question = question

    current_app.logger.debug("Condensed question: %s", condensed_question)
    current_app.logger.debug("Question: %s", question)

    docs = store.as_retriever().invoke(condensed_question,config={"callbacks": [langfuse_handler_span]})
    for doc in docs:
        doc_source = {**doc.metadata, "page_content": doc.page_content}
        current_app.logger.debug(
            "Retrieved document passage from: %s", doc.metadata["name"]
        )
        yield f"data: {SOURCE_TAG} {json.dumps(doc_source)}\n\n"

    qa_prompt = render_template(
        "rag_prompt.txt",
        question=question,
        docs=docs,
        chat_history=chat_history.messages,
    )


    answer = ""
    for chunk in get_llm().stream(qa_prompt, config={"callbacks": [langfuse_handler_span]}):
        content = chunk.content.replace("\n\n", "\n").replace(
            "\n", " "
        )  # the stream can get messed up with newlines
        yield f"data: {content}\n\n"
        answer += chunk.content


    yield f"data: {DONE_TAG}\n\n"
    current_app.logger.debug("Answer: %s", answer)

    chat_history.add_user_message(question)
    chat_history.add_ai_message(answer)

``` 

Error Logs

```
2024-05-28 23:42:50,781 WARNING werkzeug:  * Debugger is active!
2024-05-28 23:42:50,808 INFO werkzeug:  * Debugger PIN: 259-812-146
2024-05-28 23:42:52,362 INFO werkzeug: 127.0.0.1 - - [28/May/2024 23:42:52] "OPTIONS /api/chat HTTP/1.1" 200 -
2024-05-28 23:42:52,372 INFO werkzeug: 127.0.0.1 - - [28/May/2024 23:42:52] "POST /api/chat HTTP/1.1" 200 -
2024-05-28 23:42:52,372 DEBUG app: Chat session ID: c5cf7666-f7ff-4300-8a23-5af7f454e94f
/Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2024-05-28 23:42:54,080 DEBUG app: Condensed question: What's the NASA sales team?
2024-05-28 23:42:54,080 DEBUG app: Question: What's the NASA sales team?
2024-05-28 23:42:54,088 ERROR langfuse: parent run not found
Traceback (most recent call last):
  File "/Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 518, in on_retriever_start
    raise Exception("parent run not found")
Exception: parent run not found
/Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2024-05-28 23:42:54,480 ERROR langfuse: run not found
Traceback (most recent call last):
  File "/Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 544, in on_retriever_end
    raise Exception("run not found")
Exception: run not found
2024-05-28 23:42:54,480 DEBUG app: Retrieved document passage from: Sales Organization Overview
2024-05-28 23:42:54,480 DEBUG app: Retrieved document passage from: Sales Engineering Collaboration
2024-05-28 23:42:54,480 DEBUG app: Retrieved document passage from: Fy2024 Company Sales Strategy
2024-05-28 23:42:54,481 DEBUG app: Retrieved document passage from: Sales Engineering Collaboration
/Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2024-05-28 23:43:09,936 DEBUG app: Answer: The NASA sales team is not mentioned in any of the provided passages. However, according to the "Sales Organization Overview" passage, there is a region called "North America South America (NASA)" that covers countries such as the United States, Canada, Mexico, and others.

Blank line:


SOURCES: Sales Organization Overview, Sales Engineering Collaboration
/Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
```

**Comment by GMartin-dev** [comment]
I'm seeing similar issues with retrievers in some contexts. It seems buy the moment it triggers the retriever events the trace / span are not properly set.

**Comment by lukas-thirdmind** [comment]
I had the same issue. It was fixed with the latest langchain-core update (version=0.2.10). 

See here: https://github.com/langchain-ai/langchain/discussions/21596

**Comment by marcklingen** [comment]
> I had the same issue. It was fixed with the latest langchain-core update (version=0.2.10).
> 
> See here: [langchain-ai/langchain#21596](https://github.com/langchain-ai/langchain/discussions/21596)

awesome, thanks for sharing. Glad to hear that this was fixed.

I'll close this issue, let's reopen in case this issue persist (langchain-core >= 0.2.10).
