### ISSUE TITLE
bug: run not found and Generations are not stacked under Span

### ISSUE THREAD

**Issue by nathan-vo810** [langfuse/langfuse#2155]
### Describe the bug

When using Langchain ContextualCompressionRetriever, "run not found" was raised. 

`Traceback (most recent call last):
  File "/Users/anhvo/miniconda3/envs/eongpt/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 209, in on_chain_start
    self.runs[run_id] = self.runs[parent_run_id].span(**content)
                        ~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: UUID('5cd6a619-19a2-404c-af17-a6f770c593ff')
run not found
Traceback (most recent call last):
  File "/Users/anhvo/miniconda3/envs/eongpt/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 365, in on_chain_end
    raise Exception("run not found")
Exception: run not found
run not found
Traceback (most recent call last):
  File "/Users/anhvo/miniconda3/envs/eongpt/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 539, in on_retriever_end
    raise Exception("run not found")
Exception: run not found`
---------------------------------------------------------------------------------------------------------
The ContextualCompressionRetriever consists of 2 parts:
1. Retrieval part
2. Generations part

The Generations part are not stacked under the parent span

<img width="268" alt="Screenshot 2024-05-27 at 13 57 08" src="https://github.com/langfuse/langfuse/assets/14048514/6d771d27-4ef4-46a9-bd92-9f35c954cf28">


### To reproduce

`from langchain.retrievers import ContextualCompressionRetriever
from langchain.retrievers.document_compressors import LLMChainExtractor
from langchain_openai import OpenAI

llm = OpenAI(temperature=0)
compressor = LLMChainExtractor.from_llm(llm)
compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=retriever
)

compressed_docs = compression_retriever.invoke(
    "What did the president say about Ketanji Jackson Brown"
)`

### SDK and container versions

langchain==0.1.12
langfuse==0.2.29

### Additional information

_No response_

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for reporting, sorry for the long wait here. Is this still an issue on the latest langchain/langfuse versions? Would appreciate it if you can check as there were some fixes related to this recently in Langchain afaik

**Comment by solanki-aman** [comment]
Facing the same issue on latest langchain and langfuse version.
