### ISSUE TITLE
bug: Streaming response with tool call is not working 

### ISSUE THREAD

**Issue by someshfengde** [langfuse/langfuse#2163]
### Describe the bug

Hi can this be resolved. 

After some more debugging. I found it's indeed error from langfuse.openai

### traceback
```

  + Exception Group Traceback (most recent call last):
  |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
  |     raise exc
  |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
  |     await self.simple_response(scope, receive, send, request_headers=headers)
  |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
  |     await self.app(scope, receive, send)
  |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
  |     raise exc
  |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
  |     await self.app(scope, receive, sender)
  |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
  |     raise e
  |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
  |     await self.app(scope, receive, send)
  |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
  |     await route.handle(scope, receive, send)
  |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
  |     await self.app(scope, receive, send)
  |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/starlette/routing.py", line 69, in app
  |     await response(scope, receive, send)
  |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/starlette/responses.py", line 270, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/starlette/responses.py", line 273, in wrap
    |     await func()
    |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/starlette/responses.py", line 262, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/Users/som/Downloads/code/cybergpt_backend/openai_function_calling.py", line 423, in run_conversation
    |     completion = openai.chat.completions.create(
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/langfuse/openai.py", line 151, in wrapper
    |     return func(open_ai_definitions, initialize, wrapped, args, kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/langfuse/openai.py", line 488, in _wrap
    |     generation, is_nested_trace = _get_langfuse_data_from_kwargs(
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/langfuse/openai.py", line 264, in _get_langfuse_data_from_kwargs
    |     prompt = _extract_chat_prompt(kwargs)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/langfuse/openai.py", line 181, in _extract_chat_prompt
    |     return _filter_image_data(kwargs.get("messages", []))
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/langfuse/openai.py", line 642, in _filter_image_data
    |     if message.get("content", None) is not None:
    |        ^^^^^^^^^^^
    |   File "/Users/som/Downloads/code/cybergpt_backend/.venv/lib/python3.11/site-packages/pydantic/main.py", line 811, in __getattr__
    |     raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
    | AttributeError: 'ChatCompletionMessage' object has no attribute 'get'
    +------------------------------------
```

the messages object was something similar to this 
```
messages = [{'role': 'user', 'content': 'what is the most efficient way to store responses.'},
ChatCompletionMessage(content=None, role='assistant', function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_wGM41oVUgboqYCpSsaYCXLpH', function=Function(arguments='{"query":"efficient way to store responses"}', name='get_general_cybersec_context'), type='function')]),
{'tool_call_id': 'call_wGM41oVUgboqYCpSsaYCXLpH', 'role': 'tool', 'name': 'get_general_cybersec_context', 'content': 'responding with therequested data notice that the server response repeats the functio...ave welldocumented and incident response p'}]
```
If you use same message_list in openai official client it works. but here we are getting it has no attribute get 

### To reproduce

from langfuse.openai import openai
from openai.types.chat import ChatCompletionMessage, ChatCompletionMessageToolCall

messages = [{'role': 'user', 'content': 'what is the most efficient way to store responses.'},
ChatCompletionMessage(content=None, role='assistant', function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_wGM41oVUgboqYCpSsaYCXLpH', function=Function(arguments='{"query":"efficient way to store responses"}', name='get_general_cybersec_context'), type='function')]),
{'tool_call_id': 'call_wGM41oVUgboqYCpSsaYCXLpH', 'role': 'tool', 'name': 'get_general_cybersec_context', 'content': 'responding with therequested data notice that the server response repeats the functio...ave welldocumented and incident response p'}]

completion = openai.chat.completions.create(
  name="test-chat",
  model="gpt-3.5-turbo",
  messages=messages, 
  temperature=0,
  metadata={"someMetadataKey": "someValue"},
  stream=True
)
 
for chunk in completion:
  print(chunk.choices[0].delta.content, end="")

### SDK and container versions

langfuse = "^2.33.0"
openai = "1.30.3"

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
related discussion: https://github.com/orgs/langfuse/discussions/2055#discussioncomment-9578747
