### ISSUE TITLE
bug: langfuse llama index functionality is not threadsafe

### ISSUE THREAD

**Issue by dgarnitz** [langfuse/langfuse#2265]
### Describe the bug

I am running into a bug (or perhaps a missing feature). Looks like the langfuse llama index functionality is not threadsafe with `ThreadPoolExecutor`. If I try to run a query with a llama index query_engine as follows

```python
with concurrent.futures.ThreadPoolExecutor(max_workers=20) as executor:
        results = list(executor.map(lambda _: query_engine.query("What is the general theme of the documents you are looking at?"), range(3)))
```

it will throw the following error
```python
ValueError: not enough values to unpack (expected 2, got 1)
ERROR:langfuse:An error occurred in _handle_span_events: 'NoneType' object has no attribute 'span'
Traceback (most recent call last):
  File "/Users/davidgarnitz/Documents/Programming/market-research-rag/venv/lib/python3.9/site-packages/langfuse/utils/error_logging.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/Users/davidgarnitz/Documents/Programming/market-research-rag/venv/lib/python3.9/site-packages/langfuse/llama_index/llama_index.py", line 506, in _handle_span_events
    span = parent.span(
AttributeError: 'NoneType' object has no attribute 'span'
ERROR:langfuse:An error occurred in _handle_LLM_events: 'NoneType' object has no attribute 'generation'
Traceback (most recent call last):
  File "/Users/davidgarnitz/Documents/Programming/market-research-rag/venv/lib/python3.9/site-packages/langfuse/utils/error_logging.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/Users/davidgarnitz/Documents/Programming/market-research-rag/venv/lib/python3.9/site-packages/langfuse/llama_index/llama_index.py", line 352, in _handle_LLM_events
    generation = parent.generation(
AttributeError: 'NoneType' object has no attribute 'generation'
```

### To reproduce

Create a llama index query engine to perform RAG then define a query method:

```python
import concurrent.futures
langfuse_callback_handler = LlamaIndexCallbackHandler()
Settings.callback_manager = CallbackManager([langfuse_callback_handler])

with concurrent.futures.ThreadPoolExecutor(max_workers=20) as executor:
        results = list(executor.map(lambda _: query_engine.query("What is the general theme of the documents you are looking at?"), range(3)))
```

this error will only occur if the query engine is called with concurrent future

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
afaik this is a known limitation of llamaindex in general, @hassiebp any other insights on this?

**Comment by dgarnitz** [comment]
Its not a Llama Index issue, when I comment out the Langfuse code it works totally fine. if I set `use_langfuse` to false, it works great.
```python
if use_langfuse:
            logging.info("Using langfuse")
            langfuse_callback_handler = LlamaIndexCallbackHandler()
            Settings.callback_manager = CallbackManager([langfuse_callback_handler])
```
