### ISSUE TITLE
Circular references in the storage cache when using observeOpenAI

### ISSUE THREAD

**Issue by pabloromeo** [langfuse/langfuse#2318]
## Bug description

So, I've been using traces successfully within an application, all traces and spans get stored correctly and it works great.
However, I recently added the langfuse error handler and started logging errors from it, and noticed that every time traces occur I see the following errors being logged:

```
2024-05-23 22:26:31 Error while flushing Langfuse TypeError: Converting circular structure to JSON
2024-05-23 22:26:31     --> starting at object with constructor 'Object'
2024-05-23 22:26:31     |     property 'queue' -> object with constructor 'Array'
2024-05-23 22:26:31     |     index 2 -> object with constructor 'Object'
2024-05-23 22:26:31     |     ...
2024-05-23 22:26:31     |     property 'client' -> object with constructor 'Langfuse'
2024-05-23 22:26:31     --- property '_storageCache' closes the circle
2024-05-23 22:26:31     at JSON.stringify (<anonymous>)
2024-05-23 22:26:31     at Langfuse.setPersistedProperty (file:///usr/src/app/node_modules/langfuse/lib/index.mjs:177:50)
2024-05-23 22:26:31     at Langfuse.flush (file:///usr/src/app/node_modules/langfuse-core/lib/index.mjs:598:10)
2024-05-23 22:26:31     at file:///usr/src/app/node_modules/langfuse-core/lib/index.mjs:574:14
2024-05-23 22:26:31     at new Promise (<anonymous>)
2024-05-23 22:26:31     at Langfuse.flushAsync (file:///usr/src/app/node_modules/langfuse-core/lib/index.mjs:572:12)
```

I don't see what I might be doing wrong that is causing a circular reference to end up in the storage cache, since I'm just either manually creating a trace or a span just with a name and some input and output (which get shown correctly in langfuse), plus the `observeOpenAI` wrapper for OpenAI completions.

## How to reproduce

Traces that are manually created don't trigger the error, neither do spans.
The error appears as soon as it's a Generation automatically created by the `observeOpenAI` wrapped openAI client.

## Related sub-libraries

- [ ] All of them
- \[X \] langfuse
- [ ] langfuse-node

## Additional context

Completions in my case are mostly done as streams. Not sure if that info helps. Even completions with tools, since I'm running an Agent with tools with streamed responses.
I'm using langfuse version 3.11.1 from npm.

#### *Thank you* for your bug report – we love squashing them!

**Comment by marcklingen** [comment]
thanks for reporting @pabloromeo, I moved the issue to our main repo as we centralize issues here. @hassiebp can you have a look?

**Comment by pabloromeo** [comment]
Ah, sorry about that! Will track it there. Thanks so much!

**Comment by MarquisG** [comment]
Hi all!
@hassiebp 
I've just had the same problem, even without using observeOpenAI.
In my case, this error occurs when I create several traces, with the same session id, in a short space of time and without waiting for the previous trace to finish. For example, if the session is a chat, and the trace is a question/answer, this happens when a user sends several messages in the same chat without waiting for the bot to reply.

I hope this helps you find out what's going on.

**Comment by Haoping-Xiao** [comment]
@MarquisG @pabloromeo did you solve your problem? I had the same problem here.

**Comment by pabloromeo** [comment]
> @MarquisG @pabloromeo did you solve your problem? I had the same problem here.

Unfortunately no. The issue was closed because I couldn't prepare a sample repo  with steps to reproduce it (haven't found the time yet).
If you have something like that for the team to test this case I'm sure they'll reopen the issue and take a look, given that there's several of us seeing this same issue occur.

**Comment by Haoping-Xiao** [comment]
I've tried to repo this issue for a day.  And finally succeeded. 

`
const langfuse = new Langfuse({
    secretKey: process.env.LANGFUSE_SECRET_KEY,
    publicKey: process.env.LANGFUSE_PUBLIC_KEY,
    baseUrl: process.env.LANGFUSE_BASEURL,
    flushAt: 1
});

async function main(){
    const query = "xxx"
    const n_outputs = 2;
    const prompt = await langfuse.getPrompt("recommend");
     
    // Insert variables into prompt template
    const system_prompt = prompt.compile({ n_outputs: n_outputs });
    const messages = [{role: 'system', content: system_prompt},
                      {role: 'user', content: query}]
    const trace = langfuse.trace({
        name: "my-AI-application-endpoint",
        userId: "1",
        tags: ["production"]
    });
    const span1 = trace.span({
        "name": "test1",
        "input": messages
    })
    const chatCompletion = await getLLM(span1, messages, prompt)
    const  test = {}
    span1.end({"output": {
                test
            }})

    const span2 = trace.span({
        "name": "test2",
        "input": messages
    })
    const chatCompletion1 = await getLLM(span2, messages, prompt)
    span2.end({"output": {
        test
    }})
    await langfuse.shutdownAsync();
}

async function getLLM(langfuseObject, messages, prompt){
    const openai = new OpenAI({
        baseURL : process.env.LLM_URL,
        apiKey: process.env.LLM_API_KEY,
    });
    const Lopenai = observeOpenAI(openai, {
        generationName: "OpenAI Custom Trace",
        parent: langfuseObject,
        generationName: prompt.name,
        langfusePrompt: prompt
    })
    const chatCompletion = await Lopenai.chat.completions.create({
        messages: messages,
        model: 'qwen1.5-14b-32k',
        temperature: 0.5,
      });
    console.log(chatCompletion)
    return chatCompletion
}

main()
`

The problem can be repoduced after the first span is flushed. I didn't set flushAt in my project. But somehow when storage cache get flushed, the problem occurs. 

@hassiebp I hope this code snippet helps you repoduce the issue.
