### ISSUE TITLE
bug: Invalid Public Key

### ISSUE THREAD

**Issue by harsh-garg98** [langfuse/langfuse#2439]
### Describe the bug

I have a self-hosted instance of langfuse running on Azure (using the self-hosting guide provided for Azure - VS Code Dev Containers - https://github.com/Azure-Samples/langfuse-on-azure). I have created a new fresh set of Public and Secret API Keys. I have added them both, and the hostname displayed on the Settings page to my .env file. I am trying to use langfuse with ollama (using the Python SDKs; ollama is hosted locally) but I am getting an error saying 'invalid public key'

### To reproduce

.env:
```
LANGFUSE_SECRET_KEY="sk-..."
LANGFUSE_PUBLIC_KEY="pk-..."
HOST_NAME="https://.....azurecontainerapps.io"
```

main.py:
```
from dotenv import load_dotenv
from langfuse.decorators import observe
import ollama

load_dotenv()


@observe()
def tinyllama():
    response = ollama.chat(
        model="tinyllama",
        messages=[
            {
                "role": "user",
                "content": "Why is the sky blue?",
            },
        ],
    )
    return(response["message"]["content"])


@observe()
def main():
    return tinyllama()


if __name__ == "__main__":
    print(main())
```

Error message:
```
received error response: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."}
received error response: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."}
received error response: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."}
Giving up execute_task_with_backoff(...) after 3 tries (langfuse.request.APIError: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."} (401): None)
error uploading: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."} (401): None
Traceback (most recent call last):
  File "/Users/harshgarg/Desktop/litellm/langfuse-self-host/.venv/lib/python3.9/site-packages/langfuse/task_manager.py", line 160, in upload
    self._upload_batch(batch)
  File "/Users/harshgarg/Desktop/litellm/langfuse-self-host/.venv/lib/python3.9/site-packages/langfuse/task_manager.py", line 187, in _upload_batch
    execute_task_with_backoff(batch)
  File "/Users/harshgarg/Desktop/litellm/langfuse-self-host/.venv/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/Users/harshgarg/Desktop/litellm/langfuse-self-host/.venv/lib/python3.9/site-packages/langfuse/task_manager.py", line 185, in execute_task_with_backoff
    return self._client.batch_post(batch=batch, metadata=metadata)
  File "/Users/harshgarg/Desktop/litellm/langfuse-self-host/.venv/lib/python3.9/site-packages/langfuse/request.py", line 56, in batch_post
    return self._process_response(
  File "/Users/harshgarg/Desktop/litellm/langfuse-self-host/.venv/lib/python3.9/site-packages/langfuse/request.py", line 120, in _process_response
    raise APIError(res.status_code, payload)
langfuse.request.APIError: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."} (401): None
The sky blue color is due to the blue light emitted by sunlight traveling through the atmosphere. The atmosphere consists of gas molecules that absorb some of the shorter wavelengths of red, orange, and green light as well as some of the longer wavelengths of blue and violet light. This absorption occurs at a specific range of wavelengths based on the composition of the air molecules in the atmosphere. The higher the altitude, the longer the wavelength that is absorbed and the brighter the sky becomes.

As you look up towards the heavens, the color of the sky changes due to the atmospheric conditions at different heights above the Earth's surface. The blue light emitted by sunlight at higher altitudes in the morning hours is absorbed by the cooler air molecules, resulting in a brighter and more vivid blue hue. As you go lower in altitude towards the horizon, the light starts to get dimmer due to the increase in atmospheric thickness, which results in a fading or duller blue color.

There are several factors that affect the color of the sky, including temperature, humidity, air pressure, and distance from the Earth's surface. The intensity and direction of the sun's rays also play a role in how blue or red the sky becomes depending on where you are located.
received error response: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."}
received error response: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."}
received error response: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."}
Giving up execute_task_with_backoff(...) after 3 tries (langfuse.request.APIError: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."} (401): None)
error uploading: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."} (401): None
Traceback (most recent call last):
  File "/Users/harshgarg/Desktop/litellm/langfuse-self-host/.venv/lib/python3.9/site-packages/langfuse/task_manager.py", line 160, in upload
    self._upload_batch(batch)
  File "/Users/harshgarg/Desktop/litellm/langfuse-self-host/.venv/lib/python3.9/site-packages/langfuse/task_manager.py", line 187, in _upload_batch
    execute_task_with_backoff(batch)
  File "/Users/harshgarg/Desktop/litellm/langfuse-self-host/.venv/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/Users/harshgarg/Desktop/litellm/langfuse-self-host/.venv/lib/python3.9/site-packages/langfuse/task_manager.py", line 185, in execute_task_with_backoff
    return self._client.batch_post(batch=batch, metadata=metadata)
  File "/Users/harshgarg/Desktop/litellm/langfuse-self-host/.venv/lib/python3.9/site-packages/langfuse/request.py", line 56, in batch_post
    return self._process_response(
  File "/Users/harshgarg/Desktop/litellm/langfuse-self-host/.venv/lib/python3.9/site-packages/langfuse/request.py", line 120, in _process_response
    raise APIError(res.status_code, payload)
langfuse.request.APIError: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."} (401): None
```

### Are you interested to contribute a fix for this bug?

Yes

**Comment by marcklingen** [comment]
Thanks for reporting!

- Have you printed the variables to make sure that they are actually in the environment?
- Can you try loading `load_dotenv()` before running `from langfuse.decorators import observe`?

**Comment by 4t8dd** [comment]
>LANGFUSE_SECRET_KEY="sk-..."
>LANGFUSE_PUBLIC_KEY="pk-..."
>HOST_NAME="https://.....azurecontainerapps.io"

Replace HOST_NAME with LANGFUSE_HOST

**Comment by marcklingen** [comment]
> Replace HOST_NAME with LANGFUSE_HOST
+1, thank you

I just searched product and docs, where did you find `HOST_NAME` as the env?

**Comment by marcklingen** [comment]
> Replace HOST_NAME with LANGFUSE_HOST
+1, thank you

@harsh-garg98, I just searched product and docs, where did you find `HOST_NAME` as the env?

**Comment by harsh-garg98** [comment]
Changing HOST_NAME to LANGFUSE_HOST worked for me. I must have not looked at the docs properly to set the wrong env var name. Apologies for the oversight. But thanks a lot for helping me out!

**Comment by marcklingen** [comment]
thanks again @4t8dd for spotting this, glad that this fixed it for you
