### ISSUE TITLE
Bug: Type errors using observeOpenAI and langfuse prompt

### ISSUE THREAD

**Issue by oscarmorrison** [langfuse/langfuse#2569]
```
    const prompt = await langfuse.getPrompt(PROMPT.ANSWER);
    const messages = prompt.compile({
        team_name: team_name,
        team_usecase: team_usecase,
        user_name: user_name,
        user_role: user_role,
        query: query,
        pagesString: pagesString,
        documentsString: documentsString,
        questionsString: questionsString,
    });


    const metadata = {
        search_results: searchResults.length,
        trimmed_search_results: trimmedSearchResults.length,
        user_role: user_role,
        original_query: query,
    };

    const langfuseConfig = {
        generationName: GENERATION_NAME,
        userId: user_id.toString(),
        version: minorVersion,
        release: APP_ENV === ENV.PROD ? minorVersion : 'local',
        metadata: metadata,
    };

    const observableOpenAi = observeOpenAI(openai, langfuseConfig);

    const response = await observableOpenAi.chat.completions.create({
        model: model.name,
        response_format: {type: 'json_object'},
        messages: JSON.parse(JSON.stringify(messages)),
        max_tokens: RESPONSE_TOKEN_COUNT,
        temperature: temp,
        frequency_penalty: 0,
        presence_penalty: 0,
    });

```

If you look here: for the messages param, this is the only way I can get it to work:
`        messages: JSON.parse(JSON.stringify(messages)),`

If I don't stringify then parse I get a type error:

` messages: messages,     ■ No overload matches this call.    Overload 1 of 3, '(body: ChatCompletionCreateParamsNonStreaming, options?: RequestOptions<unknown> | undefined): APIPromise<ChatCompletion>', gave the following error.      Type 'string' is`

Full error:

```
TSError: ⨯ Unable to compile TypeScript:
src/routes/v4/answer.ts:117:9 - error TS2769: No overload matches this call.
  Overload 1 of 3, '(body: ChatCompletionCreateParamsNonStreaming, options?: RequestOptions<unknown> | undefined): APIPromise<ChatCompletion>', gave the following error.
    Type 'string' is not assignable to type 'ChatCompletionMessageParam[]'.
  Overload 2 of 3, '(body: ChatCompletionCreateParamsStreaming, options?: RequestOptions<unknown> | undefined): APIPromise<Stream<ChatCompletionChunk>>', gave the following error.
    Type 'string' is not assignable to type 'ChatCompletionMessageParam[]'.
  Overload 3 of 3, '(body: ChatCompletionCreateParamsBase, options?: RequestOptions<unknown> | undefined): APIPromise<ChatCompletion | Stream<...>>', gave the following error.
    Type 'string' is not assignable to type 'ChatCompletionMessageParam[]'.

117         messages: messages,
            ~~~~~~~~

  node_modules/openai/resources/chat/completions.d.ts:564:5
    564     messages: Array<ChatCompletionMessageParam>;
            ~~~~~~~~
    The expected type comes from property 'messages' which is declared here on type 'ChatCompletionCreateParamsNonStreaming'
  node_modules/openai/resources/chat/completions.d.ts:564:5
    564     messages: Array<ChatCompletionMessageParam>;
            ~~~~~~~~
    The expected type comes from property 'messages' which is declared here on type 'ChatCompletionCreateParamsStreaming'
  node_modules/openai/resources/chat/completions.d.ts:564:5
    564     messages: Array<ChatCompletionMessageParam>;
            ~~~~~~~~
    The expected type comes from property 'messages' which is declared here on type 'ChatCompletionCreateParamsBase'

    at createTSError (/Users/oscarmorrison/tettra/project-hydra/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/oscarmorrison/tettra/project-hydra/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/oscarmorrison/tettra/project-hydra/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/oscarmorrison/tettra/project-hydra/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/Users/oscarmorrison/tettra/project-hydra/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/oscarmorrison/tettra/project-hydra/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19) {
  diagnosticCodes: [ 2769 ]
}
```

**Comment by oscarmorrison** [comment]
```
    const prompt = await langfuse.getPrompt(PROMPT.ANSWER, undefined, {
        type: 'chat'
    });
```
@marcklingen 

this makes no difference. I still have the type error (btw i was getting the correct chat prompt beforehand)

**Comment by oscarmorrison** [comment]
I believe the issue is: https://js.reference.langfuse.com/types/langfuse_core.ChatMessage.html

it should be returning: `OpenAI.Chat.ChatCompletionMessageParam[]`

**Comment by marcklingen** [comment]
Got it, thanks for reporting! `name` is used by openai for function calls afaik. You should be safe to use the compiled langfuse chat prompt and cast it to `ChatCompletionMessageParam[]` until we release a fix for this

**Comment by oscarmorrison** [comment]
Casting fixed the issue:

```
    const messages: ChatCompletionMessageParam[] = prompt.compile({
        team_name: team_name,
        team_usecase: team_usecase,
        user_name: user_name,
        user_role: user_role,
        query: query,
        pagesString: pagesString,
        documentsString: documentsString,
        questionsString: questionsString,
    }) as ChatCompletionMessageParam[];
```

**Comment by hassiebp** [comment]
Hi @oscarmorrison - OpenAI allows only a narrow set of message roles whereas Langfuse chat prompts can have arbitrary strings as roles. Thus the type errors as the role is not narrow enough. You can either type-cast as `OpenAI.ChatCompletionMessageParam[]` or write a type-guard to verify the returned Langfuse chat prompt is OpenAI compatible.
