### ISSUE TITLE
bug: Getting httpx error httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol

### ISSUE THREAD

**Issue by ashutoshsaboo** [langfuse/langfuse#2623]
### Describe the bug

This is happening on a self hosted langfuse instance, deployed on AWS ECS + Postgres RDS. All env vars are perfectly set, which is why one of the below calls goes successfully as well. Langfuse UI opens up perfectly and is fully functional as well. 
When i do the below, this works perfectly fine and writes the trace to Langfuse DBs, and I can see it on the UI as well: 
```
from langfuse import Langfuse

langfuse = Langfuse(
  secret_key=<langfuse_secret_key>,
  public_key=<langfuse_public_key>,
  host=<langfuse_load_balancer_url>
)
trace.update(
    input="Hi there"
)
 
# option 2: via trace_id, trace is upserted on id
langfuse.trace(id=trace.id, output="Hi 👋")
```

See successful log for the above below, 
```
In [68]: trace.update(
    ...:     input="Hi there"
    ...: )
    ...:
In [68]: trace.update(
    ...:     input="Hi there"
    ...: )
    ...:
    ...: # option 2: via trace_id, trace is upserted on id
    ...: langfuse.trace(id=trace.id, output="Hi 👋")
    ...:
    ...:
DEBUG:langfuse:Update trace {'id': '0a9ae026-1c04-44f2-a396-8ea80769156b', 'name': None, 'userId': None, 'sessionId': None, 'version': None, 'release': None, 'input': 'Hi there', 'output': None, 'metadata': None, 'public': None, 'tags': None}...
DEBUG:langfuse:Creating trace id='0a9ae026-1c04-44f2-a396-8ea80769156b' timestamp=datetime.datetime(2024, 7, 13, 18, 10, 18, 801107, tzinfo=datetime.timezone.utc) name=None user_id=None input=None output='Hi 👋' session_id=None release=None version=None metadata=None tags=None public=None
Out[68]: <langfuse.client.StatefulTraceClient at 0x11fbf1c90>
DEBUG:langfuse:item size 191
DEBUG:langfuse:item size 243
In [69]: DEBUG:langfuse:~0 items in the Langfuse queue
DEBUG:langfuse:uploading batch of 1 items
DEBUG:langfuse:uploading data: {'batch': [{'id': 'a2c6e83a-415b-4068-9e02-e81f2a2bd60d', 'type': 'trace-create', 'body': {'id': '0a9ae026-1c04-44f2-a396-8ea80769156b', 'timestamp': datetime.datetime(2024, 7, 13, 18, 10, 18, 801107, tzinfo=datetime.timezone.utc), 'output': 'Hi 👋'}, 'timestamp': datetime.datetime(2024, 7, 13, 18, 10, 18, 801349, tzinfo=datetime.timezone.utc)}], 'metadata': {'batch_size': 1, 'sdk_integration': 'default', 'sdk_name': 'python', 'sdk_version': '2.39.1', 'public_key': '<public_key_id>'}}
DEBUG:langfuse:making request: {"batch": [{"id": "a2c6e83a-415b-4068-9e02-e81f2a2bd60d", "type": "trace-create", "body": {"id": "0a9ae026-1c04-44f2-a396-8ea80769156b", "timestamp": "2024-07-13T18:10:18.801107Z", "output": "Hi \ud83d\udc4b"}, "timestamp": "2024-07-13T18:10:18.801349Z"}], "metadata": {"batch_size": 1, "sdk_integration": "default", "sdk_name": "python", "sdk_version": "2.39.1", "public_key": "<public_key_id>"}} to http://<langfuse_load_balancer_url>/api/public/ingestion
DEBUG:langfuse:~0 items in the Langfuse queue
DEBUG:langfuse:uploading batch of 1 items
DEBUG:langfuse:uploading data: {'batch': [{'id': '60270390-509e-4139-bb70-c2f12eed3586', 'type': 'trace-create', 'body': {'id': '0a9ae026-1c04-44f2-a396-8ea80769156b', 'input': 'Hi there'}, 'timestamp': datetime.datetime(2024, 7, 13, 18, 10, 18, 800952, tzinfo=datetime.timezone.utc)}], 'metadata': {'batch_size': 1, 'sdk_integration': 'default', 'sdk_name': 'python', 'sdk_version': '2.39.1', 'public_key': '<public_key_id>'}}
DEBUG:langfuse:making request: {"batch": [{"id": "60270390-509e-4139-bb70-c2f12eed3586", "type": "trace-create", "body": {"id": "0a9ae026-1c04-44f2-a396-8ea80769156b", "input": "Hi there"}, "timestamp": "2024-07-13T18:10:18.800952Z"}], "metadata": {"batch_size": 1, "sdk_integration": "default", "sdk_name": "python", "sdk_version": "2.39.1", "public_key": "<public_key_id>"}} to http://<langfuse_load_balancer_url>/api/public/ingestion
DEBUG:langfuse:~0 items in the Langfuse queue
DEBUG:langfuse:received response: {"errors":[],"successes":[{"id":"a2c6e83a-415b-4068-9e02-e81f2a2bd60d","status":201}]}
DEBUG:langfuse:successfully uploaded batch of 1 items
DEBUG:langfuse:received response: {"errors":[],"successes":[{"id":"60270390-509e-4139-bb70-c2f12eed3586","status":201}]}
DEBUG:langfuse:successfully uploaded batch of 1 items
DEBUG:langfuse:~0 items in the Langfuse queue
```

However, this doesn't work: 
```
from langfuse.decorators import observe
from langfuse.openai import openai # OpenAI integration
 
@observe()
def story():
    return openai.chat.completions.create(
        model="gpt-3.5-turbo",
        max_tokens=100,
        messages=[
          {"role": "system", "content": "You are a great storyteller."},
          {"role": "user", "content": "Once upon a time in a galaxy far, far away..."}
        ],
    ).choices[0].message.content
 
@observe()
def main():
    return story()
 
main()
```

The above gives the error, 
```
client.chat.completions.create(
    ...:         model="gpt-3.5-turbo",
    ...:         max_tokens=100,
    ...:         messages=[
    ...:           {"role": "system", "content": "You are a great storyteller."},
    ...:           {"role": "user", "content": "Once upon a time in a galaxy far, far away..."}
    ...:         ],
    ...:     ).choices[0].message.content
DEBUG:langfuse:Creating trace id='ff9b300c-c3b9-4407-b156-d8ad05b411c4' timestamp=datetime.datetime(2024, 7, 13, 18, 1, 29, 87493, tzinfo=datetime.timezone.utc) name='OpenAI-generation' user_id=None input=[{'role': 'system', 'content': 'You are a great storyteller.'}, {'role': 'user', 'content': 'Once upon a time in a galaxy far, far away...'}] output=None session_id=None release=None version=None metadata=None tags=None public=None
DEBUG:langfuse:Creating generation max {'id': 'd46f5f19-5513-40fd-b583-ceaa1a8d0d07', 'trace_id': 'ff9b300c-c3b9-4407-b156-d8ad05b411c4', 'release': None, 'name': 'OpenAI-generation', 'start_time': datetime.datetime(2024, 7, 13, 18, 1, 29, 74434, tzinfo=datetime.timezone.utc), 'metadata': None, 'input': [{'role': 'system', 'content': 'You are a great storyteller.'}, {'role': 'user', 'content': 'Once upon a time in a galaxy far, far away...'}], 'output': None, 'level': None, 'status_message': None, 'parent_observation_id': None, 'version': None, 'end_time': None, 'completion_start_time': None, 'model': 'gpt-3.5-turbo', 'model_parameters': {'temperature': 1, 'max_tokens': 100, 'top_p': 1, 'frequency_penalty': 0, 'presence_penalty': 0}, 'usage': None, 'trace': {'release': None}, 'prompt_version': None, 'prompt_name': None, 'user_id': None} None...
DEBUG:langfuse:item size 395
DEBUG:langfuse:Creating top-level generation {'id': 'c3b68647-7899-4bd0-b2f2-7207766cb123', 'type': 'generation-create', 'body': {'traceId': 'ff9b300c-c3b9-4407-b156-d8ad05b411c4', 'name': 'OpenAI-generation', 'startTime': datetime.datetime(2024, 7, 13, 18, 1, 29, 74434, tzinfo=datetime.timezone.utc), 'input': [{'role': 'system', 'content': 'You are a great storyteller.'}, {'role': 'user', 'content': 'Once upon a time in a galaxy far, far away...'}], 'id': 'd46f5f19-5513-40fd-b583-ceaa1a8d0d07', 'model': 'gpt-3.5-turbo', 'modelParameters': {'temperature': 1, 'max_tokens': 100, 'top_p': 1, 'frequency_penalty': 0, 'presence_penalty': 0}, 'trace': {'release': None}}} ...
DEBUG:langfuse:item size 622
DEBUG:langfuse:~0 items in the Langfuse queue
DEBUG:langfuse:~0 items in the Langfuse queue
DEBUG:langfuse:~0 items in the Langfuse queue
DEBUG:langfuse:uploading batch of 2 items
DEBUG:langfuse:uploading data: {'batch': [{'id': '5b1e4c10-a857-4910-ab35-c45ceaca9ef6', 'type': 'trace-create', 'body': {'id': 'ff9b300c-c3b9-4407-b156-d8ad05b411c4', 'timestamp': datetime.datetime(2024, 7, 13, 18, 1, 29, 87493, tzinfo=datetime.timezone.utc), 'name': 'OpenAI-generation', 'input': [{'role': 'system', 'content': 'You are a great storyteller.'}, {'role': 'user', 'content': 'Once upon a time in a galaxy far, far away...'}]}, 'timestamp': datetime.datetime(2024, 7, 13, 18, 1, 29, 87949, tzinfo=datetime.timezone.utc)}, {'id': 'c3b68647-7899-4bd0-b2f2-7207766cb123', 'type': 'generation-create', 'body': {'traceId': 'ff9b300c-c3b9-4407-b156-d8ad05b411c4', 'name': 'OpenAI-generation', 'startTime': datetime.datetime(2024, 7, 13, 18, 1, 29, 74434, tzinfo=datetime.timezone.utc), 'input': [{'role': 'system', 'content': 'You are a great storyteller.'}, {'role': 'user', 'content': 'Once upon a time in a galaxy far, far away...'}], 'id': 'd46f5f19-5513-40fd-b583-ceaa1a8d0d07', 'model': 'gpt-3.5-turbo', 'modelParameters': {'temperature': 1, 'max_tokens': 100, 'top_p': 1, 'frequency_penalty': 0, 'presence_penalty': 0}, 'trace': {'release': None}}, 'timestamp': datetime.datetime(2024, 7, 13, 18, 1, 29, 88467, tzinfo=datetime.timezone.utc)}], 'metadata': {'batch_size': 2, 'sdk_integration': 'default', 'sdk_name': 'python', 'sdk_version': '2.39.1', 'public_key': '<public_key_id>'}}
DEBUG:langfuse:making request: {"batch": [{"id": "5b1e4c10-a857-4910-ab35-c45ceaca9ef6", "type": "trace-create", "body": {"id": "ff9b300c-c3b9-4407-b156-d8ad05b411c4", "timestamp": "2024-07-13T18:01:29.087493Z", "name": "OpenAI-generation", "input": [{"role": "system", "content": "You are a great storyteller."}, {"role": "user", "content": "Once upon a time in a galaxy far, far away..."}]}, "timestamp": "2024-07-13T18:01:29.087949Z"}, {"id": "c3b68647-7899-4bd0-b2f2-7207766cb123", "type": "generation-create", "body": {"traceId": "ff9b300c-c3b9-4407-b156-d8ad05b411c4", "name": "OpenAI-generation", "startTime": "2024-07-13T18:01:29.074434Z", "input": [{"role": "system", "content": "You are a great storyteller."}, {"role": "user", "content": "Once upon a time in a galaxy far, far away..."}], "id": "d46f5f19-5513-40fd-b583-ceaa1a8d0d07", "model": "gpt-3.5-turbo", "modelParameters": {"temperature": 1, "max_tokens": 100, "top_p": 1, "frequency_penalty": 0, "presence_penalty": 0}, "trace": {"release": null}}, "timestamp": "2024-07-13T18:01:29.088467Z"}], "metadata": {"batch_size": 2, "sdk_integration": "default", "sdk_name": "python", "sdk_version": "2.39.1", "public_key": "<public_key_id>"}} to "http://<langfuse_load_balancer_url>"/api/public/ingestion
DEBUG:langfuse:~0 items in the Langfuse queue
DEBUG:langfuse:~0 items in the Langfuse queue
DEBUG:langfuse:uploading data: {'batch': [{'id': '5b1e4c10-a857-4910-ab35-c45ceaca9ef6', 'type': 'trace-create', 'body': {'id': 'ff9b300c-c3b9-4407-b156-d8ad05b411c4', 'timestamp': datetime.datetime(2024, 7, 13, 18, 1, 29, 87493, tzinfo=datetime.timezone.utc), 'name': 'OpenAI-generation', 'input': [{'role': 'system', 'content': 'You are a great storyteller.'}, {'role': 'user', 'content': 'Once upon a time in a galaxy far, far away...'}]}, 'timestamp': datetime.datetime(2024, 7, 13, 18, 1, 29, 87949, tzinfo=datetime.timezone.utc)}, {'id': 'c3b68647-7899-4bd0-b2f2-7207766cb123', 'type': 'generation-create', 'body': {'traceId': 'ff9b300c-c3b9-4407-b156-d8ad05b411c4', 'name': 'OpenAI-generation', 'startTime': datetime.datetime(2024, 7, 13, 18, 1, 29, 74434, tzinfo=datetime.timezone.utc), 'input': [{'role': 'system', 'content': 'You are a great storyteller.'}, {'role': 'user', 'content': 'Once upon a time in a galaxy far, far away...'}], 'id': 'd46f5f19-5513-40fd-b583-ceaa1a8d0d07', 'model': 'gpt-3.5-turbo', 'modelParameters': {'temperature': 1, 'max_tokens': 100, 'top_p': 1, 'frequency_penalty': 0, 'presence_penalty': 0}, 'trace': {'release': None}}, 'timestamp': datetime.datetime(2024, 7, 13, 18, 1, 29, 88467, tzinfo=datetime.timezone.utc)}], 'metadata': {'batch_size': 2, 'sdk_integration': 'default', 'sdk_name': 'python', 'sdk_version': '2.39.1', 'public_key': '<public_key_id>'}}
DEBUG:langfuse:making request: {"batch": [{"id": "5b1e4c10-a857-4910-ab35-c45ceaca9ef6", "type": "trace-create", "body": {"id": "ff9b300c-c3b9-4407-b156-d8ad05b411c4", "timestamp": "2024-07-13T18:01:29.087493Z", "name": "OpenAI-generation", "input": [{"role": "system", "content": "You are a great storyteller."}, {"role": "user", "content": "Once upon a time in a galaxy far, far away..."}]}, "timestamp": "2024-07-13T18:01:29.087949Z"}, {"id": "c3b68647-7899-4bd0-b2f2-7207766cb123", "type": "generation-create", "body": {"traceId": "ff9b300c-c3b9-4407-b156-d8ad05b411c4", "name": "OpenAI-generation", "startTime": "2024-07-13T18:01:29.074434Z", "input": [{"role": "system", "content": "You are a great storyteller."}, {"role": "user", "content": "Once upon a time in a galaxy far, far away..."}], "id": "d46f5f19-5513-40fd-b583-ceaa1a8d0d07", "model": "gpt-3.5-turbo", "modelParameters": {"temperature": 1, "max_tokens": 100, "top_p": 1, "frequency_penalty": 0, "presence_penalty": 0}, "trace": {"release": null}}, "timestamp": "2024-07-13T18:01:29.088467Z"}], "metadata": {"batch_size": 2, "sdk_integration": "default", "sdk_name": "python", "sdk_version": "2.39.1", "public_key": "<public_key_id>"}} to "http://<langfuse_load_balancer_url>"/api/public/ingestion
DEBUG:langfuse:~0 items in the Langfuse queue
DEBUG:langfuse:~0 items in the Langfuse queue
DEBUG:langfuse:~0 items in the Langfuse queue
DEBUG:langfuse:~0 items in the Langfuse queue
DEBUG:langfuse:~0 items in the Langfuse queue
DEBUG:langfuse:~0 items in the Langfuse queue
DEBUG:langfuse:uploading data: {'batch': [{'id': '5b1e4c10-a857-4910-ab35-c45ceaca9ef6', 'type': 'trace-create', 'body': {'id': 'ff9b300c-c3b9-4407-b156-d8ad05b411c4', 'timestamp': datetime.datetime(2024, 7, 13, 18, 1, 29, 87493, tzinfo=datetime.timezone.utc), 'name': 'OpenAI-generation', 'input': [{'role': 'system', 'content': 'You are a great storyteller.'}, {'role': 'user', 'content': 'Once upon a time in a galaxy far, far away...'}]}, 'timestamp': datetime.datetime(2024, 7, 13, 18, 1, 29, 87949, tzinfo=datetime.timezone.utc)}, {'id': 'c3b68647-7899-4bd0-b2f2-7207766cb123', 'type': 'generation-create', 'body': {'traceId': 'ff9b300c-c3b9-4407-b156-d8ad05b411c4', 'name': 'OpenAI-generation', 'startTime': datetime.datetime(2024, 7, 13, 18, 1, 29, 74434, tzinfo=datetime.timezone.utc), 'input': [{'role': 'system', 'content': 'You are a great storyteller.'}, {'role': 'user', 'content': 'Once upon a time in a galaxy far, far away...'}], 'id': 'd46f5f19-5513-40fd-b583-ceaa1a8d0d07', 'model': 'gpt-3.5-turbo', 'modelParameters': {'temperature': 1, 'max_tokens': 100, 'top_p': 1, 'frequency_penalty': 0, 'presence_penalty': 0}, 'trace': {'release': None}}, 'timestamp': datetime.datetime(2024, 7, 13, 18, 1, 29, 88467, tzinfo=datetime.timezone.utc)}], 'metadata': {'batch_size': 2, 'sdk_integration': 'default', 'sdk_name': 'python', 'sdk_version': '2.39.1', 'public_key': '<public_key_id>'}}
DEBUG:langfuse:making request: {"batch": [{"id": "5b1e4c10-a857-4910-ab35-c45ceaca9ef6", "type": "trace-create", "body": {"id": "ff9b300c-c3b9-4407-b156-d8ad05b411c4", "timestamp": "2024-07-13T18:01:29.087493Z", "name": "OpenAI-generation", "input": [{"role": "system", "content": "You are a great storyteller."}, {"role": "user", "content": "Once upon a time in a galaxy far, far away..."}]}, "timestamp": "2024-07-13T18:01:29.087949Z"}, {"id": "c3b68647-7899-4bd0-b2f2-7207766cb123", "type": "generation-create", "body": {"traceId": "ff9b300c-c3b9-4407-b156-d8ad05b411c4", "name": "OpenAI-generation", "startTime": "2024-07-13T18:01:29.074434Z", "input": [{"role": "system", "content": "You are a great storyteller."}, {"role": "user", "content": "Once upon a time in a galaxy far, far away..."}], "id": "d46f5f19-5513-40fd-b583-ceaa1a8d0d07", "model": "gpt-3.5-turbo", "modelParameters": {"temperature": 1, "max_tokens": 100, "top_p": 1, "frequency_penalty": 0, "presence_penalty": 0}, "trace": {"release": null}}, "timestamp": "2024-07-13T18:01:29.088467Z"}], "metadata": {"batch_size": 2, "sdk_integration": "default", "sdk_name": "python", "sdk_version": "2.39.1", "public_key": "<public_key_id>"}} to "http://<langfuse_load_balancer_url>"/api/public/ingestion
Giving up execute_task_with_backoff(...) after 3 tries (httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.)
Giving up execute_task_with_backoff(...) after 3 tries (httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.)
Giving up execute_task_with_backoff(...) after 3 tries (httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.)
ERROR:backoff:Giving up execute_task_with_backoff(...) after 3 tries (httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.)
ERROR:langfuse:error uploading: Request URL is missing an 'http://' or 'https://' protocol.
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/opt/anaconda3/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 167, in handle_request
    raise UnsupportedProtocol(
httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/langfuse/task_manager.py", line 203, in upload
    self._upload_batch(batch)
  File "/opt/anaconda3/lib/python3.11/site-packages/langfuse/task_manager.py", line 239, in _upload_batch
    execute_task_with_backoff(batch)
  File "/opt/anaconda3/lib/python3.11/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/langfuse/task_manager.py", line 237, in execute_task_with_backoff
    raise e
  File "/opt/anaconda3/lib/python3.11/site-packages/langfuse/task_manager.py", line 229, in execute_task_with_backoff
    self._client.batch_post(batch=batch, metadata=metadata)
  File "/opt/anaconda3/lib/python3.11/site-packages/langfuse/request.py", line 55, in batch_post
    res = self.post(**kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/langfuse/request.py", line 67, in post
    res = self._session.post(
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/httpx/_client.py", line 1132, in post
    return self.request(
           ^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/opt/anaconda3/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/anaconda3/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
DEBUG:langfuse:~0 items in the Langfuse queue
DEBUG:langfuse:~0 items in the Langfuse queue
```

When I use the openai langfuse wrapper client, I make sure to set these 4 env vars correctly: OPENAI_API_KEY, LANGFUSE_SECRET_KEY, LANGFUSE_PUBLIC_KEY, LANGFUSE_HOST

The issue is that if you see closely both the above logs is that, it wraps double quotes around the url, `"http://<langfuse_load_balancer_url>"/api/public/ingestion` hence it fails, whereas it doesn't do that for the traces one. I'm wondering if there's a bug with the openai langfuse wrapper. 

### To reproduce

See all the details above, with code snippets that I ran. 

### SDK and container versions

Using langfuse/langfuse:latest docker image. 
Client sdk version is - `langfuse==2.39.1`

### Are you interested to contribute a fix for this bug?

No

**Comment by ashutoshsaboo** [comment]
@marcklingen would appreciate the help on this!

**Comment by marcklingen** [comment]
@ashutoshsaboo, the issue here is that the decorator is usually configured via the environment. If this is not an option, you can also configured it like this (on top of the file before it is used for the first time):

```python
from langfuse.decorators import langfuse_context
 
# Configure the Langfuse client
langfuse_context.configure(
    host=custom_host,
)
```

See reference here: https://python.reference.langfuse.com/langfuse/decorators#LangfuseDecorator.configure
