### ISSUE TITLE
bug: SDK issue with handling 502 API while self hosting dashboard on cloud

### ISSUE THREAD

**Issue by kevinpkaria** [langfuse/langfuse#2652]
### Describe the bug

While hosting the dashboard on Azure Dev Ops, I receive the following error.
The dashboard works perfectly fine on my localhost.
(Heimdall is a name given to this project)
```
Heimdall starts Watching
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1721023467.224979       7 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache, work_serializer_dispatch
I0000 00:00:1721023467.225122       7 ev_epoll1_linux.cc:125] grpc epoll fd: 3
/usr/local/lib/python3.10/site-packages/deepeval/__init__.py:42: UserWarning: You are using deepeval version 0.21.64, however version 0.21.65 is available. You should consider upgrading via the "pip install --upgrade deepeval" command.
  warnings.warn(
status_code: 502, body: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/langfuse/api/resources/trace/client.py", line 235, in list
    _response_json = _response.json()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/langfuse/client.py", line 598, in fetch_traces
    res = self.client.trace.list(
  File "/usr/local/lib/python3.10/site-packages/langfuse/api/resources/trace/client.py", line 237, in list
    raise ApiError(status_code=_response.status_code, body=_response.text)
langfuse.api.core.api_error.ApiError: status_code: 502, body: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/langfuse/api/resources/trace/client.py", line 235, in list
    _response_json = _response.json()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/heimdall/main.py", line 9, in <module>
    traces = langfuse.fetch_traces(name="tester2").data
  File "/usr/local/lib/python3.10/site-packages/langfuse/client.py", line 611, in fetch_traces
    raise e
  File "/usr/local/lib/python3.10/site-packages/langfuse/client.py", line 598, in fetch_traces
    res = self.client.trace.list(
  File "/usr/local/lib/python3.10/site-packages/langfuse/api/resources/trace/client.py", line 237, in list
    raise ApiError(status_code=_response.status_code, body=_response.text)
langfuse.api.core.api_error.ApiError: status_code: 502, body: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

Heimdall starts Watching
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1721023467.224979       7 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache, work_serializer_dispatch
I0000 00:00:1721023467.225122       7 ev_epoll1_linux.cc:125] grpc epoll fd: 3
/usr/local/lib/python3.10/site-packages/deepeval/__init__.py:42: UserWarning: You are using deepeval version 0.21.64, however version 0.21.65 is available. You should consider upgrading via the "pip install --upgrade deepeval" command.
  warnings.warn(
status_code: 502, body: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/langfuse/api/resources/trace/client.py", line 235, in list
    _response_json = _response.json()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/langfuse/client.py", line 598, in fetch_traces
    res = self.client.trace.list(
  File "/usr/local/lib/python3.10/site-packages/langfuse/api/resources/trace/client.py", line 237, in list
    raise ApiError(status_code=_response.status_code, body=_response.text)
langfuse.api.core.api_error.ApiError: status_code: 502, body: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/langfuse/api/resources/trace/client.py", line 235, in list
    _response_json = _response.json()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/heimdall/main.py", line 9, in <module>
    traces = langfuse.fetch_traces(name="tester2").data
  File "/usr/local/lib/python3.10/site-packages/langfuse/client.py", line 611, in fetch_traces
    raise e
  File "/usr/local/lib/python3.10/site-packages/langfuse/client.py", line 598, in fetch_traces
    res = self.client.trace.list(
  File "/usr/local/lib/python3.10/site-packages/langfuse/api/resources/trace/client.py", line 237, in list
    raise ApiError(status_code=_response.status_code, body=_response.text)
langfuse.api.core.api_error.ApiError: status_code: 502, body: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

Stream closed EOF for default/fcld-heimdall-pltm-srvr-dply-6f9454fd67-tzpm9 (fcld-heimdall-pltm)
```

### To reproduce

Take a repo and push the locally hosted self hosting docker files to the repo. Make sure that the repo has postgres already set up. Upon building it, the error given above should be observed.

### SDK and container versions

langfuse==2.38.1

### Additional information

![image](https://github.com/user-attachments/assets/4649351a-1f55-4bc9-b579-b76c2251d5b9)

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Agree that the handling of the 502 by the SDK here is not very nice. Ideally let's resolve the 502 issue here first because there should not be any 502 errors when running langfuse yourself. Did you follow the self-hosting documentation?

**Comment by kevinpkaria** [comment]
Yes I did follow the entire documentation. It works perfectly fine on localhost. It's when I've deployed it on a cloud based repo - Azure DevOps when it throws this error.

**Comment by marcklingen** [comment]
Does Azure DevOps run the prebuilt containers? Most users use Azure Container instances afaik.

**Comment by kevinpkaria** [comment]
Issue is resolved. I think we were making some silly mistake somewhere.

**Comment by marcklingen** [comment]
awesome, thanks for sharing!
