### ISSUE TITLE
bug: SSO login with Cognito + Third party IDPs - Nonce Mismatch Error

### ISSUE THREAD

**Issue by jeness** [langfuse/langfuse#3084]
### Describe the bug

I am trying with to use AWS Cognito SSO (Cognito userpool is set up with a 3rd party IDP) login to Langfuse. 
I have seen the error OAuthCallback in the UI at the first time login from a browser.
![image](https://github.com/user-attachments/assets/c30c3639-0528-4c3f-8343-45cb79d3a3db)
Then I clicked on the Cognito button again, I am able to login successfully.

Note:
This issue is mentioned in next-auth.js discussions - https://github.com/nextauthjs/next-auth/discussions/3551
The solution from the above discussions (https://github.com/nextauthjs/next-auth/discussions/3551#discussioncomment-4828145) is to add `checks: "nonce"` to the `CognitoProvider`: 
```
CognitoProvider({
  clientId: process.env.COGNITO_CLIENT_ID,
  clientSecret: process.env.COGNITO_CLIENT_SECRET,
  issuer: process.env.COGNITO_ISSUER,
  checks: "nonce", // Necessary to fix a bug with Cognito's third-party providers. See the following issue and PR. Issue: https://github.com/nextauthjs/next-auth/discussions/3551 PR: https://github.com/nextauthjs/next-auth/pull/4100
})
```

### To reproduce

    1. Setup Cognito
    2. Configure to Cognito user pool to use a third party IDP
    3. SSO with docker env variables:

      ```
      AUTH_COGNITO_CLIENT_ID
      AUTH_COGNITO_CLIENT_SECRET
      AUTH_COGNITO_ISSUER
      ```

### SDK and container versions

version: "2.74.0"

### Additional information

+ Logs from container:
```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error nonce mismatch, expected undefined, got: ... {
  error: RPError: nonce mismatch, expected undefined, got: nztM6KImIJ-uTrrHjBrZNf2JeIje7zi-frPx27-j1j4btm8gCutp9rWPI6rCFLe8X-4C_dmwAcE2ozaBsutI5gN4oT4YaNikPUVyQQGPZhFbbp5KzRDp-Pta-73s06k8lbG-H9qGPPjEPIi8bvxtO04F7cGO
      at Client.validateIdToken (/app/node_modules/.pnpm/openid-client@5.6.5/node_modules/openid-client/lib/client.js:806:13)
      at async Client.callback (/app/node_modules/.pnpm/openid-client@5.6.5/node_modules/openid-client/lib/client.js:505:7)
      at async oAuthCallback (/app/node_modules/.pnpm/next-auth@4.24.7_next@14.2.3_@babel+core@7.24.3_@opentelemetry+api@1.8.0_@playwright+test@1.4_vqchpmw2nju3s6ktgv2wu6ttpi/node_modules/next-auth/core/lib/oauth/callback.js:109:16)
      at async Object.callback (/app/node_modules/.pnpm/next-auth@4.24.7_next@14.2.3_@babel+core@7.24.3_@opentelemetry+api@1.8.0_@playwright+test@1.4_vqchpmw2nju3s6ktgv2wu6ttpi/node_modules/next-auth/core/routes/callback.js:52:11)
      at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.24.7_next@14.2.3_@babel+core@7.24.3_@opentelemetry+api@1.8.0_@playwright+test@1.4_vqchpmw2nju3s6ktgv2wu6ttpi/node_modules/next-auth/core/index.js:208:28)
      at async NextAuthApiHandler (/app/node_modules/.pnpm/next-auth@4.24.7_next@14.2.3_@babel+core@7.24.3_@opentelemetry+api@1.8.0_@playwright+test@1.4_vqchpmw2nju3s6ktgv2wu6ttpi/node_modules/next-auth/next/index.js:22:19)
      at async n (/app/web/.next/server/pages/api/auth/[...nextauth].js:1:3927)
      at async /app/node_modules/.pnpm/@sentry+nextjs@8.13.0_@opentelemetry+api@1.8.0_@opentelemetry+core@1.25.1_@opentelemetry+api@_mgrdweyohp6w2gwlibvqg57s3e/node_modules/@sentry/nextjs/build/cjs/common/wrapApiHandlerWithSentry.js:90:43
      at async K (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.3_@opentelemetry+api@1.8.0_@playwright+test@1.43.1_babel-plugin-_onhpcaxa43qd7mh36cjg7s3u5i/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
      at async U.render (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.3_@opentelemetry+api@1.8.0_@playwright+test@1.43.1_babel-plugin-_onhpcaxa43qd7mh36cjg7s3u5i/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'cognito',
  message: 'nonce mismatch, expected undefined, got: ...'
}
```

### Are you interested to contribute a fix for this bug?

Yes

**Comment by marcklingen** [comment]
thanks for sharing! does this have any negative side effects based on your research?
