### ISSUE TITLE
feat: Set or reveal generationId during chat completion

### ISSUE THREAD

**Issue by alexcannan** [langfuse/langfuse#3115]
### Describe the bug

The SDK supports passing in langfuse data alongside openai (and other integrations I assume): https://langfuse.com/docs/integrations/openai/python/get-started#custom-trace-properties

I have a specific use case in my app where multiple generations are created from a single request. Each generation eventually is scored. This use case requires generationId to be accessible, so scores can be assigned later in the pipeline.

After a short support chat with @marcklingen, it sounds like assigning your own `generation_id` alongside these custom trace properties would be desirable. However, if generationId was somehow accessible within the decorate-based python flow, that would also solve my issue.

(Apologies if this is circumventing the usual issue flow.)

### To reproduce

```
> python3 -c "import uuid; from langfuse.openai import openai; r = openai.chat.completions.create(model='gpt-3.5-turbo', messages=[{'role': 'user', 'content': 'what color is the earth'}], generation_id=str(uuid.uuid4()))"
Completions.create() got an unexpected keyword argument 'generation_id'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "env/lib/python3.10/site-packages/langfuse/openai.py", line 159, in wrapper
    return func(open_ai_definitions, initialize, wrapped, args, kwargs)
  File "env/lib/python3.10/site-packages/langfuse/openai.py", line 550, in _wrap
    raise ex
  File "env/lib/python3.10/site-packages/langfuse/openai.py", line 515, in _wrap
    openai_response = wrapped(**arg_extractor.get_openai_args())
  File "env/lib/python3.10/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
TypeError: Completions.create() got an unexpected keyword argument 'generation_id'
```

### Are you interested to contribute a fix for this bug?

No

**Comment by alexcannan** [comment]
I was able to support my specific use case by adding another `@observe()` directly parenting the generations I want to score. The score is now assigned to these parent spans.

I'm not blocked by this anymore. Also, I'm not well versed in how the underlying db works, but I'd imagine generationId want to be unique, which might imply an expensive check for user-supplied IDs. Because of this, I'm happy to close this issue, but I'll leave it up to y'all.

**Comment by marcklingen** [comment]
Using the latest python sdk you can access the current observation id from the otel context
