### ISSUE TITLE
bug: prompt tracing not working with openai.chat.completion

### ISSUE THREAD

**Issue by arthuracn** [langfuse/langfuse#3142]
### Describe the bug

prompt field not understood in the openai.chat.completion.create, which makes linkage between prompt and trace impossible.

```
Uncaught Error: 400 Unrecognized request argument supplied: prompt
    at generate [as generate] (../../.yarn/__virtual__/openai-virtual-3e4fbf1542/6/.yarn/berry/cache/openai-npm-4.55.0-cda6bb045f-10c0.zip/node_modules/openai/src/error.ts:69:64)
    at makeStatusError [as makeStatusError] (../../.yarn/__virtual__/openai-virtual-3e4fbf1542/6/.yarn/berry/cache/openai-npm-4.55.0-cda6bb045f-10c0.zip/node_modules/openai/src/core.ts:397:2)
    at makeRequest [as makeRequest] (../../.yarn/__virtual__/openai-virtual-3e4fbf1542/6/.yarn/berry/cache/openai-npm-4.55.0-cda6bb045f-10c0.zip/node_modules/openai/src/core.ts:460:12)
    at async wrapMethod (../../../../../../../.yarn/berry/cache/langfuse-npm-3.19.0-174cde63a7-10c0.zip/node_modules/langfuse/src/openai/traceMethod.ts:70:8)
    at async handler (../../convex/openai.ts:156:14)
```

### To reproduce

This is the code producing the issue

```
import { Langfuse, observeOpenAI } from "langfuse";
import OpenAI from "openai";
const langfuse = new Langfuse();

const chatPrompt = await langfuse.getPrompt("prompt-name", undefined, {
      type: "chat",
      label: "production"
    });
const openai = observeOpenAI(new OpenAI(), {
      langfusePrompt: chatPrompt,
    });
    const stream = await openai.chat.completions.create({
      prompt: chatPrompt.prompt, // this is causing the error
      messages: messages,
      model: "gpt-4o",
      stream: true,
    });
```

### SDK and container versions

`langfuse@npm: 3.19.0`

### Are you interested to contribute a fix for this bug?

No

**Comment by arthuracn** [comment]
@PFacheris

**Comment by marcklingen** [comment]
Can you try passing the prompt object instead of the chatPrompt.prompt?

```typescript
const stream = await openai.chat.completions.create({
      prompt: chatPrompt,
      messages: messages,
      model: "gpt-4o",
      stream: true,
});
 ```

**Comment by arthuracn** [comment]
Hi, thanks for answering so fast.
I get the same error, what seems to be causing the error is the prompt field itself:

```
Uncaught Error: 400 Unrecognized request argument supplied: prompt
    at generate [as generate] (../../.yarn/__virtual__/openai-virtual-3e4fbf1542/6/.yarn/berry/cache/openai-npm-4.55.0-cda6bb045f-10c0.zip/node_modules/openai/src/error.ts:69:64)
    at makeStatusError [as makeStatusError] (../../.yarn/__virtual__/openai-virtual-3e4fbf1542/6/.yarn/berry/cache/openai-npm-4.55.0-cda6bb045f-10c0.zip/node_modules/openai/src/core.ts:397:2)
    at makeRequest [as makeRequest] (../../.yarn/__virtual__/openai-virtual-3e4fbf1542/6/.yarn/berry/cache/openai-npm-4.55.0-cda6bb045f-10c0.zip/node_modules/openai/src/core.ts:460:12)
    at async wrapMethod (../../../../../../../.yarn/berry/cache/langfuse-npm-3.19.0-174cde63a7-10c0.zip/node_modules/langfuse/src/openai/traceMethod.ts:70:8)
    at async handler (../../convex/openai.ts:156:6)
```

> Can you try passing the prompt object instead of the chatPrompt.prompt?
> 
> ```ts
> const stream = await openai.chat.completions.create({
>       prompt: chatPrompt,
>       messages: messages,
>       model: "gpt-4o",
>       stream: true,
> });
> ```

**Comment by marcklingen** [comment]
Sorry, the answer was too fast, should have checked the docs before auto-completing from the python sdk.

Linking to prompts works like this when using OpenAI JS

```typescript
import { observeOpenAI } from "langfuse";
import OpenAI from "openai";
 
const langfusePrompt = await langfuse.getPrompt("prompt-name"); // Fetch a previously created prompt
 
const res = await observeOpenAI(new OpenAI(), {
  langfusePrompt, // pass langfuse prompt here
}).completions.create({
  prompt: langfusePrompt.prompt, // confusing, this is the actual message passed to the instruct model which does not use the messages/chat-ml api
  model: "gpt-3.5-turbo-instruct",
  max_tokens: 300,
});
```

Docs: https://langfuse.com/docs/integrations/openai/js/get-started#link-to-langfuse-prompts

**Comment by marcklingen** [comment]
closing for now, please reopen in case this did not fix your issue

**Comment by arthuracn** [comment]
I would like to use the `openai.chat.completions.create` as the openai.completion.create does now work with gpt-40 and raise this error:

```
openai:doCompletion
failure
780ms
Uncaught Error: 404 This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?
    at generate [as generate] (../.yarn/__virtual__/openai-virtual-3e4fbf1542/6/.yarn/berry/cache/openai-npm-4.55.0-cda6bb045f-10c0.zip/node_modules/openai/src/error.ts:81:62)
    at makeStatusError [as makeStatusError] (../.yarn/__virtual__/openai-virtual-3e4fbf1542/6/.yarn/berry/cache/openai-npm-4.55.0-cda6bb045f-10c0.zip/node_modules/openai/src/core.ts:397:2)
    at makeRequest [as makeRequest] (../.yarn/__virtual__/openai-virtual-3e4fbf1542/6/.yarn/berry/cache/openai-npm-4.55.0-cda6bb045f-10c0.zip/node_modules/openai/src/core.ts:460:12)
    at async wrapMethod (../../../../../../.yarn/berry/cache/langfuse-npm-3.19.0-174cde63a7-10c0.zip/node_modules/langfuse/src/openai/traceMethod.ts:70:8)
```

**Comment by arthuracn** [comment]
> closing for now, please reopen in case this did not fix your issue

https://github.com/marcklingen I don't see how I can re-open the issue, could you do it please?

**Comment by hassiebp** [comment]
@arthuracn Could you please share a full example of the failing code? The error you mentioned looks like a wrongly configured model rather than a Langfuse error. You have likely tried to use chat model features for a model that is not supporting that.

**Comment by arthuracn** [comment]
@kalim.amzad.chy@gmail.com

**Comment by arthuracn** [comment]
https://github.com/KalimAmzad

**Comment by hassiebp** [comment]
Closing this as presumably resolved.
