### ISSUE TITLE
bug: Langfuse run not found in on_chain_ned with LangChain AgentExecutor

### ISSUE THREAD

**Issue by DARK-art108** [langfuse/langfuse#3296]
### Describe the bug

self.runs[run_id] = self.runs[parent_run_id].span(**content)
KeyError: UUID('eca3246c-c6fc-4e0c-a8ea-34c906f2cd73')
run not found

Langfuse version: 2.47.1
Langchain: 0.2.3
Langchain-core: 0.2.5

### To reproduce

The error is produced while using the agenexecutor from langchain.

### Are you interested to contribute a fix for this bug?

No

**Comment by DARK-art108** [comment]
@marcklingen any fix for this, I tried with package upgrade and downgrade still it is same.

**Comment by marcklingen** [comment]
can you share more details on how you integrated with langfuse? did you pass the callback handler to the invoke/stream method?

**Comment by DARK-art108** [comment]
I am passing the langfuse callback in the below AgentExecutor invoke and using .invoke method

from langchain.agents import AgentExecutor

agent_executor = AgentExecutor(agent=agent, tools=tools)


agent_executor.invoke()

@marcklingen

**Comment by hassiebp** [comment]
Hi @DARK-art108 - could you please share a full minimum repro example? We had a similar issue in the past that we have fixed, so curious to understand the exact case for which we get this error.

**Comment by hassiebp** [comment]
Closing this as stale.

**Comment by sharrajesh** [comment]
has this been resolved

i see this in the async mode

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 466, in on_chain_error
    self.runs[run_id] = self.runs[run_id].end(
                        ~~~~~~~~~^^^^^^^^
KeyError: UUID('61f605bc-3247-4283-87ae-06a489f70063')

i am langfuse its code in @observability.py initialized in @bot.py 


its relevant code inside @agent_utils.py @agent_response.py 

i am seeing this error occasionally

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 466, in on_chain_error
    self.runs[run_id] = self.runs[run_id].end(
                        ~~~~~~~~~^^^^^^^^
KeyError: UUID('61f605bc-3247-4213-87ae-06a489f70063')


2024-11-01 18:30:48 - langchain_core.callbacks.manager - WARNING - Error in LangChainTracer.on_chain_error callback: TracerException('No indexed run ID 61f605bc-3227-4283-87ae-06a489f70063.')

**Comment by hassiebp** [comment]
@sharrajesh Could you please share an repro example of your chain for which you see this error?
