### ISSUE TITLE
bug: langfuse:Unexpected error occurred. Please check your request and contact support: https://langfuse.com/support

### ISSUE THREAD

**Issue by DavidHWWang** [langfuse/langfuse#3337]
### Describe the bug

I'm using Fastapi to build my chatbot server and encounter this error
`ERROR:langfuse:Unexpected error occurred. Please check your request and contact support: https://langfuse.com/support.
`

### chatbot_view.py
```
@router.post("/ess/QA/chat/langfuse")
async def qa_chat_langfuse_endpoint(user_input: UserInput, request: Request, background_tasks: BackgroundTasks):
    which_system = "QA"
    user_mail: str = getattr(request.state, "user_mail", None)

    if not user_input.uuid:
        user_input.uuid = generate_uuid()

    field_mapping = {"title_field": "GPT_Question", "url_field": "tb_QA_Case_Serial"}
    index_name = "ess-qa-chat-index"
    embedding_deployment_name = "edm"
    response: dict = chat_with_langfuse(
        user_input.input,
        which_system,
        user_input.uuid,
        field_mapping,
        index_name,
        embedding_deployment_name,
        use_azure_search=False,
    )
    
    response_context: str = response.get("content", "")
    total_tokens: int = response.get("total_tokens", 0)
    history_log: str = response.get("history_log", "")
    citations: list = response.get("citations", [])
    
    return JSONResponse(
        content={
            "output": response_context,
            "uuid": user_input.uuid,
            "citation": citations,
        },
        status_code=200,
    )
```

### chatbot_controller.py
```
def chat_with_langfuse(
    user_input: str,
    which_system: str,
    uuid: str,
    field_mapping: dict,
    index_name: str,
    embedding_deployment_name: str,
    use_azure_search: bool = True,
) -> dict:
    log_summary = get_log_summary(log_uuid=uuid)

    ai_service = AzureOpenAIGenerator()
    ai_service.initialize_langfuse(
        azure_api_key=settings.AZURE_OPENAI_API_KEY,
        azure_endpoint=settings.AZURE_OPENAI_ENDPOINT,
    )

    config = get_chatbot_config(which_system=which_system)

    if use_azure_search:
        response = ai_service.chat_ai_search(
            user_content=f"[History log] {log_summary}\n[Question] {user_input}",
            ai_search_endpoint=settings.AZURE_AI_SEARCH_URL,
            ai_search_index_name=index_name,
            ai_search_key=settings.AZURE_AI_SEARCH_API_KEY,
            embedding_deployment_name=embedding_deployment_name,
            deployment_name=config.get("deployment_name", "gpt-35"),
            fields_mapping=field_mapping,
            system=config.get("system_prompt", ""),
            variable=config.get("variable", {}),
            shots=config.get("shots", []),
            return_total_tokens=True,
        )
    else:
        response = ai_service.chat(
            user_content=f"[History log] {log_summary}\n[Question] {user_input}",
            deployment_name=config.get("deployment_name", "gpt-35"),
            system=config.get("system_prompt", ""),
            variable=config.get("variable", {}),
            shots=config.get("shots", []),
            return_total_tokens=True
        )

    response["history_log"] = log_summary if uuid else ""

    return response
```

And here's part of my `AzureOpenAIGenerator`:
```
    from langfuse.openai import AzureOpenAI as LangfuseAzureOpenAI

    class AzureOpenAIGenerator:

        def initialize_langfuse(
            self, 
            azure_endpoint: str,
            azure_api_key: str,
            azure_api_version: str = "2024-02-01",
        ) -> None:
            self.azure_client = LangfuseAzureOpenAI(
                azure_endpoint=azure_endpoint,
                api_key=azure_api_key,
                api_version=azure_api_version,
            )
            return

        def chat_ai_search(
            self,
            user_content: str,
            ai_search_endpoint: str,
            ai_search_index_name: str,
            ai_search_key: str,
            embedding_deployment_name: str,
            deployment_name: str,
            fields_mapping: dict = {},
            system: str = "",
            variable: dict = {},
            shots: list = [],
            return_total_tokens: bool = False,
        ) -> dict:
            if type(user_content) is not str:
                raise Exception("user_content must be string type")
    
            workbench_message = [{"role": "user", "content": f"{user_content}"}]
    
            message = []
            if system != "":
                message.append({"role": "system", "content": f"{system}"})
    
            if shots != []:
                for item in shots:
                    message.append(item)
    
            message += workbench_message
    
            extra_body = {
                "data_sources": [
                    {
                        "type": "azure_search",
                        "parameters": {
                            "endpoint": ai_search_endpoint,
                            "index_name": ai_search_index_name,
                            "authentication": {
                                "type": "api_key",
                                "key": ai_search_key,
                            },
                            "embedding_dependency": {
                                "deployment_name": embedding_deployment_name,
                                "type": "deployment_name",
                            },
                            "query_type": "vector_simple_hybrid",
                            "fields_mapping": fields_mapping,
                        },
                    }
                ]
            }
            response = self.azure_client.chat.completions.create(
                model=deployment_name,
                temperature=variable.get("temperature", 0.3),
                max_tokens=variable.get("max_tokens", 800),
                top_p=variable.get("top_p", 1),
                presence_penalty=variable.get("presence_penalty", 0),
                frequency_penalty=variable.get("frequency_penalty", 0),
                stop=variable.get("stop", ""),
                n=variable.get("n", 1),
                messages=message,
                extra_body=extra_body,
            )
    
            ret = {
                "content": response.choices[0].message.content,
                "citations": response.choices[0].message.context.get("citations"),
            }
            if return_total_tokens:
                ret["total_tokens"] = response.usage.total_tokens
            return ret
```

### Are you interested to contribute a fix for this bug?

No

**Comment by DavidHWWang** [comment]
I only created one endpoint for testing langfuse. 

I've add `auth_check() `when initialize azure client:
```
from langfuse.decorators import langfuse_context

    def initialize_langfuse(
        self,
        azure_endpoint: str,
        azure_api_key: str,
        azure_api_version: str = "2024-02-01",
    ) -> None:
        self.azure_client = LFAzureOpenAI(
            azure_endpoint=azure_endpoint,
            api_key=azure_api_key,
            api_version=azure_api_version,
        )
        if not langfuse_context.auth_check():
            raise Exception("Langfuse auth check failed")
        return
```

And here's part of the error message:
`python_app-1  |   File "/usr/local/lib/python3.11/site-packages/langfuse/decorators/langfuse_decorator.py", line 1051, in auth_check
python_app-1  |     self._log.error("No Langfuse object found in the current context", e)
python_app-1  | Message: 'No Langfuse object found in the current context'`

**Comment by marcklingen** [comment]
langfuse_context does not work here as you do not use the langfuse decorator. 

please use:

```
self.azure_client.langfuse_auth_check()
```

**Comment by DavidHWWang** [comment]
Here's the new error:
`'AzureOpenAI' object has no attribute 'langfuse_auth_check'`

**Comment by hassiebp** [comment]
@DavidHWWang could you please adjust your check to this and report back?

```python
from langfuse.openai import openai, AzureOpenAI as LFAzureOpenAI

    def initialize_langfuse(
        self,
        azure_endpoint: str,
        azure_api_key: str,
        azure_api_version: str = "2024-02-01",
    ) -> None:
        self.azure_client = LFAzureOpenAI(
            azure_endpoint=azure_endpoint,
            api_key=azure_api_key,
            api_version=azure_api_version,
        )
        if not openai.langfuse_auth_check():
            raise Exception("Langfuse auth check failed")
        return
```

**Comment by DavidHWWang** [comment]
```
2024-09-20 08:43:04 ERROR:langfuse:Unexpected error occurred. Please check your request and contact support: https://langfuse.com/support.
2024-09-20 08:43:04 ERROR:    Exception in ASGI application
2024-09-20 08:43:04 INFO:     192.168.65.1:23781 - "POST /v1.0/chatbot/ess/QA/chat/langfuse HTTP/1.1" 400 Bad Request
2024-09-20 08:43:04 Traceback (most recent call last):
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
2024-09-20 08:43:04     yield
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
2024-09-20 08:43:04     resp = self._pool.handle_request(req)
2024-09-20 08:43:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
2024-09-20 08:43:04     raise exc from None
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
2024-09-20 08:43:04     response = connection.handle_request(
2024-09-20 08:43:04                ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
2024-09-20 08:43:04     raise exc
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
2024-09-20 08:43:04     stream = self._connect(request)
2024-09-20 08:43:04              ^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect
2024-09-20 08:43:04     stream = self._network_backend.connect_tcp(**kwargs)
2024-09-20 08:43:04              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
2024-09-20 08:43:04     with map_exceptions(exc_map):
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
2024-09-20 08:43:04     self.gen.throw(typ, value, traceback)
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2024-09-20 08:43:04     raise to_exc(exc) from exc
2024-09-20 08:43:04 httpcore.ConnectError: [Errno 111] Connection refused
2024-09-20 08:43:04 
2024-09-20 08:43:04 The above exception was the direct cause of the following exception:
2024-09-20 08:43:04 
2024-09-20 08:43:04 Traceback (most recent call last):
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-09-20 08:43:04     result = await app(  # type: ignore[func-returns-value]
2024-09-20 08:43:04              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-09-20 08:43:04     return await self.app(scope, receive, send)
2024-09-20 08:43:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-09-20 08:43:04     await super().__call__(scope, receive, send)
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-09-20 08:43:04     await self.middleware_stack(scope, receive, send)
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-09-20 08:43:04     raise exc
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-09-20 08:43:04     await self.app(scope, receive, _send)
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
2024-09-20 08:43:04     with collapse_excgroups():
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
2024-09-20 08:43:04     self.gen.throw(typ, value, traceback)
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
2024-09-20 08:43:04     raise exc
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
2024-09-20 08:43:04     response = await self.dispatch_func(request, call_next)
2024-09-20 08:43:04                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/workdir/app/middleware/token_middleware.py", line 37, in dispatch
2024-09-20 08:43:04     response = await call_next(request)
2024-09-20 08:43:04                ^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
2024-09-20 08:43:04     raise app_exc
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
2024-09-20 08:43:04     await self.app(scope, receive_or_disconnect, send_no_error)
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-09-20 08:43:04     await self.app(scope, receive, send)
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-09-20 08:43:04     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-09-20 08:43:04     raise exc
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-09-20 08:43:04     await app(scope, receive, sender)
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-09-20 08:43:04     await self.middleware_stack(scope, receive, send)
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-09-20 08:43:04     await route.handle(scope, receive, send)
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-09-20 08:43:04     await self.app(scope, receive, send)
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-09-20 08:43:04     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-09-20 08:43:04     raise exc
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-09-20 08:43:04     await app(scope, receive, sender)
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-09-20 08:43:04     response = await func(request)
2024-09-20 08:43:04                ^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-09-20 08:43:04     raw_response = await run_endpoint_function(
2024-09-20 08:43:04                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-09-20 08:43:04     return await dependant.call(**values)
2024-09-20 08:43:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/workdir/app/views/chatbot_view.py", line 95, in qa_chat_langfuse_endpoint
2024-09-20 08:43:04     response: dict = chat_with_langfuse(
2024-09-20 08:43:04                      ^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/workdir/app/controllers/chatbot_controller.py", line 157, in chat_with_langfuse
2024-09-20 08:43:04     ai_service.initialize_langfuse(
2024-09-20 08:43:04   File "/workdir/package/openai_connector.py", line 142, in initialize_langfuse
2024-09-20 08:43:04     if not openai.langfuse_auth_check():
2024-09-20 08:43:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/langfuse/openai.py", line 636, in langfuse_auth_check
2024-09-20 08:43:04     return self._langfuse.auth_check()
2024-09-20 08:43:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/langfuse/client.py", line 407, in auth_check
2024-09-20 08:43:04     raise e
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/langfuse/client.py", line 395, in auth_check
2024-09-20 08:43:04     projects = self.client.projects.get()
2024-09-20 08:43:04                ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/langfuse/api/resources/projects/client.py", line 49, in get
2024-09-20 08:43:04     _response = self._client_wrapper.httpx_client.request(
2024-09-20 08:43:04                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/langfuse/api/core/http_client.py", line 193, in request
2024-09-20 08:43:04     response = self.httpx_client.request(
2024-09-20 08:43:04                ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 827, in request
2024-09-20 08:43:04     return self.send(request, auth=auth, follow_redirects=follow_redirects)
2024-09-20 08:43:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
2024-09-20 08:43:04     response = self._send_handling_auth(
2024-09-20 08:43:04                ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
2024-09-20 08:43:04     response = self._send_handling_redirects(
2024-09-20 08:43:04                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
2024-09-20 08:43:04     response = self._send_single_request(request)
2024-09-20 08:43:04                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
2024-09-20 08:43:04     response = transport.handle_request(request)
2024-09-20 08:43:04                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
2024-09-20 08:43:04     with map_httpcore_exceptions():
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
2024-09-20 08:43:04     self.gen.throw(typ, value, traceback)
2024-09-20 08:43:04   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
2024-09-20 08:43:04     raise mapped_exc(message) from exc
2024-09-20 08:43:04 httpx.ConnectError: [Errno 111] Connection refused
```

Here are the environment:
```
LANGFUSE_SECRET_KEY="sk-lf-db98d..."
LANGFUSE_PUBLIC_KEY="pk-lf-8631e..."
LANGFUSE_HOST="http://localhost:3000"
```

**Comment by DavidHWWang** [comment]
I've found out I need to change `LANGFUSE_HOST="http://localhost:3000"` to `http://langfuse:3000` when using docker-compose.

And it works!

Thanks.

**Comment by marcklingen** [comment]
this makes sense if you try to connect to the langfuse instance from within your docker deployment. thanks for sharing, i'll add this to the documentation.

**Comment by daaain** [comment]
I was getting this error because the URL was quoted in the `.env` file and that somehow got loaded with the quotes within quotes in Python...

So instead of this:

```
LANGFUSE_HOST="https://cloud.langfuse.com"
```

I had to have this:

```
LANGFUSE_HOST=https://cloud.langfuse.com
```

**Comment by marcklingen** [comment]
thanks for sharing! Where did you get this from? Would love to fix the docs

**Comment by daaain** [comment]
I got it from [here](https://langfuse.com/docs/integrations/litellm/tracing#3-litellm-python-sdk) but the quotes are needed in the example Python so it's not wrong, but I guess realistically people shouldn't really be pasting the keys directly in the code so maybe a bit of rework would be good.

**Comment by hvquy001** [comment]
Also facing this problem. All env copied from the cloud setup wizard. Running on k8s. Remove double quote was fine

**Comment by codeustad** [comment]
I had to use `LANGFUSE_HOST=http://host.containers.internal:3000`

**Comment by durgesh-rathod-sf** [comment]
my application was running in docker container and my langfuse was hosted on the host machine.
i used 
os.environ["LANGFUSE_HOST"]="http://host.docker.internal:3000"
and it worked
