### ISSUE TITLE
bug: Spans being attached to incorrect parent span when reusing LangchainCallbackHandler across invocations made in parallel

### ISSUE THREAD

**Issue by Chengdyc** [langfuse/langfuse#3491]
### Describe the bug

The recommendation from Langfuse team is that LangchainCallbackHandler should be created once in global scope, then reused across all invocations in the process. However, we have a use case where we are invoking chains in parallel, both via asyncio and via Threadpool, and reusing the LangchainCallbackHandler causes spans to be attached to incorrect parent span.

### To reproduce

Example code that would result in the described behavior:

```
from langchain_openai import ChatOpenAI
import os
chat_llm = ChatOpenAI(model_name="gpt-4o-mini", openai_api_key=os.getenv('OPENAI_API_TOKEN'))

import os
from langfuse.callback import CallbackHandler
import uuid

session_id = str(uuid.uuid4())

callback_handler = CallbackHandler(
      secret_key=os.getenv('LANGFUSE_SK'),
      public_key=os.getenv('LANGFUSE_PK'),
      host=os.getenv('LANGFUSE_URL'),
      user_id="notebookuser",
      session_id=session_id
)

from uuid import UUID
from langchain_core.runnables import RunnableConfig
workflow_id = str(uuid.uuid4())
tags = ['mytest']
metadata = {"workflow_id": workflow_id}

def create_runnable_config():
    configurable={}

    return RunnableConfig(
        run_id=UUID(workflow_id),
        callbacks=[callback_handler],
        configurable=configurable,
        tags=tags,
        metadata=metadata,
    )


from langchain_core.output_parsers import StrOutputParser

runnable_config = create_runnable_config()

async def call_llm(input: str):
    return await (chat_llm | StrOutputParser()).ainvoke(input, config=runnable_config)


coro_list = [
    call_llm("how are you"),
    call_llm("what's the weather")
]


import asyncio
responses = await asyncio.gather(*coro_list)
```

### SDK and container versions

Langfuse Python sdk 2.51.1

Langfuse server at git tag 2.64.0

### Additional information

relevant discussion: https://github.com/orgs/langfuse/discussions/3485#discussioncomment-10767959

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for opening the issue, we will look into this

**Comment by Chengdyc** [comment]
What the trace looks like in Langfuse UI

![image](https://github.com/user-attachments/assets/987da332-4db4-41ce-a486-a2ea0215a2dc)

2 'ChatOpenAI' spans are under one 'RunnableSequence' span, and one of the 'RunnableSequenceSpan' is empty. 

If the spans are recorded correctly, each 'RunnableSequence' span should have 1 'ChatOpenAI' span and 1 StrOutputParser span as children.

**Comment by Chengdyc** [comment]
I'm also getting this stack trace when I run the code

```
UUID('4e3b888e-9386-43b1-be29-c2c2013c372b')
Traceback (most recent call last):
  File "/home/xxx/workspace/yyy/venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 244, in on_chain_start
    self.runs[run_id] = self.runs[parent_run_id].span(**content)
                        ~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: UUID('4e3b888e-9386-43b1-be29-c2c2013c372b')
run not found
Traceback (most recent call last):
  File "/home/xxx/workspace/yyy/venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 430, in on_chain_end
    raise Exception("run not found")
Exception: run not found
run not found
Traceback (most recent call last):
  File "/home/xxx/workspace/yyy/venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 430, in on_chain_end
    raise Exception("run not found")
Exception: run not found
```

**Comment by Chengdyc** [comment]
Also happening if I use ThreadPoolExecutor to parallelize the calls

code:

```
import os
from langfuse.callback import CallbackHandler
import uuid

session_id = str(uuid.uuid4())

callback_handler = CallbackHandler(
    secret_key=os.getenv('LANGFUSE_SK'),
    public_key=os.getenv('LANGFUSE_PK'),
    host=os.getenv('LANGFUSE_URL'),
    user_id="notebookuser",
    session_id=session_id
)

# initialize interfaces to LLMs
from langchain_openai import ChatOpenAI
import os
chat_llm = ChatOpenAI(model_name="gpt-4o-mini", openai_api_key=os.getenv('OPENAI_API_TOKEN'))

from uuid import UUID
from langchain_core.runnables import RunnableConfig

def create_runnable_config(workflow_id):
    configurable={}

    return RunnableConfig(
        run_id=UUID(workflow_id),
        callbacks=[callback_handler],
        configurable=configurable,
        tags=['mytest'],
        metadata={"workflow_id": workflow_id},
    )


from langchain_core.output_parsers import StrOutputParser

workflow_id = str(uuid.uuid4())
runnable_config = create_runnable_config(workflow_id)

def call_llm(input: str):
    return (chat_llm | StrOutputParser()).invoke(input, config=runnable_config)

from concurrent import futures
from concurrent.futures import as_completed

with futures.ThreadPoolExecutor() as executor:
    futures = [
        executor.submit(
            call_llm, "how are you"
        ),
        executor.submit(
            call_llm, "what's the weather"
        ),
        executor.submit(
            call_llm, "what's the best music"
        ),
        executor.submit(
            call_llm, "what's the best browser"
        )
    ]
    for future in as_completed(futures):
        print(future.result())
```

stacktrace same as the above one is thrown in this case as well.

what it looks like in Langfuse UI
![image](https://github.com/user-attachments/assets/7e6b08d4-fbe9-4fce-b43a-067fb392a0bf)

**Comment by hassiebp** [comment]
Thanks for reporting this @Chengdyc ! Unfortunately I cannot reproduce the issue using langfuse python 2.52.2 and langchain versions

```
langchain==0.2.16            
langchain-community==0.2.16     
langchain-core==0.2.38
langchain-opena==0.1.7
```

Here's the example I tested successfully:

```python
import asyncio
from langchain_openai import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser

callback_handler = CallbackHandler()
chat_llm = ChatOpenAI(model="gpt-4o-mini")

async def call_llm(input: str):
    return await (chat_llm | StrOutputParser()).ainvoke(
        input, config={"callbacks": [callback_handler]}
    )

questions = [
    "What's the capital of France?",
    "How do you make pancakes?",
    "Who wrote 'To Kill a Mockingbird'?",
    "What's the chemical formula for water?",
    "When was the Moon landing?",
    "What's the largest planet in our solar system?",
    "How many legs does a spider have?",
    "What's the boiling point of water in Celsius?",
    "Who painted the Mona Lisa?",
    "What's the square root of 64?",
]

coro_list = [call_llm(question) for question in questions]

responses = await asyncio.gather(*coro_list)

callback_handler.flush()
```

Could you please try upgrading Langchain and try again?

**Comment by Chengdyc** [comment]
The problem still persists. Here're the versions I'm using
```
Name: langfuse
Version: 2.51.1
Name: langchain
Version: 0.2.16
Name: langchain-core
Version: 0.2.41
Name: langchain-community
Version: 0.2.16
Name: langchain-openai
Version: 0.1.16
```
Langfuse server is latest v2.81

We're trying to attach all the spans to the same trace. please see this discussion https://github.com/orgs/langfuse/discussions/2351 on why we're doing that.

If you specify the run_id in the Langchain config (RunnableConfig), you'll be able to reproduce the bug. here's the updated code:

```
import asyncio
from langchain_openai import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser

callback_handler = CallbackHandler()
chat_llm = ChatOpenAI(model="gpt-4o-mini")

workflow_id=str(uuid.uuid4())
print(workflow_id)

async def call_llm(input: str):
    return await (chat_llm | StrOutputParser()).ainvoke(
        input, config={"callbacks": [callback_handler], "run_id": workflow_id}
    )

questions = [
    "What's the capital of France?",
    "How do you make pancakes?",
    "Who wrote 'To Kill a Mockingbird'?",
    "What's the chemical formula for water?",
    "When was the Moon landing?",
    "What's the largest planet in our solar system?",
    "How many legs does a spider have?",
    "What's the boiling point of water in Celsius?",
    "Who painted the Mona Lisa?",
    "What's the square root of 64?",
]

coro_list = [call_llm(question) for question in questions]

responses = await asyncio.gather(*coro_list)

callback_handler.flush()
```

**Comment by Chengdyc** [comment]
Maybe we need to set the parent trace/observation id explicitly? https://langfuse.com/docs/sdk/python/decorators#set-parent-trace-id-or-parent-span-id
the example in the docs is using @observe decorator, but we're using LangchainCallbackHandler. is there a way to set parent trace/observation id via the callback handler?

**Comment by hassiebp** [comment]
Exactly, having the same traceID set via the run ID creates the issue. What you can try is to first create a trace manually and get the Langchain handler from it. That will associate the parallel runs with the same trace. 

https://langfuse.com/docs/integrations/langchain/tracing#interoperability , please take a look at the tab `Python Low level SDK`

**Comment by Chengdyc** [comment]
In our case, the parent trace is created in a separate process. is there a way to serialize the span state and recreate it across process boundaries so we can obtain the callback handlers for the child spans?

**Comment by Chengdyc** [comment]
Looks like I can use the low-level SDK to create the trace with desired id first, then obtain the LangchainCallbackHandler from the trace. this way, I can avoid creating new LangchainCallbackHandler instances. I tested this solution and it seems to work fine so far.

**Comment by hassiebp** [comment]
Thanks for sharing your solution!
