### ISSUE TITLE
bug: The langchain 'run_name' cannot be retrieved for some particular langgraph nodes

### ISSUE THREAD

**Issue by elonakoromani** [langfuse/langfuse#3578]
### Describe the bug

The langchain 'run_name' for cannot be retrieved for some defined langgraph nodes. 

'NoneType' object has no attribute 'get'
2024-10-04 16:29:17 Traceback (most recent call last):
2024-10-04 16:29:17   File "/opt/venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 291, in __generate_trace_and_parent
2024-10-04 16:29:17     class_name = self.get_langchain_run_name(serialized, **kwargs)
2024-10-04 16:29:17                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-04 16:29:17   File "/opt/venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 162, in get_langchain_run_name
2024-10-04 16:29:17     return serialized.get("name", serialized.get("id", ["<unknown>"])[-1])
2024-10-04 16:29:17            ^^^^^^^^^^^^^^
2024-10-04 16:29:17 AttributeError: 'NoneType' object has no attribute 'get'
2024-10-04 16:29:17 'NoneType' object has no attribute 'get'
2024-10-04 16:29:17 Traceback (most recent call last):
2024-10-04 16:29:17   File "/opt/venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 233, in on_chain_start
2024-10-04 16:29:17     "name": self.get_langchain_run_name(serialized, **kwargs),
2024-10-04 16:29:17             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-04 16:29:17   File "/opt/venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 162, in get_langchain_run_name
2024-10-04 16:29:17     return serialized.get("name", serialized.get("id", ["<unknown>"])[-1])
2024-10-04 16:29:17            ^^^^^^^^^^^^^^
2024-10-04 16:29:17 AttributeError: 'NoneType' object has no attribute 'get'
2024-10-04 16:29:17 run not found
2024-10-04 16:29:17 Traceback (most recent call last):
2024-10-04 16:29:17   File "/opt/venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 430, in on_chain_end
2024-10-04 16:29:17     raise Exception("run not found")
2024-10-04 16:29:17 Exception: run not found

### To reproduce

I am using Langfuse to trace a Langgraph agent. 

langfuse_handler = CallbackHandler(
    host=env("LANGFUSE_HOST"), public_key=env("LANGFUSE_PUBLIC_KEY"), secret_key=env("LANGFUSE_SECRET_KEY")
)

graph = self._initialize_graph()
tracing_config = {"callbacks": [langfuse_handler]}

runnable_config = RunnableConfig(configurable={"thread_id": str(uuid4())})
runnable_config.update(tracing_config)

        async for event in graph.astream_events(
            input={
                "user_query": messages[-1].content,
                # TODO: Add only the last k messages.
                "messages": _hai_to_lc_messages(_extract_history(messages, self.last_k_messages_as_history)),
                "document_string": None,
                "agent_system_prompt_template": self.agent_system_prompt_template,
            },
            config=**runnable_config**,
            version="v2",
        ): 
.......

The end result is traced, but when some of the langgraph nodes are processed I get the following error the the langchain run name cannot be retrieved.

'NoneType' object has no attribute 'get'
2024-10-04 16:29:17 Traceback (most recent call last):
2024-10-04 16:29:17   File "/opt/venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 291, in __generate_trace_and_parent
2024-10-04 16:29:17     class_name = self.get_langchain_run_name(serialized, **kwargs)
2024-10-04 16:29:17                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-04 16:29:17   File "/opt/venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 162, in get_langchain_run_name
2024-10-04 16:29:17     return serialized.get("name", serialized.get("id", ["<unknown>"])[-1])
2024-10-04 16:29:17            ^^^^^^^^^^^^^^
2024-10-04 16:29:17 AttributeError: 'NoneType' object has no attribute 'get'
2024-10-04 16:29:17 'NoneType' object has no attribute 'get'
2024-10-04 16:29:17 Traceback (most recent call last):
2024-10-04 16:29:17   File "/opt/venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 233, in on_chain_start
2024-10-04 16:29:17     "name": self.get_langchain_run_name(serialized, **kwargs),
2024-10-04 16:29:17             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-04 16:29:17   File "/opt/venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 162, in get_langchain_run_name
2024-10-04 16:29:17     return serialized.get("name", serialized.get("id", ["<unknown>"])[-1])
2024-10-04 16:29:17            ^^^^^^^^^^^^^^
2024-10-04 16:29:17 AttributeError: 'NoneType' object has no attribute 'get'
2024-10-04 16:29:17 run not found
2024-10-04 16:29:17 Traceback (most recent call last):
2024-10-04 16:29:17   File "/opt/venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 430, in on_chain_end
2024-10-04 16:29:17     raise Exception("run not found")
2024-10-04 16:29:17 Exception: run not found
  

### Are you interested to contribute a fix for this bug?

Yes

**Comment by hassiebp** [comment]
Related issue: https://github.com/langchain-ai/langchain/issues/26773

Langchain made `serialized` argument optional [in this PR](https://github.com/langchain-ai/langchain/pull/26270).

**Comment by elonakoromani** [comment]
> Related issue: [langchain-ai/langchain#26773](https://github.com/langchain-ai/langchain/issues/26773)
> 
> Langchain made `serialized` argument optional [in this PR](https://github.com/langchain-ai/langchain/pull/26270).
> 
> We will have to handle the `serialized is None` case gracefully going forward

So it means it should be solved in the later versions?

**Comment by hassiebp** [comment]
Yes, this is to be fixed on our (Langfuse) side. It's on the todo.

**Comment by LeonKalt** [comment]
@hassiebp can you give an ETA on that?

**Comment by SebastianThomas1** [comment]
I made a [pull request](https://github.com/langfuse/langfuse-python/pull/1033) to fix this issue.

**Comment by hassiebp** [comment]
Closing this as already fixed on latest SDK version
