### ISSUE TITLE
bug(sdk-js): Log error raised when auth_check() fails in langfuse_context

### ISSUE THREAD

**Issue by ahau-square** [langfuse/langfuse#3689]
### Describe the bug

The langfuse_context's auth_check() will raise an uncaught logger error and print the stack trace if the auth_check fails. This is due to improper string formatting in the log [here](https://github.com/langfuse/langfuse-python/blob/7adec675a51f84747ff9c6dd389a4881276d111e/langfuse/decorators/langfuse_decorator.py#L1113).

Updating that line to the following should fix the issue:
`self._log.error("No Langfuse object found in the current context %s", e)`

### To reproduce

The following will reproduce the log error if the auth fails (it cannot find a langfuse object in the current context).

```
from langfuse.decorators import langfuse_context
langfuse_context.auth_check()
```

### SDK and container versions

langfuse>=2.38.2

### Additional information

Example logging error:

```
--- Logging error ---
Traceback (most recent call last):
  File "/Users/ahau/Development/goose/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 1111, in auth_check
    return self.client_instance.auth_check()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahau/Development/goose/.venv/lib/python3.12/site-packages/langfuse/client.py", line 407, in auth_check
    raise e
  File "/Users/ahau/Development/goose/.venv/lib/python3.12/site-packages/langfuse/client.py", line 395, in auth_check
    projects = self.client.projects.get()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahau/Development/goose/.venv/lib/python3.12/site-packages/langfuse/api/resources/projects/client.py", line 58, in get
    raise UnauthorizedError(pydantic_v1.parse_obj_as(typing.Any, _response.json()))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langfuse.api.resources.commons.errors.unauthorized_error.UnauthorizedError: status_code: 401, body: {'message': 'No authorization header'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/Users/ahau/.cursor/extensions/ms-python.debugpy-2024.6.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/ahau/.cursor/extensions/ms-python.debugpy-2024.6.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/ahau/.cursor/extensions/ms-python.debugpy-2024.6.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/ahau/.cursor/extensions/ms-python.debugpy-2024.6.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/ahau/.cursor/extensions/ms-python.debugpy-2024.6.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/ahau/.cursor/extensions/ms-python.debugpy-2024.6.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/ahau/Development/goose/src/goose/cli/main.py", line 10, in <module>
    from goose.cli.config import SESSIONS_PATH
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/ahau/Development/goose/src/goose/cli/config.py", line 9, in <module>
    from exchange.providers.ollama import OLLAMA_MODEL
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/ahau/Development/goose/packages/exchange/src/exchange/__init__.py", line 6, in <module>
    from exchange.exchange import Exchange  # noqa
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/ahau/Development/goose/packages/exchange/src/exchange/exchange.py", line 14, in <module>
    from exchange.providers import Provider, Usage
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/ahau/Development/goose/packages/exchange/src/exchange/providers/__init__.py", line 5, in <module>
    from exchange.providers.anthropic import AnthropicProvider  # noqa
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/ahau/Development/goose/packages/exchange/src/exchange/providers/anthropic.py", line 11, in <module>
    from langfuse_wrapper.langfuse_wrapper import observe_wrapper
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/ahau/Development/goose/packages/langfuse-wrapper/src/langfuse_wrapper/__init__.py", line 1, in <module>
    from langfuse_wrapper.langfuse_wrapper import observe_wrapper  # noqa
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/ahau/Development/goose/packages/langfuse-wrapper/src/langfuse_wrapper/langfuse_wrapper.py", line 55, in <module>
    if langfuse_context.auth_check():
  File "/Users/ahau/Development/goose/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 1113, in auth_check
    self._log.error("No Langfuse object found in the current context", e)
Message: 'No Langfuse object found in the current context'
```

### Are you interested to contribute a fix for this bug?

Yes

**Comment by marcklingen** [comment]
thank you for raising this!

**Comment by hassiebp** [comment]
Thanks a lot for your report @ahau-square - I've linked a PR that fixes this, to be merged and released soon.
