### ISSUE TITLE
bug: serializer.py stuck in an infinite loop

### ISSUE THREAD

**Issue by cjaschko** [langfuse/langfuse#3823]
### Describe the bug

Langfuse is not usable anymore because the application gets stuck in an infinite loop inside the def default() of serializer.py after I implemented langgraph into my langchain application.

**This is the implementation of langfuse:**
```
        if langfuse_enable:
            callbacksHandlers.append(
                CallbackHandler(
                    secret_key=os.getenv("LANGFUSE_SECRET_KEY"),
                    public_key=os.getenv("LANGFUSE_PUBLIC_KEY"),
                    host=os.getenv("LANGFUSE_HOST"),
                )
            )
        callbacksHandlers.extend(callbacks)

        config = RunnableConfig(callbacks=callbacksHandlers)

        msgs = get_history_messages(history)
        msgs.append(HumanMessage(content=question))

        tools_for_user = self.get_tools_of_user(user)

        output = await self.graph.ainvoke(
            {
                "messages": msgs,
                "user": user,
                "avalible_tools": tools_for_user,
                "statistics": {},
            },
            config=config,)
```

**The log output looks looks like the following:**
`2024-10-18 13:17:35,978 | WARNING  | langfuse.serializer | Serialization failed for object of type dict
Traceback (most recent call last):
  File "D:\DATA\Develop\python\venv311a\pypoetry\Cache\virtualenvs\wibo-agent-RkHoTGmH-py3.11\Lib\site-packages\langfuse\serializer.py", line 100, in default  
    return {self.default(k): self.default(v) for k, v in obj.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\Develop\python\venv311a\pypoetry\Cache\virtualenvs\wibo-agent-RkHoTGmH-py3.11\Lib\site-packages\langfuse\serializer.py", line 100, in <dictcomp>
    return {self.default(k): self.default(v) for k, v in obj.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'
2024-10-18 13:17:35,978 | WARNING  | langfuse.serializer | Serialization failed for object of type dict
Traceback (most recent call last):
  File "D:\DATA\Develop\python\venv311a\pypoetry\Cache\virtualenvs\wibo-agent-RkHoTGmH-py3.11\Lib\site-packages\langfuse\serializer.py", line 100, in default  
    return {self.default(k): self.default(v) for k, v in obj.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\Develop\python\venv311a\pypoetry\Cache\virtualenvs\wibo-agent-RkHoTGmH-py3.11\Lib\site-packages\langfuse\serializer.py", line 100, in <dictcomp>
    return {self.default(k): self.default(v) for k, v in obj.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
2024-10-18 13:17:35,986 | WARNING  | langfuse.serializer | Serialization failed for object of type bytes
Traceback (most recent call last):
  File "D:\DATA\Develop\python\venv311a\pypoetry\Cache\virtualenvs\wibo-agent-RkHoTGmH-py3.11\Lib\site-packages\langfuse\serializer.py", line 69, in default   
    return obj.decode("utf-8")
           ^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte
2024-10-18 13:17:35,986 | WARNING  | langfuse.serializer | Serialization failed for object of type bytes
Traceback (most recent call last):
  File "D:\DATA\Develop\python\venv311a\pypoetry\Cache\virtualenvs\wibo-agent-RkHoTGmH-py3.11\Lib\site-packages\langfuse\serializer.py", line 69, in default   
    return obj.decode("utf-8")
           ^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte`

**Following libs are used:**
- langchain = "^0.3.2"
- langchain-community = "^0.3.1"
- langchain-core = "^0.3.9"
- langchain-openai = "^0.2.2"
- langchain-experimental = "^0.3.2"
- langgraph = "^0.2.35"
- langfuse = "^2.52.1"

### To reproduce

Invoke graph like this:
```
        output = await self.graph.ainvoke(
            {
                "messages": msgs,
                "user": user,
                "avalible_tools": tools_for_user,
                "statistics": {},
            },
            config=config,)

```
and following lib versions:

- langchain = "^0.3.2"
- langchain-community = "^0.3.1"
- langchain-core = "^0.3.9"
- langchain-openai = "^0.2.2"
- langchain-experimental = "^0.3.2"
- langgraph = "^0.2.35"
- langfuse = "^2.52.1"

### Are you interested to contribute a fix for this bug?

Yes

**Comment by hassiebp** [comment]
@cjaschko Thanks for raising this!

- How did you detect an infinite loop? Is your console spammed with the above logs and you are forced to kill the process?
- Could you please share a minimum repro example of your graph? Somewhere in your trace the Langfuse SDK tries to decode a byte stream that is failing.

**Comment by hassiebp** [comment]
Closing this as stale. Please reopen if issue persists.

**Comment by orkhanImmerse** [comment]
This currently happens in our project (django based) with `langfuse==2.60.6`.
When debug is off, it just hangs the thread processing the requests.
When debug is on, we can see infinite spamming of logs with following
```
TypeError: unhashable type: 'list'
langfuse.serializer DEBUG    156 Serialization failed for object of type dict
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/langfuse/serializer.py", line 124, in default
    return {self.default(k): self.default(v) for k, v in obj.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langfuse/serializer.py", line 124, in <dictcomp>
    return {self.default(k): self.default(v) for k, v in obj.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'
langfuse.serializer DEBUG    156 Serialization failed for object of type dict
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/langfuse/serializer.py", line 124, in default
    return {self.default(k): self.default(v) for k, v in obj.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langfuse/serializer.py", line 124, in <dictcomp>
    return {self.default(k): self.default(v) for k, v in obj.items()}
```

If I don't kill the process, it never stops.

What does this decorator try to capture from a function that can throw the serializer off? Documentation is not clear about pre-requisites.
