### ISSUE TITLE
feat(auth): add HTTP proxy support to SSO

### ISSUE THREAD

**Issue by schnaker85** [langfuse/langfuse#3911]
### Describe the bug

We did setup SSO via Azure AD according to the docs and when we try to sign in we get "_OAuthSignin
Contact support if this error is unexpected._" on the Frontend.

In the logs it is shown that the outgoing request timed out after 3500ms.

We are behind a corporate proxy and tried to workaround setting various ENV Variables like `HTTP_PROXY`, `HTTPS_PROXY`, etc. but none of them worked.

While checking the langfuse code and next-auth.js documentation, we noticed that a general http proxy is not supported.

The following log is shown in the container after an unsuccessful login try:
```
https://next-auth.js.org/errors#signin_oauth_error outgoing request timed out after 3500ms {
  error: {
    message: 'outgoing request timed out after 3500ms',
    stack: 'RPError: outgoing request timed out after 3500ms\n' +
      '    at /app/node_modules/.pnpm/openid-client@5.6.5/node_modules/openid-client/lib/helpers/request.js:140:13\n' +
      '    at async Issuer.discover (/app/node_modules/.pnpm/openid-client@5.6.5/node_modules/openid-client/lib/issuer.js:143:22)\n' +
      '    at async openidClient (/app/node_modules/.pnpm/next-auth@4.24.7_next@14.2.15_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1._j3kmigq4faznbmd7ojo532qnmm/node_modules/next-auth/core/lib/oauth/client.js:16:14)\n' +
      '    at async getAuthorizationUrl (/app/node_modules/.pnpm/next-auth@4.24.7_next@14.2.15_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1._j3kmigq4faznbmd7ojo532qnmm/node_modules/next-auth/core/lib/oauth/authorization-url.js:70:18)\n' +
      '    at async Object.signin (/app/node_modules/.pnpm/next-auth@4.24.7_next@14.2.15_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1._j3kmigq4faznbmd7ojo532qnmm/node_modules/next-auth/core/routes/signin.js:38:24)\n' +
      '    at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.24.7_next@14.2.15_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1._j3kmigq4faznbmd7ojo532qnmm/node_modules/next-auth/core/index.js:260:26)\n' +
      '    at async NextAuthApiHandler (/app/node_modules/.pnpm/next-auth@4.24.7_next@14.2.15_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1._j3kmigq4faznbmd7ojo532qnmm/node_modules/next-auth/next/index.js:22:19)\n' +
      '    at async p (/app/web/.next/server/pages/api/auth/[...nextauth].js:1:3969)\n' +
      '    at async /app/node_modules/.pnpm/@sentry+nextjs@8.33.1_@opentelemetry+api@1.9.0_@opentelemetry+core@1.26.0_@opentelemetry+api@_7w2pabnqpritttg6xtpr2rix5i/node_modules/@sentry/nextjs/build/cjs/common/wrapApiHandlerWithSentry.js:90:43\n' +
      '    at async K (/app/node_modules/.pnpm/next@14.2.15_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1.47.2_babel-plugin_kbpuz46h3a5badhs6fmvawrksq/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16881)',
    name: 'RPError'
  },
  providerId: 'azure-ad',
  message: 'outgoing request timed out after 3500ms'
}
```

### To reproduce

Setup SSO via azure AD behind a  http proxy and try to login.

### SDK and container versions

K8s Deployment on GCP via official langfuse/langfuse:2 image and using official helm chart 0.4

### Additional information

To incorporate the proxy in the auth mechanism it should be straight forward and is described at the next-auth.js docs.

https://next-auth.js.org/tutorials/corporate-proxy#title-add-support-for-http-proxy

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Thanks for sharing this!

We are open for contributions on this, as this is not yet supported (as per documentation). I changed the issue from bug to feat to reflect this.

**Comment by marcklingen** [comment]
Aside: we do offer support for custom sso setups, more on this here: [https://langfuse.com/docs/deployment/self-host#troubleshooting](https://langfuse.com/docs/deployment/self-host#troubleshooting)

**Comment by Kratemis** [comment]
Same issue here

**Comment by marcklingen** [comment]
I tried adding httpOptions to the options of an authentication provider, as this may have changed since the post mentioned above was originally published.

Can someone test this in their own environment whether this works?

PR: #4780
Current RC (image is available in 1.5h): v3.3.0-rc.2

**Comment by marcklingen** [comment]
Has someone tried this yet? Would love to know if this helps in these scenarios

**Comment by schnaker85** [comment]
hi @marcklingen,
thanks for the update/fix.
Unfortunately, I can no longer try this fix as we switched to Keycloak Auth instead of Azure-AD SSO.

cheers
dani

**Comment by marcklingen** [comment]
ok, thanks for the update. If there's anyone else who is interested in this, please let me know if this works for you!

Does Keycloak work as expected for you @schnaker85

**Comment by schnaker85** [comment]
yes, it works as expected. See https://github.com/langfuse/langfuse/pull/2866#issuecomment-2519791933

**Comment by marcklingen** [comment]
Sounds good, closing this issue as no one can test implementations right now. Please comment on this issue if you would like this capability and are willing to test a new prerelease.

**Comment by victor-at-square** [comment]
@marcklingen -- I would love to chat more about this. We're also having a hard time configuring SSO (Okta) -- and it looks like it's a proxy issue (i.e. we can reach our IdP from the container, but the Langfuse server itself doesn't seem to be hitting the proxy at all).

**Comment by marcklingen** [comment]
Can you try whether this works on v3.3.0-rc.2 for you? I could publish a new pre-release but just for testing whether this implementation works it should be fine

**Comment by marcklingen** [comment]
reopening this issue as there is interest by @victor-at-square and another team that just emailed me

**Comment by marcklingen** [comment]
rephrasing title to also include non-Azure IDPs

**Comment by victor-at-square** [comment]
> reopening this issue as there is interest by @victor-at-square and another team that just emailed me

Thanks! We would love to get HTTP / HTTPS proxy for SSO in v2 (started a PR [here](https://github.com/langfuse/langfuse/pull/5082)) -- if possible. In the long run we would like to migrate to v3 from v2, but given vendor / security requirements and the added infrastructure complexity of v3, this may take months.

**Comment by marcklingen** [comment]
@Steffen911 will give this a stab, the current implementation will most likely not work as I got negative feedback on it privately. We will update this thread once this is available.

**Comment by Steffen911** [comment]
Change is part of https://github.com/langfuse/langfuse/releases/tag/v2.94.0 as well.

**Comment by express-41** [comment]
@marcklingen https://treacherylex.github.io/integral5/

**Comment by Steffen911** [comment]
@express-41 Could you add more context to your comment?
