### ISSUE TITLE
bug: Multiple Traces LlamaIndex Integratin

### ISSUE THREAD

**Issue by anantgupta129** [langfuse/langfuse#3922]
### Describe the bug

![image](https://github.com/user-attachments/assets/3320fc08-3563-422a-8091-e846782a72aa)

### To reproduce

```python

langfuse_callback_handler = LlamaIndexCallbackHandler(host="https://us.cloud.langfuse.com")

def init_langfuse(tags: str | list, email: str | None = None, **kwargs):
    tags = tags if isinstance(tags, list) else [tags]
    tags.append(LANGFUSE_TAG)
    langfuse_callback_handler.set_trace_params(user_id=email, tags=tags, **kwargs)
    Settings.callback_manager = CallbackManager([langfuse_callback_handler])

credential = AzureKeyCredential(env.SEARCH_SERVICE_API_KEY)
search_client = SearchClient(
    endpoint=env.SEARCH_SERVICE_ENDPOINT, index_name=env.INDEX_NAME, credential=credential
)

vector_store = AzureAISearchVectorStore(
    search_or_index_client=search_client,
    index_management=IndexManagement.VALIDATE_INDEX,
    filterable_metadata_field_keys=metadata_fields,
    id_field_key="id",
    chunk_field_key="chunk",
    embedding_field_key="embedding",
    embedding_dimensionality=3072,
    metadata_string_field_key="metadata",
    doc_id_field_key="doc_id",
)


def get_chat_engine(user_role: str = "lo") -> "CondensePlusContextChatEngine":
    Settings.llm = OpenAI(
        model="gpt-4o-2024-08-06",
        api_key=env.OPENAI_API_KEY,
        temperature=0.1,
    )
    filters = MetadataFilters(
        filters=[
            ExactMatchFilter(key="role", value="common"),
            ExactMatchFilter(key="role", value=user_role),
        ],
        condition=FilterCondition.OR,
    )
    index = VectorStoreIndex.from_vector_store(vector_store=vector_store)
    # using azure ai search (Vector + text + Semantic Ranker)
    _retrievers = [
        index.as_retriever(
            similarity_top_k=3,
            vector_store_query_mode=VectorStoreQueryMode.SEMANTIC_HYBRID,
            filters=filters,
        )
    ]
    # output of original query & HyDE are Reranked with Reciprocal Rank
    retriever = QueryFusionRetriever(
        _retrievers,
        num_queries=2,
        similarity_top_k=3,
        mode=FUSION_MODES.RECIPROCAL_RANK,
        use_async=False,
        verbose=True,
        query_gen_prompt=HYDE_PROMPT_TMPL,
    )
    chat_engine = CondensePlusContextChatEngine.from_defaults(
        retriever=retriever, system_prompt=SUPPORT_BOT_SYSTEM_PROMPT, streaming=True
    )
    return chat_engine
```

### Are you interested to contribute a fix for this bug?

No

**Comment by anantgupta129** [comment]
![image](https://github.com/user-attachments/assets/bfd84b78-2ca7-42d9-928a-235dcd8d8b18)

**Comment by hassiebp** [comment]
Hi @anantgupta129 - could you please upgrade to the instrumentor based integration and try again? https://langfuse.com/docs/integrations/llama-index/get-started

**Comment by anantgupta129** [comment]
@hassiebp i tried with instrumentor also 

![image](https://github.com/user-attachments/assets/17ba999d-ce09-412d-bc43-20a4f420bc25)

```shell
Serialization failed for object of type CompletionResponse
Traceback (most recent call last):
  File "/home/payload/miniconda3/envs/flo/lib/python3.12/site-packages/langfuse/serializer.py", line 77, in default
    return obj.model_dump()
           ^^^^^^^^^^^^^^^^
  File "/home/payload/miniconda3/envs/flo/lib/python3.12/site-packages/pydantic/main.py", line 390, in model_dump
    return self.__pydantic_serializer__.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
Serialization failed for object of type CompletionResponse
Traceback (most recent call last):
  File "/home/payload/miniconda3/envs/flo/lib/python3.12/site-packages/langfuse/serializer.py", line 77, in default
    return obj.model_dump()
           ^^^^^^^^^^^^^^^^
  File "/home/payload/miniconda3/envs/flo/lib/python3.12/site-packages/pydantic/main.py", line 390, in model_dump
    return self.__pydantic_serializer__.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
```

reference code snippet 
```python 

instrumentor = LlamaIndexInstrumentor()

def get_chat_engine(user_role: str = "lo") -> "CondensePlusContextChatEngine":
    Settings.llm = OpenAI(
        model="gpt-4o-2024-08-06",
        api_key=env.OPENAI_API_KEY,
        temperature=0.1,
    )
    filters = MetadataFilters(
        filters=[
            ExactMatchFilter(key="role", value="common"),
            ExactMatchFilter(key="role", value=user_role),
        ],
        condition=FilterCondition.OR,
    )
    index = VectorStoreIndex.from_vector_store(vector_store=vector_store)
    # using azure ai search (Vector + text + Semantic Ranker)
    _retrievers = [
        index.as_retriever(
            similarity_top_k=3,
            vector_store_query_mode=VectorStoreQueryMode.SEMANTIC_HYBRID,
            filters=filters,
        )
    ]
    # output of original query & HyDE are Reranked with Reciprocal Rank
    retriever = CustomQueryFusionRetriever(
        _retrievers,
        num_queries=2,
        similarity_top_k=3,
        mode=FUSION_MODES.RECIPROCAL_RANK,
        use_async=False,
        verbose=True,
        query_gen_prompt=HYDE_PROMPT_TMPL,
    )
    chat_engine = CondensePlusContextChatEngine.from_defaults(
        retriever=retriever, system_prompt=SUPPORT_BOT_SYSTEM_PROMPT, streaming=True
    )
    return chat_engine

def stream_generator(
    response: StreamingAgentChatResponse, history: list, timezone: str
) -> Generator[Any, None, None]:
    yield from (
        json.dumps({"type": "content_block", "text": text}) for text in response.response_gen
    )
    langfuse_callback_handler.flush()

    history.append(
        Message(
            role=MessageRole.ASSISTANT,
            content=response.response,
            created_at=get_current_time(timezone),
        )
    )
    history = [h.dict() for h in history]

    yield json.dumps({"type": "message_stop", "history": history})


async def chat(request: ChatRequestBody):
    try:
        history = load_history(
            request.history.copy()[-8:]
        ) 
        request.history.append(
            Message(
                role=MessageRole.USER,
                content=request.message,
                created_at=get_current_time(request.timezone),  # time is shown in UI
            )
        )
        message = request.message + "\n\n"
        message += ("Greet User: " if not history else "Call user by name: ") + request.first_name

        # init_langfuse(tags="support-bot", email=request.email_id)
        # global_handler.set_trace_params(user_id=request.email_id, tags=["support-bot", env.ENVIRONMENT])
        with instrumentor.observe(user_id=request.email_id, tags=["support-bot", env.ENVIRONMENT]):
            engine = get_chat_engine()
            response_stream = engine.stream_chat(message, chat_history=history)
            return StreamingResponse(
                stream_generator(response_stream, request.history, request.timezone),
                media_type="application/x-ndjson",
            )

    except Exception as e:
        traceback.print_exc()
        raise HTTPException(
            status_code=500, detail=f"An error occurred while processing the request. {str(e)}"
        ) from e

```

**Comment by hassiebp** [comment]
Related issue: [https://github.com/langfuse/langfuse/issues/3861](https://github.com/langfuse/langfuse/issues/3861)

Could you please upgrade to v2.53.2 and try again?

**Comment by anantgupta129** [comment]
![image](https://github.com/user-attachments/assets/69cef29c-a729-4547-a1be-92cf1859ac14)

after update to v2.53.2  `TypeError: 'MockValSer'` is solved but there are still multiple traces 

```python
@observe(capture_input=True, capture_output=True)
async def chat(request: ChatRequestBody):
    try:
        history = load_history(
            request.history.copy()[-8:]
        )  # limit chat history to LLM, to reduce tokens
        request.history.append(
            Message(
                role=MessageRole.USER,
                content=request.message,
                created_at=get_current_time(request.timezone),  # time is shown in UI
            )
        )
        message = request.message + "\n\n"
        message += ("Greet User: " if not history else "Call user by name: ") + request.first_name

        # init_langfuse(tags="support-bot", email=request.email_id)
        while instrumentor.observe(user_id=request.email_id, tags=["support-bot", env.ENVIRONMENT]):
    
            engine = get_chat_engine()
            response_stream = engine.stream_chat(message, chat_history=history)
            return StreamingResponse(
                stream_generator(response_stream, request.history, request.timezone),
                media_type="application/x-ndjson",
            )

    except Exception as e:
        traceback.print_exc()
        raise HTTPException(
            status_code=500, detail=f"An error occurred while processing the request. {str(e)}"
        ) from e
```

**Comment by hassiebp** [comment]
Please check our interoperability docs between the langfuse decorator and the LlamaIndex instrumentor. You need to pass the current observation_id and trace_id to the `instrumentor.observe` context manager. 

https://langfuse.com/docs/integrations/llama-index/get-started#interoperability-with-langfuse-sdk

> When using the [Langfuse @observe() decorator](https://langfuse.com/docs/sdk/python/decorators), langfuse_context.get_current_llama_index_handler() you can pass the current trace ID or parent observation ID to the instrumentor.observe() context manager.

```python
from langfuse.decorators import langfuse_context, observe
from langfuse.llama_index import LlamaIndexInstrumentor
from llama_index.core import Document, VectorStoreIndex
 
instrumentor = LlamaIndexInstrumentor()
 
@observe()
def llama_index_fn(question: str):
    # Get current trace ID and observation ID
    current_trace_id = langfuse_context.get_current_trace_id()
    current_observation_id = langfuse_context.get_current_observation_id()
 
    # Set IDs on the instrumentor
    with instrumentor.observe(
        trace_id=current_trace_id,
        parent_observation_id=current_observation_id,
        update_parent=False,  # Do not update the parent observation or trace, default is True
    ):
        # Run application
        index = VectorStoreIndex.from_documents([doc1, doc2])
        response = index.as_query_engine().query(question)
 
        return response
```

**Comment by anantgupta129** [comment]
@hassiebp  still its not working 

```python

def get_chat_engine(user_role: str = "lo") -> "CondensePlusContextChatEngine":
    Settings.llm = OpenAI(
        model="gpt-4o-2024-08-06",
        api_key=env.OPENAI_API_KEY,
        temperature=0.1,
    )
    filters = MetadataFilters(
        filters=[
            ExactMatchFilter(key="role", value="common"),
            ExactMatchFilter(key="role", value=user_role),
        ],
        condition=FilterCondition.OR,
    )
    index = VectorStoreIndex.from_vector_store(vector_store=vector_store)
    # using azure ai search (Vector + text + Semantic Ranker)
    _retrievers = [
        index.as_retriever(
            similarity_top_k=3,
            vector_store_query_mode=VectorStoreQueryMode.SEMANTIC_HYBRID,
            filters=filters,
        )
    ]
    # output of original query & HyDE are Reranked with Reciprocal Rank
    retriever = CustomQueryFusionRetriever(
        _retrievers,
        num_queries=2,
        similarity_top_k=3,
        mode=FUSION_MODES.RECIPROCAL_RANK,
        use_async=False,
        verbose=True,
        query_gen_prompt=HYDE_PROMPT_TMPL,
    )
    chat_engine = CondensePlusContextChatEngine.from_defaults(
        retriever=retriever, system_prompt=SUPPORT_BOT_SYSTEM_PROMPT, streaming=True
    )
    return chat_engine


def stream_generator(
    response: StreamingAgentChatResponse, history: list, timezone: str
) -> Generator[Any, None, None]:
    yield from (
        json.dumps({"type": "content_block", "text": text}) for text in response.response_gen
    )
    langfuse_callback_handler.flush()

    history.append(
        Message(
            role=MessageRole.ASSISTANT,
            content=response.response,
            created_at=get_current_time(timezone),
        )
    )
    history = [h.dict() for h in history]

    sources = {
        env.MLOFLO_DOCS_URL + "-".join(source.metadata["file_name"].split(".")[0].split())
        for source in response.source_nodes
    }
    yield json.dumps({"type": "message_stop", "history": history, "sources": list(sources)})


@router.post("/chat")
@observe(capture_input=False, capture_output=False)
async def chat(request: ChatRequestBody):
    try:
        # Get current trace ID and observation ID
        current_trace_id = langfuse_context.get_current_trace_id()
        current_observation_id = langfuse_context.get_current_observation_id()

        history = load_history(
            request.history.copy()
        ) 
        request.history.append(
            Message(
                role=MessageRole.USER,
                content=request.message,
                created_at=get_current_time(request.timezone),  # time is shown in UI
            )
        )
        message = request.message + "\n\n"
        message += ("Greet User: " if not history else "Call user by name: ") + request.first_name

        # init_langfuse(tags="support-bot", email=request.email_id)
        with instrumentor.observe(
            trace_id=current_trace_id,
            parent_observation_id=current_observation_id,
            update_parent=False,
            user_id=request.email_id,
            tags=["support-bot", request.user_role.value, env.ENVIRONMENT],
        ):
            role = role_map.get(request.user_role, "lo")
            engine = get_chat_engine(role)
            response_stream = engine.stream_chat(message, chat_history=history)
            return StreamingResponse(
                stream_generator(response_stream, request.history, request.timezone),
                media_type="application/x-ndjson",
            )

    except Exception as e:
        traceback.print_exc()
        raise HTTPException(
            status_code=500, detail=f"An error occurred while processing the request. {str(e)}"
        ) from e

```

![image](https://github.com/user-attachments/assets/f9990482-c01c-4555-909a-a573758bb986)

**Comment by hassiebp** [comment]
I'm afraid this is the same issue here where FastAPI StreamingResponse does not work well with Python contextvars. Here is the root issue to track progress on that: https://github.com/langfuse/langfuse/issues/3961

**Comment by hassiebp** [comment]
Closing this as we track progress in the above linked issue
