### ISSUE TITLE
bug: broken "datasets" api in the latest version 2.91.0 (self-hosted)

### ISSUE THREAD

**Issue by ichina** [langfuse/langfuse#4357]
### Describe the bug

i'm receiving 500 on `GET https://langfuse.custom.domain/api/trpc/datasets.itemsByDatasetId?...` in the datasets dashboard.
downgrading to previous version 2.90.1 fixes the problem. 
response:
```
{
    "error": {
        "json": {
            "message": "Internal error",
            "code": -32603,
            "data": {
                "code": "INTERNAL_SERVER_ERROR",
                "httpStatus": 500,
                "path": "datasets.itemsByDatasetId",
                "zodError": null
            }
        }
    }
}
```
<img width="492" alt="Screenshot 2024-11-21 at 6 34 51 PM" src="https://github.com/user-attachments/assets/edbb4aa0-edb9-46e8-a956-55bb2bf5aa5f">

### To reproduce

upgrade docker image to 2.91.0 and open the page with items of any datasets

### SDK and container versions

container image 2.91.0

### Additional information

in the container logs i see attempts to connect to clickhouse db, but we use only postgres yet
```

2024-11-21T07:52:25.409Z error middleware intercepted error with code INTERNAL_SERVER_ERROR connect ECONNREFUSED 127.0.0.1:8123
2024-11-21T07:52:25.409Z error tRPC route failed on datasets.itemsByDatasetId: Internal error Internal error 
```

### Are you interested to contribute a fix for this bug?

No

**Comment by ichina** [comment]
just fyi, specifying `LANGFUSE_READ_FROM_POSTGRES_ONLY=true` didn't help

**Comment by mainka** [comment]
Same behaviour here with 2.91.0:

```
│ 2024-11-21T11:32:31.615Z error     middleware intercepted error with code INTERNAL_SERVER_ERROR                                                   │
│ AggregateError [ECONNREFUSED]:                                                                                                                    │
│     at internalConnectMultiple (node:net:1118:18)                                                                                                 │
│     at afterConnectMultiple (node:net:1685:7)                                                                                                     │
│     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)                                                                       │
│ 2024-11-21T11:32:31.615Z error     tRPC route failed on datasets.itemsByDatasetId: Internal error Internal error                                  │
│ TRPCError: Internal error                                                                                                                         │
│     at /app/web/.next/server/pages/api/trpc/[trpc].js:689:6727                                                                                    │
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                 │
│     at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)                  │
│     at async file:///app/node_modules/.pnpm/@baselime+trpc-opentelemetry-middleware@0.1.2_@opentelemetry+api@1.9.0_@trpc+server@10.45.2/node_modu │
│     at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)                  │
│     at async resolve (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:481:24)                        │
│     at async inputToProcedureCall (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/resolveHTTPResponse-2fc435b │
│     at async Promise.all (index 0)                                                                                                                │
│     at async resolveHTTPResponse (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/resolveHTTPResponse-2fc435bb │
│     at async file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/nodeHTTPRequestHandler-97af83bc.mjs:67:9          │
```

**Comment by skabbit** [comment]
Experiencing exactly similar error:
```
2024-11-21T13:14:37.454Z error  middleware intercepted error with code INTERNAL_SERVER_ERROR connect ECONNREFUSED 127.0.0.1:8123
Error: connect ECONNREFUSED 127.0.0.1:8123
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
2024-11-21T13:14:37.454Z error  tRPC route failed on datasets.itemsByDatasetId: Internal error Internal error
TRPCError: Internal error
    at /app/web/.next/server/pages/api/trpc/[trpc].js:689:6727
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
    at async file:///app/node_modules/.pnpm/@baselime+trpc-opentelemetry-middleware@0.1.2_@opentelemetry+api@1.9.0_@trpc+server@10.45.2/node_modules/@baselime/trpc-opentelemetry-middleware/dist/index.js:43:22
    at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
    at async resolve (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:481:24)
    at async inputToProcedureCall (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/resolveHTTPResponse-2fc435bb.mjs:46:22)
    at async Promise.all (index 0)
    at async resolveHTTPResponse (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/resolveHTTPResponse-2fc435bb.mjs:182:37)
    at async file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/nodeHTTPRequestHandler-97af83bc.mjs:67:9
```

Langfuse v2.91.0 OSS
PostgreSQL 16.3 (Debian 16.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

Whole setup is running inside Docker containers, using public images: `langfuse/langfuse:2` and `pgvector/pgvector:pg16`

**Comment by maxdeichmann** [comment]
@ichina thanks for raising this. We are working on a fix right now.

**Comment by maxdeichmann** [comment]
Here is the fix: https://github.com/langfuse/langfuse/pull/4366
