### ISSUE TITLE
bug (sdk-python): Datasets not found in latest python SDK when name includes special characters

### ISSUE THREAD

**Issue by jscastanoc** [langfuse/langfuse#4404]
### Describe the bug

Datasets are accessible with client.get_dataset("NAME") if using `version 2.36.2`, but if we upgrade to `2.54.1`, we get the exception:

`langfuse.api.resources.commons.errors.not_found_error.NotFoundError: status_code: 404, body: {'message': 'Dataset not found', 'error': 'LangfuseNotFoundError'}`

### To reproduce

Try to get a dataset that was working with version 2.36.2, using version 2.54.1

### SDK and container versions

SDK 2.54.1, Dataset hosted in langfuse (no self-hosted)

### Are you interested to contribute a fix for this bug?

Yes

**Comment by jscastanoc** [comment]
@marcklingen thank you for the fast reply!

Yes, I am able to retrieve prompts, for example, so the connection works. The only difference between but runs is the sdk version. I did not change anything else and I mentioned, the client works for retrieving other assets.

**Comment by marcklingen** [comment]
I've just tried this again and cannot reproduce this, can we have a quick look together into this?<br>https://cal.com/marc-kl/5

**Comment by hassiebp** [comment]
@jscastanoc What is the exception raised when `get_dataset` is failing for you? I cannot reproduce the issue on the latest SDK version 🤔

**Comment by marekkucak** [comment]
Hi,

I get the same error. At first when I was trying to load the dataset for experiment. Then it started to happen also when I tried to create a new one (my impression was that naming was off so I wanted to create a new dataset without breaks in the name)


When I try to load the dataset I get this error:
Langfuse auth check response: True
Langfuse auth check response: True
Internal error occurred. This is an unusual occurrence and we are monitoring it closely. For help, please contact support: https://langfuse.com/support.
Traceback (most recent call last):
  File "/mnt/c/Repos/sql_chatbot_chinook/model_evaluation.py", line 150, in <module>
    run_experiment(experiment_name, dataset_name)
  File "/mnt/c/Repos/sql_chatbot_chinook/model_evaluation.py", line 113, in run_experiment
    dataset = langfuse.get_dataset(dataset_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Repos/sql_chatbot_chinook/.venv/lib/python3.12/site-packages/langfuse/client.py", line 378, in get_dataset
    raise e
  File "/mnt/c/Repos/sql_chatbot_chinook/.venv/lib/python3.12/site-packages/langfuse/client.py", line 363, in get_dataset
    new_items = self.client.dataset_items.list(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Repos/sql_chatbot_chinook/.venv/lib/python3.12/site-packages/langfuse/api/resources/dataset_items/client.py", line 222, in list
    raise NotFoundError(pydantic_v1.parse_obj_as(typing.Any, _response.json()))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langfuse.api.resources.commons.errors.not_found_error.NotFoundError: status_code: 404, body: {'message': 'Dataset not found', 'error': 'LangfuseNotFoundError'}

(.venv) marek@SHS7580953C:/mnt/c/Repos/sql_chatbot_chinook$ python [populate_dataset_from_csv.py](http://populate_dataset_from_csv.py/) 
Failed to decode with utf-8
Internal error occurred. This is an unusual occurrence and we are monitoring it closely. For help, please contact support: https://langfuse.com/support.
An error occurred: status_code: 404, body: {'message': 'Dataset not found', 'error': 'LangfuseNotFoundError'}
Traceback (most recent call last):
  File "/mnt/c/Repos/sql_chatbot_chinook/populate_dataset_from_csv.py", line 44, in <module>
    populate_langfuse_dataset(csv_file_path)
  File "/mnt/c/Repos/sql_chatbot_chinook/populate_dataset_from_csv.py", line 22, in populate_langfuse_dataset
    langfuse.create_dataset_item(
  File "/mnt/c/Repos/sql_chatbot_chinook/.venv/lib/python3.12/site-packages/langfuse/client.py", line 550, in create_dataset_item
    raise e
  File "/mnt/c/Repos/sql_chatbot_chinook/.venv/lib/python3.12/site-packages/langfuse/client.py", line 547, in create_dataset_item
    return self.client.dataset_items.create(request=body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Repos/sql_chatbot_chinook/.venv/lib/python3.12/site-packages/langfuse/api/resources/dataset_items/client.py", line 86, in create
    raise NotFoundError(pydantic_v1.parse_obj_as(typing.Any, _response.json()))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langfuse.api.resources.commons.errors.not_found_error.NotFoundError: status_code: 404, body: {'message': 'Dataset not found', 'error': 'LangfuseNotFoundError'}

**Comment by hassiebp** [comment]
This might be related to the fetching of dataset items that belong to a dataset with special chars. To be investigated further.

**Comment by hassiebp** [comment]
Closing this as not reproducible. Please create a new issue if you experience this issue again.

**Comment by mattverantos** [comment]
Created a new bug here: https://github.com/langfuse/langfuse/issues/6832
