### ISSUE TITLE
bug: AzureOpenAI chat completion streaming raises AttributeError in _extract_streamed_openai_response

### ISSUE THREAD

**Issue by j4yh3m** [langfuse/langfuse#4432]
### Describe the bug

When running a Python script using Langfuse with the AzureOpenAI client, a trace is successfully uploaded to LangFuse, but at the end, an AttributeError is raised in the _extract_streamed_openai_response function. The error occurs because the delta object is None, and the code attempts to access its __dict__ attribute.

The same script does not raise any exceptions with OpenAI, it only does with AzureOpenAI.

### To reproduce

Create a `.env` file with the required env variables.

Used `AZURE_OPENAI_API_VERSION="2024-10-01-preview"` but the previous versions show the same behaviour.

Run the following script, tried with both Python 3.11 and 3.12

```python
import os
from dotenv import load_dotenv
from langfuse.openai import AzureOpenAI

def create_azure_openai_client() -> AzureOpenAI:
    load_dotenv()
    return AzureOpenAI(
        api_key=os.getenv("AZURE_OPENAI_API_KEY"),
        azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
        api_version=os.getenv("AZURE_OPENAI_API_VERSION"),
    )

def stream_test():
    client = create_azure_openai_client()
    stream = client.chat.completions.create(
        model=os.getenv("AZURE_GPT_4O_MINI"),
        messages=[{"role": "user", "content": "Say this is a test"}],
        stream=True,
        stream_options={"include_usage": True},
    )
    for chunk in stream:
        if chunk.choices:
            if chunk.choices[0].delta:
                if chunk.choices[0].delta.content is not None:
                    print(chunk.choices[0].delta.content, end="")
    AzureOpenAI.flush_langfuse()
    print()

if __name__ == "__main__":
    stream_test()
```

### SDK and container versions

Langfuse v2.90.1 OSS
langfuse-2.54.0

### Are you interested to contribute a fix for this bug?

Yes

**Comment by j4yh3m** [comment]
@dosu my script already ensures that chunk.choices[0].delta is not None

**Comment by j4yh3m** [comment]
I've already ruled out the `stream_options` setting, the behaviour is the same with or without it.

The error is triggered from the line `for chunk in stream:`, which causes langfuse to iterate over the stream without checking if delta is None.

The full trace is below:
```
$ uv run minimal-streaming.py                                         
This is a test. How can I assist you today?
Traceback (most recent call last):                                                                                          
  File "/home/jkuffer/dev/myrepos/bdp/genai-samples/packages/examples-basic/examples-basic/minimal-streaming.py", line 42, in <module>                                 
    stream_test()                                                                                                                                                      
  File "/home/jkuffer/dev/myrepos/bdp/genai-samples/packages/examples-basic/examples-basic/minimal-streaming.py", line 31, in stream_test                              
    for chunk in stream:                                                                                                                                               
  File "/home/jkuffer/dev/myrepos/bdp/genai-samples/.venv/lib/python3.11/site-packages/langfuse/openai.py", line 825, in __iter__                                      
    self._finalize()                                                                                                                                                   
  File "/home/jkuffer/dev/myrepos/bdp/genai-samples/.venv/lib/python3.11/site-packages/langfuse/openai.py", line 849, in _finalize                                     
    model, completion, usage = _extract_streamed_openai_response(                                                                                                      
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                        File "/home/jkuffer/dev/myrepos/bdp/genai-samples/.venv/lib/python3.11/site-packages/langfuse/openai.py", line 471, in _extract_streamed_openai_response             
    delta = delta.__dict__                                                                                                                                             
            ^^^^^^^^^^^^^^                                                                                                                                             
AttributeError: 'NoneType' object has no attribute '__dict__'. Did you mean: '__dir__'?
```

**Comment by hassiebp** [comment]
Hi @j4yh3m - thanks for raising this! Unfortunately I cannot reproduce this error on the latest Langfuse SDK and openai 1.54.3. Could you please upgrade and try again?

**Comment by hassiebp** [comment]
Closing this as stale.
