### ISSUE TITLE
bug: middleware intercepted error with code INTERNAL_SERVER_ERROR 

### ISSUE THREAD

**Issue by talrejanikhil** [langfuse/langfuse#4435]
### Describe the bug

I see this error in our logs after every request. We are using a self-hosted version of langfuse

### To reproduce

Login to langtrace and perform any operation

### SDK and container versions

docker container - ver 2

### Additional information

```
2024-11-26T13:11:37.756Z error  middleware intercepted error with code INTERNAL_SERVER_ERROR [
  {
    "validation": "regex",
    "code": "invalid_string",
    "message": "Invalid",
    "path": []
  }
]
ZodError: [
  {
    "validation": "regex",
    "code": "invalid_string",
    "message": "Invalid",
    "path": []
  }
]
    at get error [as error] (file:///app/node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/index.mjs:587:31)
    at ZodString.parse (file:///app/node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/index.mjs:692:22)
    at l (/app/web/.next/server/pages/api/trpc/[trpc].js:575:4337)
    at /app/web/.next/server/pages/api/trpc/[trpc].js:575:5297
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:421:30)
    at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
    at async /app/web/.next/server/pages/api/trpc/[trpc].js:760:6607
    at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
    at async file:///app/node_modules/.pnpm/@baselime+trpc-opentelemetry-middleware@0.1.2_@opentelemetry+api@1.9.0_@trpc+server@10.45.2/node_modules/@baselime/trpc-opentelemetry-middleware/dist/index.js:43:22
2024-11-26T13:11:37.756Z error  tRPC route failed on public.checkUpdate: Internal error Internal error
TRPCError: Internal error
    at /app/web/.next/server/pages/api/trpc/[trpc].js:760:6727
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
    at async file:///app/node_modules/.pnpm/@baselime+trpc-opentelemetry-middleware@0.1.2_@opentelemetry+api@1.9.0_@trpc+server@10.45.2/node_modules/@baselime/trpc-opentelemetry-middleware/dist/index.js:43:22
    at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
    at async resolve (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:481:24)
    at async inputToProcedureCall (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/resolveHTTPResponse-2fc435bb.mjs:46:22)
    at async Promise.all (index 0)
    at async resolveHTTPResponse (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/resolveHTTPResponse-2fc435bb.mjs:182:37)
    at async file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/nodeHTTPRequestHandler-97af83bc.mjs:67:9
```

### Are you interested to contribute a fix for this bug?

No

**Comment by talrejanikhil** [comment]
I don't know all the actions when this error occurs. But after I login, it always appears

**Comment by talrejanikhil** [comment]
Oh yes thats a good point. My env is inside a private network and cannot access the internet. Is this going to be a problem? Can I disable some features?

**Comment by marcklingen** [comment]
Langfuse works fully air-gapped without access to the internet, except for some additional ui-only commercial features (playground, llm-as-a-judge evals runner).

The issue here was that the function that helps display an indicator when a new version is available failed by printing a stack trace. I've just fixed this in #4436. This issue does not cause any runtime issue except for logs that are not pretty.

**Comment by marcklingen** [comment]
No, they are on main. We just today branched v2, if this is extremely important for you, then we could cherry pick this change for v2, otherwise, this will be fixed as you upgrade to v3

**Comment by marcklingen** [comment]
sure, happy to help. thanks!

**Comment by alex-nogue-sanchez** [comment]
Hi @marcklingen, thank you for the clarity of your answer.
Instead of improving the returned exception, is there a way to turn off this new release check? It may not be harmful if there is no internet connection, but some companies may still be concerned about this. Many thanks!

**Comment by marcklingen** [comment]
Sure, open for contributions on this! Feel free to add a pr that disables this check via an environment variable.

In my point of view this is rather low priority since Internet access is usually blocked at the security policy level of the VPC.
