### ISSUE TITLE
bug: `require is not defined` when loading crypto or fs module

### ISSUE THREAD

**Issue by felixgabler** [langfuse/langfuse#4470]
### Describe the bug

After upgrading from `3.30.3` to `3.31.0`, I started getting the following exception on startup of my Nitro server functions (using Nuxt 3):

```
Error loading crypto or fs module ReferenceError: require is not defined
    at <anonymous> (/Users/my-user-name/my-app-project/node_modules/langfuse-core/src/media/LangfuseMedia.ts:7:5)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:120:12)
```

### To reproduce

Installing the latest version and starting a Nuxt app (that imports it somewhere) should be enough. The error message shows right on startup Langfuse is even initialized by my app.

### SDK and container versions

Using `langfuse` JS SDK version `3.31.0`. If I downgrade back to `3.30.3` (have to override for `langfuse-core`, the exception does not show.

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for sharing! do you import Langfuse (server-side) or LangfuseWeb (client-side)?

**Comment by hey-nicolasklein** [comment]
Same here with Nuxt 3.13.2 and the Langfuse SDK 3.27.2 observing OpenAi SDK on 4.68.2. Every call to Langfuse happening serverside (e.g. Nuxt API-Routes).

Message:
```bash
Error loading crypto or fs module ReferenceError: require is not defined
    at <anonymous> (/Users/nico/development/smd/node_modules/langfuse-core/src/media/LangfuseMedia.ts:7:5)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
```
Printed on every rerun twice.

**Comment by hassiebp** [comment]
@felixgabler @hey-nicolasklein -to gauge the seriousness of this, Is this error message logged only or is this exception crashing your app? I would expect server startup to succeed and events being logged to Langfuse, and only see those logged error message in STDOUT

**Comment by hey-nicolasklein** [comment]
Second that. Does not crash the app and has no further visible impact for tracing and prompt fetching.

( https://nico.so )

Nicolas Klein

UX Engineer

Mobile-App Development

***@***.*** ( ***@***.*** )

Saarland, Germany

nico.so ( https://nico.so/ )

**Comment by brian-xu-vlt** [comment]
Same here when running integration test with the Langfuse client in vitest.
Running `3.31.0`


```
Error loading crypto or fs module ReferenceError: require is not defined
    at file:///Users/code/node_modules/.pnpm/langfuse-core@3.31.0/node_modules/langfuse-core/src/media/LangfuseMedia.ts:7:5
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at VitestExecutor.interopedImport (file:///Users/code/node_modules/.pnpm/vite-node@2.1.6_@types+node@22.10.1_less@4.2.0_lightningcss@1.25.1_sass@1.77.6_terser@5.36.0/node_modules/vite-node/dist/client.mjs:421:28)
    at VitestExecutor.directRequest (file:///Users/code/node_modules/.pnpm/vite-node@2.1.6_@types+node@22.10.1_less@4.2.0_lightningcss@1.25.1_sass@1.77.6_terser@5.36.0/node_modules/vite-node/dist/client.mjs:280:24)
    at VitestExecutor.cachedRequest (file:///Users/code/node_modules/.pnpm/vite-node@2.1.6_@types+node@22.10.1_less@4.2.0_lightningcss@1.25.1_sass@1.77.6_terser@5.36.0/node_modules/vite-node/dist/client.mjs:206:14)
    at VitestExecutor.dependencyRequest (file:///Users/code/node_modules/.pnpm/vite-node@2.1.6_@types+node@22.10.1_less@4.2.0_lightningcss@1.25.1_sass@1.77.6_terser@5.36.0/node_modules/vite-node/dist/client.mjs:259:12)
    at /Users/code/packages/server/src/application/sharedServices/LangfuseClient/makeLangfuseClient.ts:3:31
    at VitestExecutor.runModule (file:///Users/code/node_modules/.pnpm/vite-node@2.1.6_@types+node@22.10.1_less@4.2.0_lightningcss@1.25.1_sass@1.77.6_terser@5.36.0/node_modules/vite-node/dist/client.mjs:399:5)
    at VitestExecutor.directRequest (file:///Users/code/node_modules/.pnpm/vite-node@2.1.6_@types+node@22.10.1_less@4.2.0_lightningcss@1.25.1_sass@1.77.6_terser@5.36.0/node_modules/vite-node/dist/client.mjs:381:5)
```

**Comment by hassiebp** [comment]
Could you please upgrade to 3.31.1 and try again? 🙏🏾

**Comment by hey-nicolasklein** [comment]
3.31.1 fixed it for me 🎉

**Comment by brian-xu-vlt** [comment]
Fixed on my end too! Thanks a lot!

**Comment by marcklingen** [comment]
awesome, closing this now!

**Comment by marcklingen** [comment]
thanks @hassiebp
