### ISSUE TITLE
bug: KeyError 'metadata'

### ISSUE THREAD

**Issue by memben** [langfuse/langfuse#4592]
### Describe the bug

Hey there,

Reviewing our Error Tracking, I've stumbled over a Langfuse + LiteLLM bug
Unfortunately it is one of those bugs, that happen only rarely in production and which I cannot reproduce locally

```
Langfuse Layer Error - Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/litellm/integrations/langfuse/langfuse.py", line 379, in _log_langfuse_v2
    optional_params.pop("metadata")
KeyError: 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/litellm/integrations/langfuse/langfuse.py", line 393, in _log_langfuse_v2
    new_metadata[key] = copy.deepcopy(value)
  File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.10/copy.py", line 230, in _deepcopy_dict
    for key, value in x.items():
RuntimeError: dictionary changed size during iteration
```

### To reproduce

As described earlier happening only rarely - let me know if I you need more information from Sentry

### SDK and container versions

litellm | 1.51.3
langfuse | 2.55.0 + langfuse cloud

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
Hi @memben - this is related to #4594 where there the dict handling by LiteLLM seems to be the root issue (notice the `RuntimeError: dictionary changed size during iteration` message here as well.) Could you please open an issue in the LiteLLM repo with the error traces as the exception occurs in their preprocessing steps?

**Comment by hassiebp** [comment]
Closing this as stale.
