### ISSUE TITLE
bug(llama-index): Bedrock usage not reported correctly

### ISSUE THREAD

**Issue by hassiebp** [langfuse/langfuse#4667]
### Discussed in https://github.com/orgs/langfuse/discussions/4637

We're using AWS Bedrock as a foundation model supplier, and using the BedrockConverse class as LLMs. When doing so, the input and output tokens are incorrectly reported (usually some number apperas as input token count, and 0 as output) even though the API returns usage and the token count is captured there. I'm not sure if this is a langfuse issue or a llama-index upstream issue, but it is definitely an inconvenience at the very least. 
By the way, this is not a problem when using LangChain LLMs with Bedrock, that does report usage correctly in Langfuse.

**Comment by maltehedderich** [comment]
Hi @hassiebp,

we're also using BedrockConverse with LlamaIndex & Langfuse. While there is some usage shown in the langfuse UI `v3.58.0 OSS`, the console logs the following errors:
```
Usage object must have either {input, output, total, unit} or {promptTokens, completionTokens, totalTokens}
Traceback (most recent call last):
  File "/home/<USER>/repos/<REPOSITORY>/.venv/.venv/lib/python3.13/site-packages/langfuse/client.py", line 2728, in update
    "usage": _convert_usage_input(usage) if usage is not None else None,
             ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/home/<USER>/repos/<REPOSITORY>/.venv/lib/python3.13/site-packages/langfuse/utils/__init__.py", line 103, in _convert_usage_input
    raise ValueError(
        "Usage object must have either {input, output, total, unit} or {promptTokens, completionTokens, totalTokens}"
    )
ValueError: Usage object must have either {input, output, total, unit} or {promptTokens, completionTokens, totalTokens}
```

The setup to reproduce is as described here: https://langfuse.com/docs/integrations/llama-index/example-python-instrumentation-module#setup
+
llama-index-core `0.12.34.post1`
llama-index-llms-bedrock-converse `0.5.0`
and Claude 3.5 Sonnet

My local langfuse python SDK version is `2.60.5`.

Cheers,
Malte

**Comment by hassiebp** [comment]
Thanks for letting us know - we will take a look!
