### ISSUE TITLE
bug: Error in Next.js Server Initialization

### ISSUE THREAD

**Issue by spacepirate0001** [langfuse/langfuse#4675]
### Describe the bug

The application fails to initialize due to a TypeError:

```
TypeError: Cannot set property message of [object Object] which has only a getter
    at NextNodeServer.prepareImpl (/app/node_modules/.../next-server.js:476:33)
```
This error occurs repeatedly during the server's `prepareImpl` step.
Application reports:
`Failed to prepare server TypeError.`
 Prisma migrations (273) load successfully, and no pending migrations are found.

### To reproduce

Deploy the container using the ghcr.io/langfuse/langfuse:3.0.0 image with Clockhouse image `clickhouse:24.3.14.35-focal`

### SDK and container versions

Image: ghcr.io/langfuse/langfuse:3.0.0

### Additional information

```
▲ Next.js 14.2.15
✓ Starting...
Running init scripts...
Script executed successfully.
Prisma schema loaded from packages/shared/prisma/schema.prisma
273 migrations found in prisma/migrations
No pending migrations to apply.
```
Error:
```
TypeError: Cannot set property message of [object Object] which has only a getter
   at NextNodeServer.prepareImpl (/app/node_modules/.../next-server.js:476:33)
```
![image](https://github.com/user-attachments/assets/5abfda02-f27b-4185-8b99-17f3c3d644a9)

### Are you interested to contribute a fix for this bug?

No

**Comment by gbben** [comment]
Same issue:
```
Failed to prepare server TypeError: Cannot set property message of [object Object] which has only a getter
    at NextNodeServer.prepareImpl (/app/node_modules/.pnpm/next@14.2.15_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1.47.2_babel-plugin_kbpuz46h3a5badhs6fmvawrksq/node_modules/next/dist/server/next-server.js:476:33)
```

**Comment by elliotvilhelm** [comment]
Same issue here
```
No pending migrations to apply.
no change
  ▲ Next.js 14.2.15
  - Local:        http://80be42553748:3000
  - Network:      http://172.18.0.4:3000

 ✓ Starting...
Running init scripts...
 ✓ Ready in 1510ms
Failed to prepare server TypeError: Cannot set property message of [object Object] which has only a getter
    at NextNodeServer.prepareImpl (/app/node_modules/.pnpm/next@14.2.15_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1.47.2_babel-plugin_kbpuz46h3a5badhs6fmvawrksq/node_modules/next/dist/server/next-server.js:476:33)
```

**Comment by gbben** [comment]
The issue doesn't appear when specifying the docker file as given in the documentation, as given [here](https://github.com/langfuse/langfuse/blob/main/docker-compose.yml):

**Comment by maxdeichmann** [comment]
@gbben can you elaborate what exactly you did to resolve the issue?

**Comment by gbben** [comment]
@maxdeichmann Originally I had written my own compose file with the following services: langfuse (app), Postgres and clickhouse. That kept raising the above `next.js` setter error. All I did was copy the above linked compose file which adds the langfuse worker (plus minIO and Redis). I'm not sure what specifically solved the issue and I didn't investigate further. Reading the docs one of the reason for upgrade the splitting of web service and worker says:
```
When processing observability data for LLM applications, there are many CPU-heavy operations which block the main loop in our Node.js backend, e.g. tokenization and other parsing of event bodies. To achieve high availability and low latencies across client applications, we decided to move the heavy processing into an asynchronous worker container. It accepts events from a Redis queue and ensures that they are eventually being upserted into Clickhouse.
```

I can't imaging this is related to the issue. I had also tried a number of images before which all gave me the same issue. Maybe it was some configuration issue somewhere? Do you have an idea of what could have led to the issue?


Since the change the who stack works very well

**Comment by Steffen911** [comment]
Could be related to https://github.com/vercel/next.js/issues/54417.

**Comment by Rafisto** [comment]
I had the same issue prior to populating S3 `LANGFUSE_S3_EVENT_UPLOAD_*` environment variables in my helm chart `values.yaml` configuration. Afterwards, the worker pod and the web pod started successfully

**Comment by mikebranski** [comment]
I started seeing this with our rather vanilla self-serve setup in AWS (running in ECS, not EKS), even with @Rafisto's suggestion. I finally got it working after adding these three environment variables to our ECS task definition:

- `NEXT_PUBLIC_API_URL=<our-langfuse-web-url>`
- `NEXT_RUNTIME=nodejs`
- `NEXT_SHARP_PATH=/app/node_modules/sharp`

**Comment by maxdeichmann** [comment]
Thanks a lot! We will look into this.

**Comment by Steffen911** [comment]
@mikebranski Could you share the env variables that you had configured before you added those three? Ideally, you'd have some minimal reproduction, e.g. via a task definition that helps me recreate this issue.

**Comment by hemisalo** [comment]
> Failed to prepare server TypeError: Cannot set property message of [object Object] which has only a getter
    at NextNodeServer.prepareImpl (/app/node_modules/.pnpm/next@14.2.15_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1.47.2_babel-plugin_kbpuz46h3a5badhs6fmvawrksq/node_modules/next/dist/server/next-server.js:476:33)

Can confirm that this worked for both web and worker with default values:

> I had the same issue prior to populating S3 `LANGFUSE_S3_EVENT_UPLOAD_*` environment variables in my helm chart `values.yaml` configuration. Afterwards, the worker pod and the web pod started successfully

**Comment by Steffen911** [comment]
@hemisalo Are those all the logs you see in the container or is there anything else? Is it the same error for the web and the worker container?

**Comment by Enescigdem** [comment]
Same issue , when I tried to up langfuse as self-hosted.
  ▲ Next.js 14.2.30
  - Local:        http://address:3000
  - Network:      http://address:3000

 ✓ Starting...
Running init scripts...
 ✓ Ready in 3.5s
Failed to prepare server TypeError: Cannot set property message of ZodError which has only a getter
    at NextNodeServer.prepareImpl (/app/node_modules/.pnpm/next@14.2.30_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1.47.2_babel-plugin_pz5jczsrwmn5olwahiiemkgmoy/node_modules/next/dist/server/next-server.js:481:33)

**Comment by Steffen911** [comment]
@Enescigdem Are you running a docker image that we provide or use your own custom build? Can you confirm that all required environment variables based on our documentation (https://langfuse.com/self-hosting/configuration) are configured?

**Comment by Enescigdem** [comment]
```
DOCKER COMPOSE FILE

services:
  # PostgreSQL for Langfuse metadata
  postgres:
    image: postgres:15
    container_name: langfuse-postgres
    environment:
      POSTGRES_DB: langfuse
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - langfuse-network
    restart: unless-stopped

  # ClickHouse Database - Simplified setup
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: langfuse-clickhouse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    ports:
      - "18123:8123"
      - "19000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - langfuse-network
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: langfuse-redis
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    networks:
      - langfuse-network
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}

 # Langfuse Application (Web UI and API) - Built from source
  langfuse:
    build:
      context: ./langfuse
      dockerfile: ./web/Dockerfile
    container_name: langfuse-app

    ports:
      - "13000:3000"

    environment:
      # Database Configuration
      DATABASE_URL: "postgresql://langfuse:${POSTGRES_PASSWORD}@postgres:5432/langfuse"
      DIRECT_URL: "postgresql://langfuse:${POSTGRES_PASSWORD}@postgres:5432/langfuse"

      # ClickHouse Configuration - Exactly as per Langfuse docs
      CLICKHOUSE_URL: "http://clickhouse:8123"
      CLICKHOUSE_MIGRATION_URL: "clickhouse://clickhouse:9000"
      CLICKHOUSE_USER: "clickhouse"
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD}"
      CLICKHOUSE_DB: "default"
      CLICKHOUSE_CLUSTER_ENABLED: "false"

      # Redis Configuration
      REDIS_URL: "redis://:${REDIS_PASSWORD}@redis:6379"

      # Application Configuration
      NEXTAUTH_URL: "http://localhost:13000"
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
      SALT: "${SALT}"

      # Additional Configuration
      NODE_ENV: "production"
      LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: "false"
      TELEMETRY_ENABLED: "false"

      # Blob Storage (using local file system)
      LANGFUSE_S3_EVENT_UPLOAD_ENABLED: "false"

    volumes:
      - langfuse_data:/app/data
    networks:
      - langfuse-network
    restart: unless-stopped
# Langfuse Worker (Background processing)
  langfuse-worker:
    image: langfuse/langfuse-worker:3
    container_name: langfuse-worker
    environment:
      # Database Configuration
      DATABASE_URL: "postgresql://langfuse:${POSTGRES_PASSWORD}@postgres:5432/langfuse"
      DIRECT_URL: "postgresql://langfuse:${POSTGRES_PASSWORD}@postgres:5432/langfuse"

      # ClickHouse Configuration
      CLICKHOUSE_URL: "http://clickhouse:8123"
      CLICKHOUSE_USER: "clickhouse"
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD}"
      CLICKHOUSE_DATABASE: "default"

      # Redis Configuration
      REDIS_URL: "redis://:${REDIS_PASSWORD}@redis:6379"

      # Required Auth Configuration
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
      SALT: "${SALT}"

      # Application Configuration
      NODE_ENV: "production"

      # Optional Configuration
      LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: "false"
      TELEMETRY_ENABLED: "true"


    volumes:
      - langfuse_data:/app/data
    networks:
      - langfuse-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  clickhouse_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local
  langfuse_data:
    driver: local

networks:
  langfuse-network:
    driver: bridge
""".ENV FİLE """
# PostgreSQL Configuration
POSTGRES_PASSWORD=g66XvqAfsA2lDKCWiLPFeNOVm

# ClickHouse Configuration

CLICKHOUSE_PASSWORD=ySXxTJYPiGMuiEPRlzOmlLBSN

# Redis Configuration
REDIS_PASSWORD=XUrUcPr2bjsOu9ZJ4gdXOAOfU

# Langfuse Application Configuration
NEXTAUTH_SECRET=ggBSpcdEdHykRaqJHSdImI65x
SALT=s6t4yRkCy8sxWGdKs0Vw1oBMI

# MinIO Configuration
MINIO_ROOT_PASSWORD=FNRTNqsMgSKA7OYTNvPsT78FJ

# Ports (change if needed)
LANGFUSE_PORT=13000
POSTGRES_PORT=15432
CLICKHOUSE_HTTP_PORT=18123
CLICKHOUSE_TCP_PORT=19000
REDIS_PORT=16379
MINIO_API_PORT=19001
MINIO_CONSOLE_PORT=19002"""

Hi @Steffen911 , you can see my configuration files

**Comment by Steffen911** [comment]
@Enescigdem `      LANGFUSE_S3_EVENT_UPLOAD_ENABLED: "false"` is not supported for Langfuse v3 and you'll have to supply all S3 configuration items.

**Comment by jtsang4** [comment]
I'm experiencing this issue as well. Are there any updates on a potential fix?

**Comment by Steffen911** [comment]
@jtsang4 As there are multiple issues being discussed within this thread that heavily deploy on the deployment config it's not necessarily the case that you observe exactly the same issue. Could you create a new ticket and describe the problem you observe with the configuration you use to deploy Langfuse? Feel free to tag me there.

**Comment by Enescigdem** [comment]
> [@Enescigdem](https://github.com/Enescigdem) ` LANGFUSE_S3_EVENT_UPLOAD_ENABLED: "false"` is not supported for Langfuse v3 and you'll have to supply all S3 configuration items.

This worked for me, thanks @Steffen911

**Comment by oleksandrsv** [comment]
Same issue here in aws self hosted:

```
sh-4.2$ sudo docker logs 890267e498f0
Script executed successfully.
Prisma schema loaded from packages/shared/prisma/schema.prisma
Datasource "db": PostgreSQL database "langfuse", schema "public" at "langfuse-staging-postgres.xxx.amazonaws.com:5432"

276 migrations found in prisma/migrations


No pending migrations to apply.
  ▲ Next.js 14.2.21
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000

 ✓ Starting...
Running init scripts...
 ✓ Ready in 1081ms
Failed to prepare server TypeError: Cannot set property message of [object Object] which has only a getter
    at NextNodeServer.prepareImpl (/app/node_modules/.pnpm/next@14.2.21_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1.47.2_babel-plugin_yqlzwwxnhgfuesbfmfmtmhekse/node_modules/next/dist/server/next-server.js:476:33)
```

**Comment by Steffen911** [comment]
@oleksandrsv Could you share a configuration that reproduces this problem?
