### ISSUE TITLE
bug: Error in Worker when luanch Worker in local in my PC

### ISSUE THREAD

**Issue by kongchujun** [langfuse/langfuse#4830]
### Describe the bug

2024-12-24T07:06:52.737Z error  Error running background migrations The "listener" argument must be of type function. Received an instance of Object
TypeError: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (node:events:276:3)
    at ClientRequest.once (node:events:653:3)
    at new ClientRequest (node:_http_client:242:10)
    at Object.request (node:http:103:10)
    at C:\work\node_modules\.pnpm\dd-trace@5.28.0\node_modules\dd-trace\packages\datadog-instrumentations\src\http\client.js:35:24
    at Object.request (C:\work\node_modules\.pnpm\@opentelemetry+instrumentation-http@0.53.0_\@opentelemetry+instrumentation-http\src\http.ts:683:26)
    at safeExecuteInTheMiddle (C:\work\aimarkets-ai-lens\node_modules\.pnpm\@opentelemetry+instrumentation@0.53.0_\@opentelemetry+instrumentation\src\utils.ts:32:14)
    at C:\work\node_modules\.pnpm\@opentelemetry+instrumentation-http@0.53.0_\@opentelemetry+instrumentation-http\src\http.ts:682:67
    at AsyncLocalStorageContextManager.with (C:\work\aimarkets-ai-lens\node_modules\.pnpm\@opentelemetry+context-async-hooks@1.26.0_\@opentelemetry+context-async-hooks\src\AsyncLocalStorageContextManager.ts:40:36)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
2024-12-24T07:06:53.437Z info  Upserted default model prices (clx30hkrx0000w9mz7jlqioial)
2024-12-24T07:06:53.630Z info  Finished upserting default model prices in 10541ms

### To reproduce

clone langfuse 3.2.0
cd langfuse
pnpm install 
cd worker
npm run dev

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
Hi @kongchujun - thanks for raising this! Unfortunately I cannot reproduce this on my end. Could you please share more information on your runtime environment (node version) and retry a clean install?

**Comment by maxdeichmann** [comment]
@kongchujun thanks for raising this issue with us. Do you continue to encounter this issue? As Hassieb mentioned, we are not able to reproduce this. Could you please share more information on your runtime environment (node version) and retry a clean install?
