### ISSUE TITLE
bug: Not able to login after upgrade to v3

### ISSUE THREAD

**Issue by mulakkalfaizal** [langfuse/langfuse#4859]
### Describe the bug

Previous version 2.92.0 OSS
Upgraded version 3.10
Deployment environment: kubernetes using helm chart

Background migration ran successfully but the login is not working. i am getting the below error when i try to login

`2024-12-31T13:35:12.073Z error 	prisma:error
Invalid `prisma.user.findUnique()` invocation:

The column `t8.deleted_at` does not exist in the current database.
[next-auth][error][JWT_SESSION_ERROR]
https://next-auth.js.org/errors#jwt_session_error
Invalid `prisma.user.findUnique()` invocation:

The column `t8.deleted_at` does not exist in the current database. {
  message: '\n' +
    'Invalid `prisma.user.findUnique()` invocation:\n' +
    '\n' +
    '\n' +
    'The column `t8.deleted_at` does not exist in the current database.',
  stack: 'PrismaClientKnownRequestError: \n' +
    'Invalid `prisma.user.findUnique()` invocation:\n' +
    '\n' +
    '\n' +
    'The column `t8.deleted_at` does not exist in the current database.\n' +
    '    at $n.handleRequestError (/app/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7315)\n' +
    '    at $n.handleAndLogRequestError (/app/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)\n' +
    '    at $n.request (/app/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)\n' +
    '    at async l (/app/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)\n' +
    '    at async /app/web/.next/server/chunks/9388.js:1:12647\n' +
    '    at async /app/web/.next/server/chunks/6373.js:27:18246\n' +
    '    at async Object.session (/app/node_modules/.pnpm/next-auth@4.24.11_next@14.2.15_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1_xriyl6wjkdcwfaz3tyk4i4plby/node_modules/next-auth/core/routes/session.js:52:30)\n' +
    '    at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.24.11_next@14.2.15_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1_xriyl6wjkdcwfaz3tyk4i4plby/node_modules/next-auth/core/index.js:136:27)\n' +
    '    at async NextAuthApiHandler (/app/node_modules/.pnpm/next-auth@4.24.11_next@14.2.15_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1_xriyl6wjkdcwfaz3tyk4i4plby/node_modules/next-auth/next/index.js:18:19)\n' +
    '    at async p (/app/web/.next/server/pages/api/auth/[...nextauth].js:1:5139)',
  name: 'PrismaClientKnownRequestError'
}

`

### To reproduce

1. Take backup of existing database
2. Update the helm chart to point to the new database
3. run helm upgrade to deploy
4. if you check the logs of worker you can see that migration is running 
5. try to login to the new v3 langfuse , you will not be able to login
6. you can see the above error log in the web container

### Are you interested to contribute a fix for this bug?

No

**Comment by mulakkalfaizal** [comment]
@dusu how can i make sure all the migration ran successfully ?

**Comment by mulakkalfaizal** [comment]
![image](https://github.com/user-attachments/assets/1d8fa39b-e44e-46d5-99ce-92c4f19e3261)

**Comment by marcklingen** [comment]
Sorry for the slow response here<br><br>The deleted_at column was added to the projects table recently. Can you check the prisma_migrations table in postgres whether this migrations was applied successfully?<br>[https://github.com/langfuse/langfuse/blob/main/packages/shared/prisma/migrations/20241124115100_add_projects_deleted_at/migration.sql](https://github.com/langfuse/langfuse/blob/main/packages/shared/prisma/migrations/20241124115100_add_projects_deleted_at/migration.sql)

**Comment by maxdeichmann** [comment]
@mulakkalfaizal thanks for raising the issue above. Can you share whether all migrations have been applied to postgres? For this, you can share the content of the postgres table "_prisma_migrations" here.
