### ISSUE TITLE
bug: can't run langfuse locally

### ISSUE THREAD

**Issue by Wildhammer** [langfuse/langfuse#629]
### Describe the bug

getting 404 error when trying to connect to the local langfuse server

### To reproduce

run server locally:

```
# Clone repository
git clone https://github.com/langfuse/langfuse.git
cd langfuse
 
# Run server and db
docker compose up -d
```

go to localhost:3000 and create an api key pair

then in python run:

```python
from langfuse.callback import CallbackHandler
handler = CallbackHandler(PUBLIC_KEY, SECRET_KEY, 'http://localhost:3000', True)
handler.auth_check()
```

getting the following error:

```
DEBUG:langfuse:consumer is running...
ERROR:langfuse:Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/646516/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/client.py", line 156, in auth_check
    projects = self.client.projects.get()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/646516/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/api/resources/projects/client.py", line 44, in get
    raise NotFoundError(pydantic.parse_obj_as(typing.Any, _response.json()))  # type: ignore
                                                          ^^^^^^^^^^^^^^^^
  File "/Users/646516/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/httpx/_models.py", line 761, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
[/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/playground.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/playground.ipynb) Cell 7 line 1
      [8](vscode-notebook-cell:/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/playground.ipynb#W6sZmlsZQ%3D%3D?line=7) from langfuse.callback import CallbackHandler
      [9](vscode-notebook-cell:/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/playground.ipynb#W6sZmlsZQ%3D%3D?line=8) handler = CallbackHandler(PUBLIC_KEY, SECRET_KEY, 'http://localhost:3000/', True)
---> [10](vscode-notebook-cell:/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/playground.ipynb#W6sZmlsZQ%3D%3D?line=9) handler.auth_check()
     [12](vscode-notebook-cell:/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/playground.ipynb#W6sZmlsZQ%3D%3D?line=11) # Setup Langchain
     [13](vscode-notebook-cell:/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/playground.ipynb#W6sZmlsZQ%3D%3D?line=12) from langchain.chains import LLMChain

File [~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/callback.py:105](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/callback.py:105), in CallbackHandler.auth_check(self)
    [103](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/callback.py:103) def auth_check(self):
    [104](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/callback.py:104)     if self.langfuse is not None:
--> [105](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/callback.py:105)         return self.langfuse.auth_check()
    [106](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/callback.py:106)     elif self.trace is not None:
    [107](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/callback.py:107)         projects = self.trace.client.projects.get()

File [~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/client.py:164](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/client.py:164), in Langfuse.auth_check(self)
    [162](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/client.py:162) except Exception as e:
    [163](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/client.py:163)     self.log.exception(e)
--> [164](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/client.py:164)     raise e

File [~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/client.py:156](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/client.py:156), in Langfuse.auth_check(self)
    [154](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/client.py:154) def auth_check(self) -> bool:
    [155](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/client.py:155)     try:
--> [156](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/client.py:156)         projects = self.client.projects.get()
...
    [354](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:354) except StopIteration as err:
--> [355](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:355)     raise JSONDecodeError("Expecting value", s, err.value) from None
    [356](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:356) return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?24abecf0-02eb-454d-b82c-daad6795dbfd) or open in a [text editor](command:workbench.action.openLargeOutput?24abecf0-02eb-454d-b82c-daad6795dbfd). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
[/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/playground.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/playground.ipynb) Cell 7 line 4
      [1](vscode-notebook-cell:/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/playground.ipynb#X12sZmlsZQ%3D%3D?line=0) from langfuse import Langfuse
      [3](vscode-notebook-cell:/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/playground.ipynb#X12sZmlsZQ%3D%3D?line=2) langfuse = Langfuse(PUBLIC_KEY, SECRET_KEY, 'http://localhost:3000/')
----> [4](vscode-notebook-cell:/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/playground.ipynb#X12sZmlsZQ%3D%3D?line=3) langfuse.client.projects.get()

File [~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/api/resources/projects/client.py:44](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/api/resources/projects/client.py:44), in ProjectsClient.get(self)
     [42](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/api/resources/projects/client.py:42)     raise MethodNotAllowedError(pydantic.parse_obj_as(typing.Any, _response.json()))  # type: ignore
     [43](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/api/resources/projects/client.py:43) if _response.status_code == 404:
---> [44](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/api/resources/projects/client.py:44)     raise NotFoundError(pydantic.parse_obj_as(typing.Any, _response.json()))  # type: ignore
     [45](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/api/resources/projects/client.py:45) try:
     [46](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/langfuse/api/resources/projects/client.py:46)     _response_json = _response.json()

File [~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/httpx/_models.py:761](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/httpx/_models.py:761), in Response.json(self, **kwargs)
    [760](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/httpx/_models.py:760) def json(self, **kwargs: typing.Any) -> typing.Any:
--> [761](https://file+.vscode-resource.vscode-cdn.net/Users/646516/Code/gen-ai/app/packages/rag-aws-bedrock/~/Library/Caches/pypoetry/virtualenvs/rag-aws-bedrock-FM9GgLg5-py3.11/lib/python3.11/site-packages/httpx/_models.py:761)     return jsonlib.loads(self.content, **kwargs)

File [/opt/homebrew/Cellar/python](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python)@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    [341](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py:341)     s = s.decode(detect_encoding(s), 'surrogatepass')
    [343](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py:343) if (cls is None and object_hook is None and
    [344](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py:344)         parse_int is None and parse_float is None and
    [345](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py:345)         parse_constant is None and object_pairs_hook is None and not kw):
--> [346](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py:346)     return _default_decoder.decode(s)
    [347](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py:347) if cls is None:
    [348](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py:348)     cls = JSONDecoder

File [/opt/homebrew/Cellar/python](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python)@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    [332](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:332) def decode(self, s, _w=WHITESPACE.match):
    [333](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:333)     """Return the Python representation of ``s`` (a ``str`` instance
    [334](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:334)     containing a JSON document).
    [335](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:335) 
    [336](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:336)     """
--> [337](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:337)     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    [338](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:338)     end = _w(s, end).end()
    [339](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:339)     if end != len(s):

File [/opt/homebrew/Cellar/python](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python)@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    [353](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:353)     obj, end = self.scan_once(s, idx)
    [354](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:354) except StopIteration as err:
--> [355](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:355)     raise JSONDecodeError("Expecting value", s, err.value) from None
    [356](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:356) return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by marcklingen** [comment]
Thanks for raising this, happy to help debug. To confirm, you were able to access localhost:3000 to create a project and API keys but get this error when trying to create the callback handler on the same machine?

**Comment by qiankunli** [comment]
your python client version may be not match with langfuse server.

**Comment by Wildhammer** [comment]
@qiankunli not sure if I understand why that matters as I am accessing langfuse server over http

**Comment by marcklingen** [comment]
Agree with @qiankunli, the /api/public/projects route was introduced in Langfuse 1.7.0. When self-hosting Langfuse, are you on a more recent version than 1.7.0?

**Comment by Wildhammer** [comment]
@marcklingen I clone the repo and been pulling for changes every day. I am on main branch. 

`commit 803a19ff3bf1aedffe8882f3d81bd4d2582d36f7 (HEAD -> main, origin/main, origin/HEAD)`

**Comment by he-org** [comment]
run into the same issue, any update?

**Comment by he-org** [comment]
Figured out, need to upgrade the docker too, 
# Stop server and db
docker compose down

# Pull latest changes
git pull
docker-compose pull

# Run server and db
docker compose up -d

**Comment by Wildhammer** [comment]
has `auth_check` method been removed? I don't see it anymore

**Comment by marcklingen** [comment]
Auth_check included in python sdk
https://github.com/langfuse/langfuse-python/blob/38175ad19b479422c6710c504cd1d6398ea35874/langfuse/client.py#L155-L165

Projects api route
https://github.com/langfuse/langfuse/blob/main/src/pages/api/public/projects.ts

Just tried it and can confirm that it works: https://colab.research.google.com/drive/1Djhn7WzcywPysmOJauWCltomFZIayicy#scrollTo=qG2WS-eNKIHD

@Wildhammer can you help me reproduce this? Can you confirm that you have the same issue when using Langfuse Cloud (free account)?

**Comment by marcklingen** [comment]
@Wildhammer any update on this? Would love to help in case you still encounter this issue

**Comment by marcklingen** [comment]
Closing this for now. Happy to reopen if the problem persists.
