### ISSUE TITLE
how to debug:  HTTP error while fetching Langfuse: 207 ? running locally

### ISSUE THREAD

**Issue by archywillhe** [langfuse/langfuse#942]
### Describe the bug

got this error out of nowhere 

```
LangfuseFetchHttpError: HTTP error while fetching Langfuse: 207
        at retriable (/Users/archy/ARCH_GPT/ArchGPT/lib/node_modules/langfuse-core/src/index.ts:466:17)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at retriable (/Users/archy/ARCH_GPT/ArchGPT/lib/node_modules/langfuse-core/src/utils.ts:33:19)
        at Langfuse.fetchWithRetry (/Users/archy/ARCH_GPT/ArchGPT/lib/node_modules/langfuse-core/src/index.ts:448:12) {
      response: _Response [Response] {
        [Symbol(realm)]: null,
        [Symbol(state)]: {
          aborted: false,
          rangeRequested: false,
          timingAllowPassed: true,
          requestIncludesCredentials: true,
          type: 'default',
          status: 207,
          timingInfo: [Object],
          cacheState: '',
          statusText: 'Multi-Status',
          headersList: [_HeadersList],
          urlList: [Array],
          body: [Object]
        },
        [Symbol(headers)]: _HeadersList {
          cookies: null,
          [Symbol(headers map)]: [Map],
          [Symbol(headers map sorted)]: null
        }
      }
    }
```

### To reproduce

followed the tutorial and without using langchain

**Comment by maxdeichmann** [comment]
@archywillhe thanks for reporting this. Do you still have this issue? Could you maybe turn the debug mode on and send us the logs? (https://langfuse.com/docs/sdk/typescript#debugging) 
We will improve the logs of the SDK so that it becomes more obvious what is going on.

**Comment by marcklingen** [comment]
closing as stale, please reopen if you still have this issue and can share more context
