### ISSUE TITLE
bug: JSON serializability issues

### ISSUE THREAD

**Issue by SinghCoder** [langfuse/langfuse#948]
### Describe the bug

Langfuse fails to serialize some of the runs with error:

```
Exception in adding task Object of type <X> is not JSON serializable
```

where X = a custom type.

### To reproduce

```python
@dataclass
class SearchResponse:
    text: str
    id: str

@dataclass
class AnswerChainInput:
    query: str
    role_description: str
    articles: list[SearchResponse]
    qa_list: list[SearchResponse]
```

I have two LangChain chains, KBChain and AnswerChain, KBChain outputs a dict with {"articles": list[SearchResponse], "qa_list": list[SearchResponse]

and AnswerChain expects AnswerChainInput as input. I am using LCEL to pass around outputs.
When I run the chain, this is what Langfuse outputs:

```
2024-01-24 14:45:21,670 - ERROR - Exception in adding task Object of type AnswerChainInput is not JSON serializable
Traceback (most recent call last):
  File "..../langfuse/task_manager.py", line 236, in add_task
    json.dumps(event, cls=EventSerializer)
  File "..../json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "..../json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "..../json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "..../langfuse/serializer.py", line 34, in default
    return JSONEncoder.default(self, obj)
  File "..../json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AnswerChainInput is not JSON serializable
```

**Comment by yhrchan** [comment]
I am also encountering the same, please assist, thanks

```
2024-01-27 02:03:57 - Exception in adding task Object of type ObjectId is not JSON serializable
Traceback (most recent call last):
  File "/home/rchan/Development/projects/langchain-mongodb/.venv/lib/python3.10/site-packages/langfuse/task_manager.py", line 236, in add_task
    json.dumps(event, cls=EventSerializer)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/rchan/Development/projects/langchain-mongodb/.venv/lib/python3.10/site-packages/langfuse/serializer.py", line 34, in default
    return JSONEncoder.default(self, obj)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
```

**Comment by SinghCoder** [comment]
@marcklingen @maxdeichmann I have raised a PR https://github.com/langfuse/langfuse-python/pull/357 to fix this. Can one of you take a look when you get some time?

**Comment by maxdeichmann** [comment]
@SinghCoder, thanks a lot for the contribution and the link to the Langchain Repo. I added some logic and testing to make this part more robust. Please re-open if this appears again.

cc @yhrchan, your issue is solved as well.

**Comment by SinghCoder** [comment]
Thank you so much!!!
