### ISSUE TITLE
bug: Langfuse was not able to parse the LLM model.

### ISSUE THREAD

**Issue by shangjian2022** [langfuse/langfuse#971]
### Describe the bug

Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. Please create an issue so we can fix your integration: https://github.com/langfuse/langfuse/issues/new/choose
2 validation errors for SdkLogEvent
timestamp
  str type expected (type=type_error.str)
body
  field required (type=value_error.missing)
Traceback (most recent call last):
  File "c:\Users\huangbin\anaconda3\envs\myenv\lib\site-packages\langfuse\callback.py", line 680, in __on_llm_action
    self._report_error(
  File "c:\Users\huangbin\anaconda3\envs\myenv\lib\site-packages\langfuse\callback.py", line 818, in _report_error
    event = SdkLogEvent(id=str(uuid4()), data=error, timestamp=_get_timestamp())
  File "c:\Users\huangbin\anaconda3\envs\myenv\lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for SdkLogEvent
timestamp
  str type expected (type=type_error.str)
body
  field required (type=value_error.missing)
Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. Please create an issue so we can fix your integration: https://github.com/langfuse/langfuse/issues/new/choose
2 validation errors for SdkLogEvent
timestamp
  str type expected (type=type_error.str)
body
  field required (type=value_error.missing)
Traceback (most recent call last):
  File "c:\Users\huangbin\anaconda3\envs\myenv\lib\site-packages\langfuse\callback.py", line 680, in __on_llm_action
    self._report_error(
  File "c:\Users\huangbin\anaconda3\envs\myenv\lib\site-packages\langfuse\callback.py", line 818, in _report_error
    event = SdkLogEvent(id=str(uuid4()), data=error, timestamp=_get_timestamp())
  File "c:\Users\huangbin\anaconda3\envs\myenv\lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for SdkLogEvent
timestamp
  str type expected (type=type_error.str)
body
  field required (type=value_error.missing)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\huangbin\anaconda3\envs\myenv\lib\site-packages\langfuse\callback.py", line 692, in __on_llm_action
    self._report_error(
  File "c:\Users\huangbin\anaconda3\envs\myenv\lib\site-packages\langfuse\callback.py", line 818, in _report_error
    event = SdkLogEvent(id=str(uuid4()), data=error, timestamp=_get_timestamp())
  File "c:\Users\huangbin\anaconda3\envs\myenv\lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for SdkLogEvent
timestamp
  str type expected (type=type_error.str)
body
  field required (type=value_error.missing)
ERROR:langfuse:Run not found, see docs what to do in this case.
Traceback (most recent call last):
  File "c:\Users\huangbin\anaconda3\envs\myenv\lib\site-packages\langfuse\callback.py", line 759, in on_llm_end
    raise Exception("Run not found, see docs what to do in this case.")
Exception: Run not found, see docs what to do in this case.

### To reproduce

from langfuse.callback import CallbackHandler

handler = CallbackHandler(
    public_key = public_key,
    secret_key = secret_key,
    trace_name = "test1",
    user_id = 'huangbin'
)

from langchain.chat_models.tongyi import ChatTongyi

tongyillm = ChatTongyi(name="tongyi",model='qwen-72b-chat',dashscope_api_key=dashscope)

from langchain_core.prompts import ChatPromptTemplate
prompt = ChatPromptTemplate.from_messages([
    ("system", "You are world class technical documentation writer."),
    ("user", "{input}")
])

from langchain_core.output_parsers import StrOutputParser

output_parser = StrOutputParser()

chain = prompt | tongyillm | output_parser

prompt = ChatPromptTemplate.from_messages([
    ("system", "You are an enthusiastic assistant."),
    ("user", "{input}")
])

chain = prompt | tongyillm | output_parser
chain.invoke({"input":"hello"},config={"callbacks":[handler]})

### Additional information

![微信图片_20240127092623](https://github.com/langfuse/langfuse/assets/97206799/02f05341-a75e-4d32-9a4d-c841ffa34af3)

**Comment by mjoyce-nr** [comment]
I encountered the same error when invoking the following code:  

```
from langfuse.callback import CallbackHandler 
handler = CallbackHandler()
llm_response = self.llm_chain.run(**inputs, stop=self.stop,  callbacks=[handler], verbose=False)
callbacks[0].langfuse.flush()
```

**Comment by maxdeichmann** [comment]
@shangjian2022 thanks for reporting this issue. As of [release 2.11.0](https://github.com/langfuse/langfuse-python/releases/tag/v2.11.0), this issue was resolved. Feel free to re-open this issue if this appears again.
